### ISSUE TITLE
Destination tags should be 64-bit

### ISSUE THREAD

**Issue by kballard** [stellar/stellar-protocol#1]
Destination tags, as I understand them, are unsigned 32-bit integers. That seems like an unnecessary limitation. They should be 64-bit integers. JavaScript can use strings to represent them if that's a concern (as JavaScript can only represent integers up to 52 bits).

A few points in favor:

1. In the theoretical future world where Stellar takes off and is used everywhere, one recipient might actually need to distinguish payments to more than 4 billion different accounts. Using multiple destination addresses isn't a great solution, because people will expect to be using something like `payments@domain.com`. As an example of who might need more than 4 billion tags, a gateway that converts between STR and BTC (assuming BTC also is ubiquitous) might, as BTC addresses are free to create and therefore you could have tens or hundreds of addresses per user.
2. Proving ownership of an address is easiest done by sending a payment of a specified tiny amount to an address with a unique destination tag. 4 billion tags is a lot, but it's still not enough to really be totally secure. With a 10 stroop fee, and assuming a 1 stroop payment (because the payment amount is irrelevant), you can run through all the tags with just over 47k STR. With the current value on stellarvalue.org (I'm not sure how accurate it is, but it's ballpark at least), that's less than $300. Bumping the destination tags up to 64-bit obviously makes this attack impossible.

I can't think of any good reason against this change. 64-bit integers are easy to handle in modern software, have no real performance penalty to speak of, and as I said before, JavaScript clients can treat it as a string, they have no need to actually represent it as a number

**Comment by jedmccaleb** [comment]
this is done now. The memo you can attach to transactions is much more flexible

**Comment by hethm999** [comment]
بالتأكيد انا هنا لاساعدكم انا اسمي هيثم مطور شبكة بلوكشين ومصدر الرموزات المميزة كونو مطمئنين دعونا نتعاون معأ لدي الملكية الفكرية في جميع البروتوكولات التي قمت بزيراتها لذالك دعونا نحط يدا علا يد ونمضي قدما
