### ISSUE TITLE
account_lines ledger bloat and API inefficiencies

### ISSUE THREAD

**Issue by johansten** [stellar/stellar-protocol#10]
Looking at account_lines and they way they are use by the official client, wouldn't is make more sense NOT to extend trust to EVERY issued currency for an issuer?

Taking justcoin as an example, there's 7318 trust lines right now. How many of those are ever going to be used? There's somewhere around 100 people actually holding currency.

If you, like me, think the stellar.txt approach is a rather weird design decision, then my only option today is to download the whole thing and parse it.

1) From a ledger bloat perspective, let the user decide what currencies to trust, and don't just default to "*"

2) From a client perspective, how about adding an "issued"-stanza to account_currencies?

**Comment by jedmccaleb** [comment]
no longer applies
