### ISSUE TITLE
Feature Request: Stellar address validation

### ISSUE THREAD

**Issue by danielissac** [stellar/stellar-protocol#1047]
Need a way to validate whether a XLM address is valid (no typo)
**Solution :**
An API end point that returns true if its valid, false if its invalid.

Is there already an REST API end point available to validate address?

**Comment by Kanaye** [comment]
Well what is a "valid" address for you ?
If it just means: the public key is valid: Use the sdk of your choice, most of them will have a way to verify the validity of publickeys.
e.g. for the js-sdk: https://stellar.github.io/js-stellar-base/StrKey.html#.isValidEd25519PublicKey

If you want to know wheter an account also exists: just query horizon for an account with the ID. If it exists ... well the public key will be valid and the account is funded (e.g. https://laboratory.stellar.org/#explorer?resource=accounts&endpoint=single&network=test ), if not, well the account is not funded and you can check via one of the SDKs if the public key is valid.

But an endpoint just for that purpose makes no sense to me as it's fairly easy to compute on your end via the SDKs.
