### ISSUE TITLE
SEP-6 extra_info

### ISSUE THREAD

**Issue by yuriescl** [stellar/stellar-protocol#1071]
SEP-6 successful [deposit ](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md#1-success-no-additional-information-needed) response include an `extra_info` field. This field is specified as being an object, but it has a single field inside, which is `message`.
Since SEP-6 is non-interactive and Wallets might wanna use it in an automated way, maybe the SEP should add flexibility to the response by allowing custom fields inside `extra_info`. This would allow each Anchor to specify it's own fields in the response.
Example:
1. At the moment, if it's a bank deposit for example, the Anchor would have to respond with something like:
```
{
  "how" : "Make a payment to BANK123 account ACCOUNT123 with note NOTE123",
  "id": "9421871e-0623-4356-b7b5-5996da122f3e",
  "eta": 1800
}
```
2. This can be difficult for the Wallet to parse. But if `extra_info` allowed custom fields, this could be the response:
```
{
  "how" : "Make a payment to BANK123 account ACCOUNT123 with note NOTE123",
  "id": "9421871e-0623-4356-b7b5-5996da122f3e",
  "eta": 1800,
  "extra_info": {
    "bank_name": "BANK123",
    "bank_account": "ACCOUNT123",
    "bank_note": "NOTE123",
  }
}
```

This makes it easier for Wallets to parse the response and get the values it needs to complete the deposit/withdrawal.

**Comment by JakeUrban** [comment]
Hi @yuriescl, I think this is a good idea. If we do this, I think it also makes sense to add a similar object to the `GET /transactions` response body, so the `extra_info` returned in a deposit or withdrawal response can be found without recreating a transaction.

@leighmcculloch curious on your thoughts here.

**Comment by leighmcculloch** [comment]
I like the idea. I'm wondering if before we go the custom field route, is there value in defining some common fields so that anchors implementing similar integrations use the same keys for the fields. What do you think?

**Comment by JakeUrban** [comment]
I think that makes sense. There are some SEP-9 fields that would probably fit here too:
- bank_account_number
- bank_number
- bank_branch_number

But there are others not in SEP-9 that could be relevant to many anchors:
- bank_memo/note
- bank_name
- address (for dropping off cash at a retail location)

Generally, we can try to think of standardized field names for pieces of information that would typically be included in the `"how"` message.
