### ISSUE TITLE
SEP-9: Adding organization registration date

### ISSUE THREAD

**Issue by ymatienzo** [stellar/stellar-protocol#1074]
### What problem does your feature solve?

The registration date of a business is a field that is always asked during onboarding. This field is currently missing in the organization KYC fields. 

### What would you like to see?
Adding  **organization.registration_date**  as part of the Organization KYC list of fields

**Comment by ymatienzo** [comment]
Hi, sorry for the late reply on this. I thought that this was the way to open the PR. Could you hint me where to do it?

**Comment by leighmcculloch** [comment]
Hi @ymatienzo, you can open a pull request (PR) by forking the repository, editing SEP-9, and opening a PR. If you already did that, could you share a link to it here so that I can link it to this issue and review and get it merged?

**Comment by leighmcculloch** [comment]
@ymatienzo The `organization.registration_date` field has been added. Thanks for suggesting!
