### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by MehdiAliakbar32** [stellar/stellar-protocol#1092]

**Comment by jmar42** [comment]
A new AMM or additional feature to current AMM to short assets.  People that are long an asset deposit asset XYZ.  Counter parties that want to short XYZ, deposit 150% of USD in turn for a withdrawl of XYZ asset.  USD is locked in the AMM and liquidity providers make liquidity fee.  When XYZ is returned, the USD is withdrawn to depositor.  This will solve inefficient markets.  The alternatives would be atomic swaps or CEX/CEFI.

**Comment by MehdiAliakbar32** [comment]
> ### What problem does your feature solve?
> ### What would you like to see?
> ### What alternatives are there?

**Comment by MehdiAliakbar32** [comment]
https://github.com/stellar/stellar-protocol/issues/1092#issue-1065122051
