### ISSUE TITLE
Retire PathPaymentStrictReceive, instead create PathPaymentReceiveMin

### ISSUE THREAD

**Issue by hot-bit-git** [stellar/stellar-protocol#1106]
#### What problem does your feature solve?
1. Exchange rate for tiny, stroop size payments will be more fair (closer to market rates)
2. Price spikes in price history and charts will be limited

#### Current status
PathPaymentStrictReceive works on two conditions:
1. Pay: NO MORE THAN
2. Receive: EXACTLY

#### What would you like to see?
Proposed PathPaymentStrictReceive  conditions:
1. Pay: NO MORE THAN
2. Receive: NOT LESS THAN

#### Examples
1. Currently one can buy about 1 SLT for 40 XLM.
With current conditions, 
    a. Pay: NO MORE THAN 0.0000001 SLT
    b. Receive: EXACTLY 0.0000001 XLM
price reported after the trade is 40 (or 1/40) times the market price, as payer pays 0.0000001 SLT and receiver receives 0.0000001 XLM.

   With the proposed rules (conditions):
     a. Pay: NO MORE THAN 0.0000001 SLT
     b. Receive: NOT LESS THAN 0.0000001 XLM
price reported after the trade would be close to the market price, as payer would pay 0.0000001 SLT and receiver would receive 0.0000040 XLM.

2. A transaction causing large price spike due to condition EXACTLY:
![stricReceive](https://user-images.githubusercontent.com/35734693/148051950-b5260903-44ca-46ea-bf93-186e73c0bb92.png)

#### Operation name change
As PathPaymentStrictReceive operation name would no longer be adequate, new operation PathPaymentReceiveMin would be required.

**Comment by jonjove** [comment]
In your example, why shouldn't the sender use `PathPaymentStrictSend` instead of `PathPaymentStrictReceive`? In that case, they would send exactly 0.0000001 SLT and receive not less than 0.0000040 XLM. How does a sender know which one to use? They can compute both prices and choose the better one.

**Comment by hot-bit-git** [comment]
>They can compute both prices and choose the better one.

As I have pointed out, receiver receives less than he could, which is not fair.

But it's not only about a better price.

Some parties, for whatever reason, use deliberately PathPaymentStrictReceive to cause massive price faking and huge candles on price charts. 
The above solution would prevent fake candles over 100% high, even though some smaller candles would be still possible due to rounding errors (up to 100%, but still better than 4000%).

The above solution would limit abuse of PathPaymentStrictReceive and make price history a bit more realistic and usable.
![xrp](https://user-images.githubusercontent.com/35734693/148099327-cdfaf05f-543d-41a3-a951-b1422eba8190.png)
On the image is a product of misuse of PathPaymentStrictReceive. Does it resemble a price chart? Will the new potential DEX user trust the DEX after seeing this?

**Comment by jonjove** [comment]
People are already working to improve the trade aggregations which are used to produce these charts: https://github.com/stellar/go/issues/4160.

> As I have pointed out, receiver receives less than he could, which is not fair.
I don't follow. With `PathPaymentStrictSend` you would get the 40:1 price that you expect. In what way does the "receiver receive less than he could"?

**Comment by hot-bit-git** [comment]
Indeed, `PathPaymentStrictSend` does not cause that problem. But I'm talking about using `PathPaymentStrictReceive` - sending 1 stroop of much more expensive asset with a set 1 stroop of less expensive as a receiving one, you will only receive 1/40 of what you could/should.

As in the image attached in the op, someone has sent 0.0000001 SLT and received only 0.0000001 XLM instead of 0.0000040 or so. Therefore the ledger registered 40x price spike.

Even if trade aggregations can be improved, the above behaviour of  `PathPaymentStrictReceive` seems far from optimal. Can be unfair with small amounts and is causing ledger to register kind of 'fake (but real)' prices. Filtering through trade_aggregations on one hand would show more realistic state, on the other it can fake the real state of the ledger, as those wild prices are real and registered.

**Comment by jonjove** [comment]
How would you propose to actually implement this? `PathPaymentStrictSend` works by propagating the "strict send" amount through the hops from source to destination, and `PathPaymentStrictReceive` works by propagating the "strict receive" amount _backwards_ through the hops from destination to source. In this case, we wouldn't have either number so how do you actually perform the calculation? Specifically, there are potentially many valid solutions. For example, a valid solution to

> a. Pay: NO MORE THAN 0.0000001 SLT
> b. Receive: NOT LESS THAN 0.0000001 XLM

is pay 0.0000001 SLT and receive 0.0000001 XLM.

**Comment by hot-bit-git** [comment]
Implementation could be a combination of methods used in `PathPaymentStrictSend` and `PathPaymentStrictReceive` as follows:

Transaction: send max nA receive min mB _(example: market price is 1A = 40B, transaction sets: send max 1A -> min 1B)_.

1. calculate outcome with the method:
`PathPaymentStrictSend`:  sent nA, received iB, 
return: price1 =  nA/iB _(example: price1 = 1/40)_
2. calculate outcome with the method:
`PathPaymentStrictReceive`: sent kA, received mB, 
return: price2 = kA/mB (example: price2 = 1)
3. if price1 < price2: _(example: 1/40 < 1):_ 
run real transaction like `PathPaymentStrictSend` does.
4. if price2 < price1: _(example: 1 > 1/40 so condition false):_ 
run real transaction like `PathPaymentStrictReceive` does.

**Problem**: this solution would add **compute cost** to the network. I don't know if lower network costs due to limitation of `PathPaymentStrictReceive` 0.0000001A -> 0.0000001B operations would offset additional compute costs of `PathPaymentReceiveMin`.

Another possible solution to `PathPaymentStrictReceive` 0.0000001A -> 0.0000001B abuse, would be simple, just to raise min. send value from 0.0000001A to 0.0000100A. However, different **problem** arises, as Litemint's NFTs are traded / 'swapped' using 1 stroop transactions. I don't know if trading those NFTs could work with only `PathPaymentStrictSend` operation, as this one is not as prone to abuse and min send could be left at 1 stroop.

Thank you for your effort and discussing this proposal.
