### ISSUE TITLE
SEP-6, 24, 31: add transaction status for discontinued transactions

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#1109]
### What problem does your feature solve?

Anchors may want to communicate to wallet application that specific in-progress transactions are no longer valid. For example, if a transaction is in `pending_user_transfer_start` for over X minutes, the anchor may want to consider this transaction abandoned by the user.

### What would you like to see?

All SEPs that process transactions (6, 24, & 31), should have a `status` value that indicates to client-side applications that the transaction cannot be continued.

Status valid candidates:

- `canceled`
- `invalid`
- `discontinued`
- `abondoned`

cc @lijamie98

**Comment by lijamie98** [comment]
In the MGI meeting on 1/27/2022, MGI wish to show something like `expired`. I think we may add `cancel`. 

For `invalid`, when does that happen?

**Comment by JakeUrban** [comment]
The values I listed are just suggestions, we could use `expired` instead 👍 

I can see a future where we have both `expired` and `canceled` though, since they indicate two different things. For now lets roll with `expired`.

**Comment by lijamie98** [comment]
Yes, that looks good. 

In your original list, I thought you are going to add more of the statuses to SEP24. Should we add the others as well?

**Comment by JakeUrban** [comment]
The "status value candidates" list was just ideas for the name, I didn't mean to indicate that we should add all those as distinct status values.

**Comment by accordeiro** [comment]
I think we should make `refunded` a first-class status, since combining a `refunded` boolean flag with other statuses is confusing (like what does it mean to have `refunded=true` and `status=pending_anchor`)?

So I like the plan of adding the following statuses:

- `expired`
- `cancelled`
- `refunded` 

And deprecating the boolean flag. Although I'm not sure how that flag is used in the wild, if at all.

**Comment by accordeiro** [comment]
I think we should think about this problem and #1122 together, since it touches the refund process.

**Comment by JakeUrban** [comment]
Reopening this because #1222 did not address this issue. We added the `refunded` status value, but not the `expired` status.
