### ISSUE TITLE
SEP-0014: Implementation or status

### ISSUE THREAD

**Issue by alejomendoza** [stellar/stellar-protocol#1120]
### What problem does your feature solve?

It would be nice to have SEP-0014 working now that NFTs have become really big and there's a need for a TOML that supports thousands of assets or more. 

### What would you like to see?

See the proposal on Awaiting Decision. Not sure what is missing for it to pass @orbitlens or why did it stay on draft for so long? What will it take for `ASSET_METADATA_SERVER` field on the TOML to work on the public network? This will solve a ton of our pain points when trying to issue a lot of assets and still verify those.

**Comment by leighmcculloch** [comment]
I don't know the answer to the questions about how we got here, but I'm wondering, would SEP-1's ability to split assets into separate files, which is an ability it has now, something that helps alleviates the pain points with issuing lots of assets?

I'm referring to this functionality of SEP-1:

https://github.com/stellar/stellar-protocol/blob/d26f73ec0791b0c07e90dd1c4fa63b9e1a018108/ecosystem/sep-0001.md#L154

**Comment by alejomendoza** [comment]
Even with having `toml="https://DOMAIN/.well-known/CURRENCY.toml"` as the only currency field, the file size limitation would still exist on a marketplace that wants to issue many assets on a daily basis, in the case of music, 60,000 tracks are uploaded to Spotify daily.  Which makes SEP-0014 a viable solution for these types cases.
