### ISSUE TITLE
github action "mddiffcheck" is broken

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-protocol#1159]
Looking at https://github.com/stellar/stellar-protocol/runs/5775535682?check_suite_focus=true
```
Run go get github.com/stellar/mddiffcheck
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
Error: Process completed with exit code 1.
```

It looks like Github actions moved to Go 1.18 in https://github.com/actions/virtual-environments/pull/5261 which broke "mddiffcheck".

https://go.dev/doc/go-get-install-deprecation#:~:text=go%20get%20%E2%80%99s%20ability%20to%20build%20and%20install,that%20can%E2%80%99t%20be%20built%20for%20the%20current%20platform.

**Comment by leighmcculloch** [comment]
Just need to change the `get` to `install` and add `@latest` on the end.

**Comment by ire-and-curses** [comment]
https://github.com/stellar/stellar-protocol/pull/1160
