### ISSUE TITLE
SEP-31 - Include FX rate conversion from destination to source token during refund process

### ISSUE THREAD

**Issue by nirojapanda** [stellar/stellar-protocol#1182]
### What problem does your feature solve?
When refunds are made in SEP 31, the sender might expect the refund amount in originating fiat token. So these refunds need to be converted back from receiving token to sender token. In order to do that, there is a need of FX conversion at the current available quotes.

### What would you like to see?
When refunds are made in SEP 31, the sender might expect the refund amount in originating fiat token. So these refunds need to be converted back from receiving token to sender token. In order to do that, there is a need of FX conversion at the current available quotes.

### What alternatives are there?
If not implemented, the receiving anchor will take the risk of losing value of the FX conversion rates change.

**Comment by JakeUrban** [comment]
@nirojapanda can we set up a time to discuss this issue? I don't want it to be forgotten but I don't fully understand this case.

**Comment by nirojapanda** [comment]
Discussed with Jake and would not be making this change. We recommend that the Receiving Anchor makes use of the amount_fee field in the Refunds Object to charge a fee (can be variable amount based on the conversion rate) to the sender to process the refunds. A disclaimer about the variable fee can be added by Sending Anchor to its sending clients.
