### ISSUE TITLE
Multiple source accounts in SEP-0007

### ISSUE THREAD

**Issue by johansten** [stellar/stellar-protocol#119]
"If the source account in the xdr is all zeros then the URI handler should replace the source account and sequence number with the user's source account and sequence number before it signs it. If the source account is set and the sequence number is 0 then the URI handler should replace only the sequence number before signing."

This assumes transactions only have one unknown source account.

**Comment by nikhilsaraf** [comment]
we will be updating the SEP to remove mutable source accounts for the XDR format of the URI scheme. so this issue no longer applies. will keep this open until the sep is changed.

**Comment by theaeolianmachine** [comment]
@nikhilsaraf did these updates ever get made? How much time do you think it would take to put together?

**Comment by nikhilsaraf** [comment]
@theaeolianmachine we concluded that there are a fair number of ways in which we may want to mutate a SEP-0007 URI, essentially leaving “holes” that should be filled in by a wallet. This warrants a new SEP altogether, which I’ve not begun work on yet.

**Comment by theaeolianmachine** [comment]
@nikhilsaraf would you mind creating an issue summarizing what the new SEP plans to address? Along with related issues (not sure if the changes mentioned in #157 are related or still a part of SEP-0007 updates).
