### ISSUE TITLE
SEP-39: use of `is_asset_anchored` to classify NFT

### ISSUE THREAD

**Issue by garantor** [stellar/stellar-protocol#1196]
### What problem does your feature solve?
It makes it easier to classify NFTs.

### What would you like to see?
Since the `is_asset_anchored` and `anchor_asset_type` are asset/currency specific within SEP-1, perhaps creators of NFTs can use this to classify their NFTs rather than using just the asset code. This way it would be easier to classify NFTs by just looking up their toml file. With this, NFTs can still use their NFT code/name when Creating asset rather than most creators specifying  `NFT` as their asset code when creating NFT.

```
[DOCUMENTATION]
ORG_URL="<https://ink.litemint.store>"

[[CURRENCIES]]
issuer="GAKZGD5BFXZ7P7P45WHTM6DODMOEWWJUSCAIPGYIVIPYQSVR6MM6YR7M"
code="DEMOASSET"
is_asset_anchored = true
anchor_asset_type = "NFT"
name="A demonstration of NFT metadata"
desc="This is a description of the cool NFT used in this demo."
image="https://cloudflare-ipfs.com/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/I/m/RickAstleyNeverGonnaGiveYouUp7InchSingleCover.jpg"
fixed_number=1
display_decimals=7

```

**Comment by JakeUrban** [comment]
Hi @garantor, as I understand this suggestion, we would just need to add an `NFT` value to the list of valid `anchor_asset_type` values correct? I think this is a great idea.

**Comment by garantor** [comment]
yes @JakeUrban
