### ISSUE TITLE
SEP-9: add `clabe_number` to list of standardized fields

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#1201]
### What problem does your feature solve?

Mexico's banking system makes heavy use of [CLABE numbers](https://bank.codes/guides/clabe-numbers-guide), but our standard does not support this value format.

### What would you like to see?

Add a `clabe_number` attribute to the standardized list.

### What alternatives are there?

CLABE numbers are composed of values, some of which are already standardized in SEP-9. These values are:

- `bank_branch`
- `bank_account_number`

However, we are missing attributes to describe the bank itself, as well as a "validation digit".

Given the added complexity of generating the CLABE number from a set of values passed via SEP-9 attributes, I would recommend adding a single `clabe_number` attribute instead, even if there is technically some overlap with the attributes we have already defined.

cc @leighmcculloch, what do you think?

**Comment by leighmcculloch** [comment]
👍🏻 We should include it. I'm surprised we don't have IBAN either in the list, that would serve the same purpose in other regions.
