### ISSUE TITLE
How to prove that a transaction is pre-auth?

### ISSUE THREAD

**Issue by methuz** [stellar/stellar-protocol#121]
Public key `GCGYUNCVPVS2DFOKMUQ57OP3CBZ3HSOOEPARSVP7DLXDEHEVB7EJIGOO`
Hash of transaction to be pre-auth:
`482e0044b698eb42b15e37c4ac5302c8e1d6220aee8cac58ca1295cddcd76848`

After I submit pre-auth transaction of the above hash. I got this data in signer section
 ```  
 {
      "public_key": "TAKX3KIOHTBHECSSLULYMZ5ANVU2WDTSL4NBDFQEPBGTDYSLF2AQCLRP",
      "weight": 1,
      "key": "TAKX3KIOHTBHECSSLULYMZ5ANVU2WDTSL4NBDFQEPBGTDYSLF2AQCLRP",
      "type": "preauth_tx"
    }
```

So my questions are
1. Why hash is not kept in ledger?
2. How do I turn public key and hash into Ed25519 key or vice versa? Or is there any way to prove that a transaction is pre-authed
for example 
```
f(GCGYUNCVPVS2DFOKMUQ57OP3CBZ3HSOOEPARSVP7DLXDEHEVB7EJIGOO,482e0044b698eb42b15e37c4ac5302c8e1d6220aee8cac58ca1295cddcd76848) == TAKX3KIOHTBHECSSLULYMZ5ANVU2WDTSL4NBDFQEPBGTDYSLF2AQCLRP
```

It would be great if I can have the following function :
1. f(pk, hash) => Ed25519Key
2. f(Ed25519Key, ?) => hash (I don't think this is possible)

**Comment by bartekn** [comment]
Please ask questions in [Stellar Stack Exchange](https://stellar.stackexchange.com/).
