### ISSUE TITLE
CAP-0047: Stop using "parent" 

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-protocol#1259]
### What problem does your feature solve?

Avoids use of parent, which is vague in this context.

### What would you like to see?

Use host function names that reflect the envelope type names, such as `create_contract_from_contract` or `create_contract_from_ed25519`. Any changes should be reflected in rs-stellar-contract-env and rs-stellar-contract-sdk as well.

### What alternatives are there?

Leave it as is. Choose a different naming scheme entirely.

**Comment by sisuresh** [comment]
https://github.com/stellar/stellar-core/pull/3485 is the last issue related to this. I know we're in the middle of a release so this won't get merged for a bit, so I think we can just close the issue since the core issue is just a test case change.

**Comment by jonjove** [comment]
Agreed, the task is effectively done. Closed.
