### ISSUE TITLE
CAP-0046: WebAssembly Smart Contract Runtime Environment

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-protocol#1277]
This issue tracks open issues related to https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046.md

- [ ] reconcile CAP with user visible changes (xdr, symbols exported, etc) in preview code (needed for downstream consumers)
- [ ] reconcile CAP with behavior (xdr, symbols exported, etc) in preview code
- [ ] review and update CAP based on community and protocol committee as to move it to "Accepted" state

**Comment by smac711** [comment]
@MonsieurNicolas should we address this issue given it will be closed in 20 days due to being "Stale"?

**Comment by jonjove** [comment]
This is one of the "top level" issues. No way it will be done soon. I've removed the stale label.

**Comment by smac711** [comment]
> This is one of the "top level" issues. No way it will be done soon. I've removed the stale label.

@jonjove should we break out the subtasks as separate issues in that case so we can prioritize those into the iterations?
