### ISSUE TITLE
CAP-0054: Smart Contract Standardized Asset

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-protocol#1278]
This issue tracks open issues related to https://github.com/stellar/stellar-protocol/blob/master/core/cap-0054.md

- [ ] reconcile CAP with user visible changes (xdr, symbols exported, etc) in preview code (needed for downstream consumers)
- [ ] reconcile CAP with behavior (xdr, symbols exported, etc) in preview code
- [ ] spin up generalized "token" spec that this CAP implements
- [ ] review and update CAP based on community and protocol committee as to move it to "Accepted" state

**Comment by jonjove** [comment]
Related to https://github.com/stellar/soroban-token-contract/issues/8

**Comment by smac711** [comment]
@MonsieurNicolas @jonjove for the above checklist do we have issues open already or should we convert the checklist into issues?

**Comment by jonjove** [comment]
Removed the stale label. I'm not really sure we need individual issues for these, but I'm open to it either way.

**Comment by smac711** [comment]
> Removed the stale label. I'm not really sure we need individual issues for these, but I'm open to it either way.

No problem, just wanted to see if that would help breaking out the subtasks and prioritizing them in the iterations.
