### ISSUE TITLE
CAP-0054: Merge KeyedAuthorization and Authorization?

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-protocol#1286]
Related to https://discord.com/channels/897514728459468821/935999748840751125/1004049166944718960, in which @leighmcculloch suggested

> Remove the distinction between keyed and non-keyed authorization, to reduce the number of authorization types/dimensions.

and I replied

> If we did this, then users always provide the key during signature verification which makes using contract functions that require signatures more consistent. The provided key must still be checked that it matches the expected key, so it doesn't simplify verification (on the contrary, it actually makes it harder because you could forget to do that check). The cost is ~32 bytes... there is probably some overhead but I have no idea how much. Is this trade-off worth it? Do we want this change to propagate into production, because token is a production contract--unlike the other examples?

**Comment by sisuresh** [comment]
I think we should keep both `KeyedAuthorization` and `Authorization` in the token contract. While the admin model is an edge case, token contract admins not having to specify the key when minting and burning should result in a non-negligible (this should be verified) cost improvement with no downside. I'd be curious to see the cost difference with and without the key when we have fees in place. 

We should point people towards the auth example (when we have it - https://github.com/stellar/soroban-examples/issues/58), which should just use `KeyedAuthorization`, and then add a comment somewhere that mentions the two methods of managing an admin (either store and verify the key in `KeyedAuthorization`, or use the optimization in the token contract).

**Comment by sisuresh** [comment]
The [Authorization](https://github.com/stellar/soroban-examples/tree/dev/authorization) example implements an admin using KeyedAuthorization.

**Comment by jonjove** [comment]
I'm pretty convinced that we should make this change everywhere, then evaluate the actual cost in practice when those measurements are available. Simplicity, usability, and standardization outweigh absolute performance in this case.

**Comment by sisuresh** [comment]
The token contract no longer uses `Authorization` as of https://github.com/stellar/soroban-token-contract/pull/86. Issue https://github.com/stellar/stellar-protocol/issues/1278 should track updating the CAP to match the implementation.
