### ISSUE TITLE
CAP-0054: Move the nonce into the arguments of contract functions?

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-protocol#1287]
Related to https://discord.com/channels/897514728459468821/935999748840751125/1004049166944718960, in which @leighmcculloch suggested 

> Move the nonce into the arguments of contract fns, so similar to Stellar transactions the body of the op will explicitly contain the nonce. This will simplify verifying signatures in applications that do not know the nonce. This will also improve debugging failing signatures, which is a painful thing to debug when not all non-constant parameters are explicit.)

**Comment by sisuresh** [comment]
I made this change in my [auth example](https://github.com/stellar/soroban-examples/pull/64). A minor issue here with this approach is that `KeyedAuthorization::Contract` doesn't use a nonce, so it's just ignored in that case.

**Comment by jonjove** [comment]
@sisuresh will you please update here when you figure out what to do with the nonce and make the relevant changes?

**Comment by jonjove** [comment]
In the case of `Contract` I mean.

**Comment by sisuresh** [comment]
The auth contract was updated to expect a nonce of 0 for now.

**Comment by sisuresh** [comment]
The token contract methods take the nonce as an argument as of https://github.com/stellar/soroban-token-contract/pull/86. Issue https://github.com/stellar/stellar-protocol/issues/1278 should track updating the CAP to match the implementation.
