### ISSUE TITLE
CAP-0054: Make it possible to control the context in which a signature is used?

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-protocol#1289]
### What problem does your feature solve?

Right now, it is impossible to guarantee that a signature is used in a specific context. This creates two related problems:

1. If I sign a message, I cannot guarantee that the message is used by a specific contract function. 
2. If I sign two messages, I cannot guarantee that the two signatures are used jointly.

Both of these are impossible because anyone observing the overlay could extract a signature from the arguments list of an `InvokeHostFunctionOp` and use it in a different context.

### What would you like to see?

Solving this problem would make many constructs much simpler and improve composability of the protocol. We should consider what would need to be done to control context, and if the costs and trade-offs make it actually worthwhile.

### What alternatives are there?

Don't support this usage. The downside is that it's a foot-gun for unaware users.

**Comment by leighmcculloch** [comment]
What's being described here is an existing flexibility that creates a foot-gun, and the feature that's missing is actually a constraint, less flexibility, but less flexibility that makes things typically safer. Is that correct?

**Comment by leighmcculloch** [comment]
There will always be cases like cross-chain bridges/interop that will require arbitrary signature verification capabilities, so I don't think we can completely prevent custom auth, but if we come up with a good common standard, good tooling for that standard, that should direct most non-interop contracts from doing a good thing?

**Comment by jonjove** [comment]
> I don't think we can completely prevent custom auth, but if we come up with a good common standard

A good standard is what I have in mind here, but of course people can always implement anything themselves. 

> What's being described here is an existing flexibility that creates a foot-gun, and the feature that's missing is actually a constraint, less flexibility, but less flexibility that makes things typically safer. Is that correct?

The existing design (or many designs like it) definitely creates a foot-gun, but is cheap and simple. Unfortunately, I don't know exactly know how to describe the feature that's missing because I don't actually know how to solve this problem yet. But making things safer is the goal.

**Comment by jonjove** [comment]
After discussing this issue with @sisuresh on several occasions and doing a little experiment yesterday, I think I have a proposal that resolves these issues. I doubt this is the best possible approach, but it is a starting point for future work.

First, we would need to add new functionality to get the current contract call stack. Schematically, the return value of this function looks like
```
(ContractID[n], Fn[n])
…
(ContractID[0], Fn[0])
HostFunction::Call
```
but there are various ways we could structure it in practice. It could be a dedicated host object type (not my preference), a vector of vectors `(Bytes, Symbol)`, a vector of maps `{ “contract”: Bytes, “function”: Symbol }`, etc. In what follows I’m just going to assume we have some way to get this information.

Second, we need to update the message format to incorporate the current contract call stack. This addresses problem (1) from my original post because the signer controls the execution path that makes the signature valid. It’s important to note that the parameters from the call stack aren’t hashed—and they can’t be because then you would need to produce a signature over a message that includes your signature—so it’s still possible that someone could use your signature in the same call stack but with different parameters. We’ll address this next. 

For clarity, let’s start with a simple but contrived example. Suppose that I want to send two payments to vendors and I want to make sure that either both happen or neither happen (it’s contrived, but let’s pretend that this is to preserve fairness so neither vendor thinks I’m paying the other vendor earlier). One way to do this would be to deploy a contract that uses `xfer` directly from my address. This contract would need to take 2 signatures for the `xfer`s from my key. But I want to ensure that the signatures are used together in this context, so I would need to submit a third signature from my key over the parameters to this function. The third signature doesn’t need a nonce (because the other signatures already have a nonce, so it won’t be reusable anyway) meaning this contract could be stateless. Now I can be sure that the two `xfer` will occur together.

As mentioned, the above example was very contrived because it could be done with `xfer_from`. One way would be to deploy a contract that uses `xfer_from` from my address to pay the vendors; to use this solution I first add an allowance for the deployed contract then invoke it. This isn’t always possible though. For example, there is no analog of `xfer_from` for `move_to_smart` and `move_to_classic`. Regardless, the example illustrates the key to controlling the context in which signatures can be used: the call stack guarantees that it is used in a certain function, and additional signature(s) guarantee that the function does what it specified. The number and type of additional signatures varies. If all parties are trusted and working cooperatively, then a single signature could be sufficient. In the more likely scenario where the parties are not trusted and working cooperatively, then a signature from each signer is likely necessary.

The interesting thing about this approach is that it makes it possible to write contracts that can generically delegate privileged actions to other contracts. While experimenting, I wrote a contract that takes a map from public key to signatures (over the vector of actions) and a vector of actions (each action is a contract id, a function to call, a `KeyedEd25519Signature` that will be wrapped into a `KeyedAuthorization` and passed as the first parameter to the specified function, and the remaining arguments to the specified function). It then tries to perform the actions in order, checking that there is a valid signature in the map corresponding to the public key of the `KeyedEd25519Signature` and failing otherwise. The entire contract was about 70 lines. This kind of functionality could mitigate the need to deploy many one-off contracts to accomplish complex goals.

As stated in my initial paragraph, I doubt this is the best possible approach (and maybe it has some flaw I didn’t notice such that it doesn’t work at all) because it has a significant amount of complexity and overhead. I wrote this to start a discussion around what we could do and whether or not we should do it. Very interested to hear what people think and get some feedback (cc @leighmcculloch, @tomerweller, @monsieurnicolas).

**Comment by leighmcculloch** [comment]
To make sure I understand correctly the idea is to include the entire contract call stack into the signed message so that the message is only valid for that specific contract call stack. This means the signature wouldn't be valid if you tried to embed it within another contract call, or embed just part of it in a sub-portion of the stack.

I'd lean on a vector of vectors/tuples.

This sounds good to me.

**Comment by jonjove** [comment]
Yes, your understanding is correct.

**Comment by mootz12** [comment]
For your example:
> This contract would need to take 2 signatures for the xfers from my key. But I want to ensure that the signatures are used together in this context, so I would need to submit a third signature from my key over the parameters to this function. ...  Now I can be sure that the two xfer will occur together. 

I think I am missing something, but can you add some clarity as to how this would prevent the case where if the first `Token::xfer` failed and the "parent contract" aborted, the second `Token::xfer` gets submitted out of context by some node that is listening in?? It appears that all the information required to submit the second transfer exist (the `KeyedEd25519Signature` and relevant parameters are getting passed to the "parent contract"). Does the token contract now validate where it is in the contract stack during authorization, and that information is included in the `KeyedEd25519Signature`?

**Comment by sisuresh** [comment]
The two `Token::xfer` signatures will have taken the call stack into account. If the user expects the `xfer` to be submitted through a parent contract method (lets say contract_id == 1 and method == `atomic_swap`), and someone pulls the second signature out and submits it directly to the token contract, then the `xfer` method will fail verification because `xfer` will verify the signature using the current call stack, which will be missing the parent contract call (contract_id == 1 and method == `atomic_swap`). The signatures take the expected context of the call into account, and if they are submitted out of context, they will fail.

**Comment by mootz12** [comment]
Thanks, that makes more sense. Is the authorization overhead going to apply to all token contract transactions, or, is this auth structure able to only run when required?

---

I wanted to offer another potential route (it's not thought out yet or tested)

A new type of `KeyedAuthorization` could be added, `KeyedAuthorization::Delegate` such that:
```
#[derive(Clone)]
#[contracttype]
pub enum KeyedAuthorization {
    Contract,
    Ed25519(KeyedEd25519Signature),
    Account(KeyedAccountAuthorization),
    Delegate(KeyedAccountAuthorization)
}
```
and the MessageV0 (pending changes to https://github.com/stellar/stellar-protocol/issues/1288) could be extended such that:
```
#[derive(Clone)]
#[contracttype]
pub struct MessageV0 {
    pub function: Symbol,
    pub contrct_id: BytesN<32>,
    pub network_id: Bytes,
    pub delegate: BytesN<32>, /// Preferably this is appended to the domain and/or made optional - pending issue 1288
    pub parameters: Vec<EnvVal>,
}
```

The validation for the `KeyedAuthorization::Delegate` would be the same as the `KeyedAuthorization::Account`, however, when building the Message, the `env.get_invoking_contract()` would be stored into the `delegate` field. Thus, the signature that gets validated will only be correct if the delegated contract is the one invoking the function and has been properly signed by the account.

The main goal here is to separate out contract call ordering from the signature, as this prohibits any conditional delegated calls. This would now the responsibility of a contract.

Things need to be cleaned up - but curious if any1 thinks there is potential here to explore further.

**Comment by sisuresh** [comment]
> Thanks, that makes more sense. Is the authorization overhead going to apply to all token contract transactions, or, is this auth structure able to only run when required?

Ideally, we would allow contracts to use the existing, simpler auth mechanism, and this more complex version would be optional.

> I wanted to offer another potential route (it's not thought out yet or tested)

First off, thanks for providing some input!

The issue with only taking the invoking contract into account is that adding another invocation to the call stack can be dangerous. If you expect the call stack to look like A->B->xfer, where the message for xfer is signed with B as the invoking contract, the message could be submitted through A, B, or any other contract that calls into B since A is not in the signature. As contracts build on other contracts, this could be a footgun.

> The main goal here is to separate out contract call ordering from the signature, as this prohibits any conditional delegated calls. This would now the responsibility of a contract.

Do you have an example how of this prohibits conditional delegated calls? I'm not sure I understand.

**Comment by paulbellamy** [comment]
Supposed contract A is a router, which dynamically delegates to other contracts based on either storage data, or other network conditions. For example, 1inch (and other market aggregators), calculates a routing across other AMM contracts to make a swap, so you don't necessarily know ahead of time which contracts it will call. You could pre-calculate the routing, then include that in the transaction (like we do for path payments today). In practice this is solved by approving the 1inch router contract, which then transfers your tokens to itself, then does the swaps from there.

**Comment by mootz12** [comment]
> f you expect the call stack to look like A->B->xfer, where the message for xfer is signed with B as the invoking contract, the message could be submitted through A, B, or any other contract that calls into B since A is not in the signature.

Good catch, this also clears up an original misunderstanding I had with the contract call stack. Unsure why I assumed this is different than a traditional call stack, but I incorrectly thought historical contract calls in the transaction would be included as well (IE - for the basic example the second `xfer` "stack" needed to include the first `xfer` call). So, conditional delegated calls would be perfectly fine!

The current proposal sounds good to me as well, assuming we are able to allow contracts that don't need this to just use the simpler auth mechanism.
---
@paulbellamy It's probably true that you could use a router to solve a majority of the use cases here. Consider https://docs.aave.com/developers/guides/credit-delegation, where Aave is stuck tracking borrow allowances on their debt tokens. A router / helper contract likely wouldn't be appropriate, as it would be stuck holding funds on behalf of all users wanting to delegate borrowing capacity. With a flexible "context controlled" signature scheme you could support something like credit delegation without any additional logic, state, or contracts.

**Comment by leighmcculloch** [comment]
@jonjove Are there cases where a signer doesn't want to constrain a full call stack, but rather just some amount of the call stack. For example, I sign for C -> B -> A, then someone else takes that signature and uses it in a call stack E -> D -> C -> B -> A. Does this need to be supported?

**Comment by jonjove** [comment]
Honestly, I'm not sure... I can't say for certain either way. I can't think of anything that says this is completely unreasonable, but likewise I can't really think of a practical use case. I don't think we'll know the answer to a question like that until people really start testing the limits of this kind of construction.

**Comment by leighmcculloch** [comment]
I think we might be making a few assumptions with this change, and we need to do more experimentation. For the release next week can we keep the full call stack idea out of auth, and then lets merge it after release so we have ample time to dog food it before others come up against it?

**Comment by jonjove** [comment]
That makes sense to me.

**Comment by leighmcculloch** [comment]
If we're deciding to keep the domain simple (https://github.com/stellar/rs-soroban-sdk/issues/577#issuecomment-1246961227), is this problem also out of scope of the soroban-auth SDK?

**Comment by jonjove** [comment]
If we don't do something like this, we're basically saying "sorry if you want to do anything complex safely." Are we comfortable saying that?

**Comment by jonjove** [comment]
Some concrete consequences of that are probably more single-use contracts and more smart wallets.

**Comment by leighmcculloch** [comment]
If we need to do this, then I think we're saying we need something like https://github.com/stellar/rs-soroban-sdk/issues/577#issuecomment-1246961227?

**Comment by jonjove** [comment]
I'm not certain these issues are if-and-only-if. Am I missing something? Why couldn't we do this without having a generic domain?
