### ISSUE TITLE
SEP-31: make `POST /transactions` payment-related response attributes optional

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#1290]
### What problem does your feature solve?

SEP-31 provides receiving anchors with two options when a `POST /transactions` request is made to their service.

1. Reject the transaction
2. Accept the transaction & return a Stellar account & memo to use for the payment

However, some receiving anchors may need to accept the transaction without immediately providing a Stellar account & memo to use in the payment. For example, its possible that the receiving anchor needs to perform asynchronous AML or KYC checks on a per-transaction basis before they are willing to accept payents. 

### What would you like to see?

We should make `stellar_account_id`, `stellar_memo`, & `stellar_memo_type` optional in the `POST /transactions` response, and update the flows documented in the protocol to use the transaction `id` returned to do one of the following:

1. Poll `GET /transactions/:id` until the status changes from `pending_receiver` to `pending_sender`. At this point `stellar_account_id`, `stellar_memo`, & `stellar_memo_type` should be populated in the response body.
2. Register a callback URL for changes in the transaction's status via `PUT /transactions/:id/callback`. The receiving anchor would make a callback to the sending anchor when the status changes from `pending_receiver` to `pending_sender`, and the callback payload should contain the `stellar_account_id`, `stellar_memo`, and `stellar_memo_type`

### What alternatives are there?

Don't change anything. This is a breaking change for sending anchors, since they likely have an assumption that the stellar account & memo is present in `POST /transactions` responses.

**Comment by gaclaudiu** [comment]
Hi @JakeUrban ,
Proposal looks good but I have some suggestions : 
- let's add transaction status on the post /transactions response in this way caller will not relay on the fields (stellar_account_id, stellar_memo, & stellar_memo_type)  beeing present or not in the response but can check status to see if he can initiate the transfer or need to waitt and query get endpoint to check status and payment details. 
- for this scenarios (in which AML check on transaction is done async and can take some time ) can we introduce a new status  like  pending_receiver_aml   to be more explicit so the calling anchor will know why is pending.  Cause the status pending_receiver is fine but is very generic and the caller doesn't know exactly why is still pending receiver. 
Let me know what you think on the above.

**Comment by JakeUrban** [comment]
> let's add transaction status on the post /transactions response

Good idea, we can do that.

> can we introduce a new status like pending_receiver_aml to be more explicit

I don't think thats a great idea because it increases the number of values the client has to be aware of. Meaning, `pending_receiver` and `pending_receiver_aml` pretty much mean the same thing for the SEP-31 sender -- that it has to wait.

I think a better approach would be to add something like a `status_message` attribute to the `GET /transactions` response. This could be a human-readable message like "the transaction is under review for AML compliance".

What do you think @gaclaudiu ?

**Comment by gaclaudiu** [comment]
status_message attribute in the GET /transactions works for me .  

Thanks @JakeUrban
