### ISSUE TITLE
CAP-0047 / CAP-0052: Should we compress WASM in transactions/operations?

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-protocol#1292]
WASM contracts can be fairly large. I recall discussion about compressing (perhaps with [LZ77](https://en.wikipedia.org/wiki/LZ77_and_LZ78)) WASM in transactions/operations to trade some network bandwidth for some CPU usage, but I couldn't find an issue to track it.

Tangentially related to https://github.com/stellar/rs-soroban-sdk/issues/415

**Comment by graydon** [comment]
moving a ways forwards -- this is not on critical path for futurenet

**Comment by smac711** [comment]
I will remove the "stale" label so it doesn't become closed.
