### ISSUE TITLE
CAP-0054: Should wrap/unwrap include destination addresses?

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-protocol#1295]
This would make it fewer steps to move money across the interoperability boundary, but might introduce other complexity that needs to be evaluated.

cc @tomerweller because he reminded me of this issue

**Comment by tomerweller** [comment]
adding a destination to `move_to_smart()` sounds pretty uncomplicated, though the [`wrap_then_do`](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0054.md#ecosystem-support-wrap-then-do-contract) example appears to provide a decent solution.

adding a destination to `move_to_classic()` might be more beneficial, but requires dealing with memos (or muxed accounts, or both), which does add additional complexity. 

Is that accurate, @jonjove ?

**Comment by jonjove** [comment]
> adding a destination to move_to_classic() might be more beneficial, but requires dealing with memos (or muxed accounts, or both), which does add additional complexity.

This is basically right, but I think it's even worse than that. Right now downstream systems grab memos etc from Horizon, and that will be quite different in the context of Soroban transactions... we'd have to figure that out too.
