### ISSUE TITLE
Freezing assets

### ISSUE THREAD

**Issue by roosmaa** [stellar/stellar-protocol#13]
It would be nice if the freezing of IOUs would be back-ported from Ripple to Stellar. I think it will play a crucial role when trying to convince current financial establishments to start using Stellar.

Currently the only way to ensure the ability to freeze funds is for the GW to create authorised accounts and give the user access to the regular key only. It would be fine, until several GWs started using this practice. Having two gateways doing this would mean it would be very hard to trade between IOUs issued by those GWs.

Having the freezing option would mean the GW can just release the IOUs to any Stellar account - knowing they can freeze them whenever there is real need for it.

**Comment by jedmccaleb** [comment]
this is done now
