### ISSUE TITLE
SEP-9: add `proof_of_income` field

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#1301]
### What problem does your feature solve?

Anchors often have different KYC "tiers" that allow their users to transact in small to large amounts. For example, with a limit of $2k per day, anchor could require a user's contact information and ID number, but if the user wants to transact more than $2k per day, then they have to provide additional KYC documentation.

However, the SEP-9 list of standard KYC fields does not include a field used for collecting income information.

### What would you like to see?

Adding a `proof_of_income` field of type `binary` standardizes anchors' request for the user to provide documentation proving their income level. Anchors may need this information to upgrade their users' to a higher "tier".

This field could be passed in a SEP-12 `PUT /customer` OR `POST /customer/files` request. If passed to `POST /customer/files`, the file ID returned would then need to be referenced in the subsequent `PUT /customer` request.

**Comment by JakeUrban** [comment]
cc @jessieserrino @howardtw

**Comment by JakeUrban** [comment]
@CassioMG

**Comment by CassioMG** [comment]
@JakeUrban this looks great to me. Would you mind if I open a PR for this change?

**Comment by JakeUrban** [comment]
Please do!

**Comment by CassioMG** [comment]
Here it is: https://github.com/stellar/stellar-protocol/pull/1310
