### ISSUE TITLE
CAP-0054: Add Renounce Ownership Function to Admin Interface

### ISSUE THREAD

**Issue by mootz12** [stellar/stellar-protocol#1306]
### What problem does your feature solve?
The wrapped/native token contract implements an admin interface that is missing a feature regarding asset control. Admins (who by default are the asset issuer) might not want to have control over actions like minting, burning, or freezing users. Allowing them to relinquish ownership should be done in an obvious and transparent way.

### What would you like to see?
Something similar to https://docs.openzeppelin.com/contracts/4.x/api/access#Ownable-renounceOwnership-- would be sufficient in providing a clear way for people to recognize a wrapped / native token contract without these controls.

### What alternatives are there?
The `admin` account can be locked from the Stellar classic side, so permission checks will always fail.

**Comment by mootz12** [comment]
@jonjove - The issue regarding the discussion in https://discord.com/channels/897514728459468821/982413811338313758

**Comment by leighmcculloch** [comment]
I think this is possible via a couple different methods.

The first would be to set the admin to a key that clearly has no known private key. This could be done by setting the admin as a `Identifier::Ed25519(BytesN::from_array(&env, &[0; 32])`, or as a zero AccountId, `GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF`. 

The second method would be to set the admin to a Stellar account that is locked. This would have the same impact as if the issuer was locked for an asset.

**Comment by greg9762** [comment]
What about protcall 20

**Comment by mootz12** [comment]
I would lean in favor of a `zero` identifier, probably an Ed25519, though I don't see any real trade-off between the two. 

I think it feels less confusing than just relying on vanilla Stellar account locking, which is non-obvious from the Soroban point of view if its an arbitrary public key. On that note, I would also be fine with some socially agreed upon public key on which corresponds to a locked stellar account.
