### ISSUE TITLE
CAP-0052 - provide a way to retrieve the return value of an on-chain contract call

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-protocol#1307]
CAP-0052 specifies that `INVOKE_HOST_FUNCTION_SUCCESS` returns an `SCVal` on success, but our implementation doesn't include this value. We should either include it, or provide an alternate way to retrieve the return value of a contract function. An alternative solution would be to return the value in a system event using CAP-0056.

**Comment by jonjove** [comment]
Some relevant discussion can be found in https://github.com/stellar/stellar-core/pull/3450#discussion_r898041956

**Comment by graydon** [comment]
This is still pending a core change: https://github.com/stellar/stellar-core/pull/3543

**Comment by sisuresh** [comment]
Closed by https://github.com/stellar/stellar-core/pull/3543
