### ISSUE TITLE
SEPs (6, 12, 24, 31): Update callback header from `X-Stellar-Signature` to `Signature`

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#1328]
### What problem does your feature solve?

Using the `X-` prefix for custom headers has been [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers), and there is an in-progress [RFC draft](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-message-signatures) to standardize signatures to verify the origin & integrity of requests that uses the `Signature` header.

While we won't update our callback signature scheme to match the draft until the RFC is finalized, we can update the header used, since that is unlikely to change.

### What would you like to see?

Update the header used for callbacks in various SEPs from `X-Stellar-Signature` to `Signature`

### What alternatives are there?

Keep the `X-Stellar-Signature` header.

**Comment by JakeUrban** [comment]
@tsachiherman @howardtw

**Comment by tsachiherman** [comment]
Where do we currently use this header field ?

**Comment by JakeUrban** [comment]
Oh sorry I meant to tag @C0x41lch0x41, but we use `X-Stellar-Signature` in our specification for anchor's making callbacks to their client applications: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#url-callback-signature

**Comment by C0x41lch0x41** [comment]
I don't see a problem with that.
@howardtw for Vibrant I would suggest to keep the code that matches `X-Stellar-Signature` and ADD `Signature` to have a backward compatibility.
Even when the RFC is finalized I am not sure we will want to use it but that's another discussion.
