### ISSUE TITLE
SEP-9: define a generalized account identifier format

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#1332]
### What problem does your feature solve?

Our existing bank-related fields are not sufficient for supporting the variety of off-chain account types that exist globally. Today, we have the following account-related fields:

Name | Type          | Description
-----|---------------|----
`bank_account_number` | string        | Number identifying bank account                                                             
`bank_number` | string        | Number identifying bank in national banking system (routing number in US)                   
`bank_branch_number` | string        |  Number identifying bank branch                                                              
`clabe_number` | string        | Bank account number for Mexico

`clabe_number` was added recently because the existing `bank_*` fields did not properly map to the scheme of Mexico's bank account system as described in #1201.

Now, we have a partner with a similar problem but related to Argentina's banking system and it's use of CBU & CVU numbers and aliases, see more [here](https://www.bcra.gob.ar/MediosPago/Politica_Pagos-i.asp).

Existing partners have attempted to decompose the account identifiers specific to their regions and use our existing fields in order to comply with the standard, but this is not ideal for them.

### What would you like to see?

Ideally, SEP-9 should offer a flexible system for communicating all bank or virtual account identifiers globally. Additionally, this system should allow account identifiers to be represented using the format that is standard to the region in which the business is operating.

I suggest we use the same pattern defined in [SEP-38's Asset Identification Format](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md#asset-identification-format), where a single field is used to communicate assets represented using various formats.

```
<scheme:identifier>
```

Each `scheme` defined in SEP-9 would also define a format to use for its `identifier`. Lets take the Brazilian PIX system for example. The `scheme` name could be `pix`, but a pix key can be one of a [few of values](https://help.remitly.com/s/article/sending-receiving-money-pix?language=en_US#:~:text=Your%20Pix%20key%20can%20be,Your%20mobile%20phone%20number).

- `pix:email:john@example.com`
- `pix:phone:+12345678901` --> phone numbers could be E164 formatted
- `pix:custom:john123`
- `pix:cpf:<a brazilian CPF number (tax ID)>`

I'm not familiar enough with Brazil's PIX, Argentina's CVU, or other non-US account identifiers, so we'll need to rely on our ecosystem to help define the proper formats.

**Comment by JakeUrban** [comment]
@lucaszanotelli let me know what you think of this proposal, and if you're on-board, can you help define the `<scheme:identifier>` formats for `CVU` & `CBU` numbers? I also see that there are `CVU` & `CBU` aliases, so maybe we should define formats for those as well?

**Comment by leighmcculloch** [comment]
One advantage we get with the current system is that we can any number of new fields and we can continue to rely on the JSON structure to provide the segmentation of different fields. Moving to a single string field is really just finding a new way to encode that same information, but without the benefit of being able to rely on JSON to provide that structure.

I think it would be reasonable to add a series of `pix_` fields and a series of fields for the Argentinian system.

If our current structure is insufficient, maybe we should start grouping fields, and at the top level the SEP says you choose from one-of `bank`, `clabe`, `pix`, etc. Each one would have its own rules for which fields are required, optional, or mutually exclusive within its object. For example:

```js
"bank": { "account_number": "...", "bank_number": "...", "branch_number": "..." },
"clabe": { "account_number": "...", "branch_number": "..." },
"pix": { "email": "...", "phone": "...", "custom": "...", "cpf": "..." },
```

**Comment by JakeUrban** [comment]
> However, one advantage we get with the current system is that we can add any number of new fields and we can continue to rely on the JSON structure to provide the segmentation of different fields.

Thats true, although the upstream SEPs that use SEP-9 fields all use flat structures currently (SEP-12's `PUT /customer`, SEP-6 `GET /deposit` & `GET /withdraw` URL params), and I think using a flat structure vs. formatted string is effectively equivalent.

The benefit to using a string format instead of adding many top level keys for `pix`, `clabe`, `cbu`, etc. is at the application level too. SDKs and deserializers wouldn't have to be updated for each new account type. The tooling would remain the same and only the logic would need to be updated.
