### ISSUE TITLE
Eliminating DEPOSIT_SERVER & FEDERATION_SERVER in SEP-0006

### ISSUE THREAD

**Issue by tomquisel** [stellar/stellar-protocol#134]
I'd like to propose a minor breaking change to SEP-0006, similar to what @istrau2 has suggested in the past.

The more I think about it, the more it seems like a hack to have both a `DEPOSIT_SERVER` and a `FEDERATION_SERVER` to enable deposits and withdrawals. The federation `forward` type that's used for withdrawals is unintuitive, and ties two protocols together that may have divergent needs. It's also confusing when adding new endpoints to SEP-0006. One has to choose between adding an endpoint that deals with withdrawals (like transaction history or KYC) to `DEPOSIT_SERVER` or adding it to the unrelated `FEDERATION_SERVER`.

I'd propose a single `ANCHOR_SERVER` that contains all endpoints for deposit, withdrawal, transaction history, and customer server.

Clients could then choose to be backwards compatible by looking for a `DEPOSIT_SERVER` vs. an `ANCHOR_SERVER` and making the requests to the appropriate URLs. The input and output formats for the endpoints would remain the same, they'd just live at different locations, making the overhead of being backwards compatible minimal.

An alternative is to have a `DEPOSIT_SERVER` and a `WITHDRAWAL_SERVER`, but then you end up with endpoints like `/transactions` or an endpoint to gather customer info that are 95% - 100% the same that need to be defined and implemented in two different servers.

@s-a-y I'd appreciate your thoughts too.

**Comment by istrau2** [comment]
I am fine with that.

**Comment by s-a-y** [comment]
yup, makes perfect sense, previous ties to FEDERATION_SERVER were very confusing for people I talked to.

**Comment by tomquisel** [comment]
@jedmccaleb That's right, the two different protocols are federation (SEP-2) and deposit/withdrawal (SEP-6). 

I'm proposing that we leave everything outside of SEP-6 unchanged, so AUTH_SERVER would still be used in SEP-3. What would change is that SEP-6 would use only the ANCHOR_SERVER, replacing its current need for both a DEPOSIT_SERVER and a FEDERATION_SERVER.

Under the proposed change, those two different use cases you mention would be covered like so:

1. withdrawing would be handled by ANCHOR_SERVER/withdraw
2. Cross border payments would be unchanged, using FEDERATION_SERVER/federation?type=forward

Since the use cases are somewhat different, I think it makes sense to handle them with different endpoints. But that's just an ancillary benefit.

**Comment by tempofr** [comment]
This goes back to discussions a year ago where we actually have 2 kyc procedures. 1 for compliance server partners and another for federation_forward for those not running the full compliance server (wallets etc).

I can rewrite what we have done for this but would really like whatever the solution to include kyc, tx_status, cancellations, and modifications and deals with transactions in a holistic manner.  

Final thing is that tx_status uses basic auth - which is fine but all solutions should support the same method of authentication for partners and/or wallets.

**Comment by jedmccaleb** [comment]
@tomquisel I'd rather not have two different ways of doing the same thing. Some of these anchors (such as tempo will be doing both cross border payments as well as allowing stellar users to hold their tokens.

**Comment by jedmccaleb** [comment]
Closing since this is addressed in the new SEP6
