### ISSUE TITLE
Make setting the home_domain low threshold

### ISSUE THREAD

**Issue by tomquisel** [stellar/stellar-protocol#137]
A few issuers have wedged themselves: they forget to set the location of their `stellar.toml` (via homedomain) file before locking their issuing account, leaving their asset easy to counterfeit and requiring a re-issuance. Two major examples of this are SureRemit and StemChain.

Stellar would be significantly less risky for issuers to use for ICOs if there were a protocol-level change that allowed an issuer to permanently lock some aspects of an account such as amount of an asset issued while still leaving homedomain changeable.

Thinking of the future: what if an issuer starts out as `getissuer.com` and then moves to `issuer.com` once they grow? It's painful to have `getissuer.com` irrevocably stored as the homedomain for the asset.

**Comment by bartekn** [comment]
Seems like changing `home_domain` threshold to low would solve this.

**Comment by johansten** [comment]
Sureremit should just have done a token swap using the DEX instead of their amateur hour effort.

**Comment by tomquisel** [comment]
LOL. @johansten can you detail how to do that a little more? @rice2000 is putting together an asset issuance guide so he can include the token swap idea.

**Comment by johansten** [comment]
It's pretty basic, really.

You create the new asset, and make sure your settings/flags are correct.

**Comment by johansten** [comment]
A SEP-0007 that handled source accounts better would make the actual swap a lot easier for the end user, if you have emails you could just email out a link to all of your asset holders.

**Comment by tomquisel** [comment]
Thanks @johansten. @nikhilsaraf just including you so you can see his feedback on SEP-7.

**Comment by johansten** [comment]
Nikhil has had my feedback ever since he didn't ask for it.

**Comment by nikhilsaraf** [comment]
@johansten we are planning to make some changes to SEP-0007, would love to hear your thoughts on how you want source accounts to be handled better.

**Comment by johansten** [comment]
https://github.com/stellar/stellar-protocol/issues/119

**Comment by nikhilsaraf** [comment]
added a comment on that issue. thanks for the suggestion.

**Comment by MonsieurNicolas** [comment]
not sure what the status of this conversation is,  in particular special casing changing `home_domain` to a threshold of `low`: I do not think this is viable.

* adding a "weight" property to "data" is doable, but seems a bit overkill in this situation
* If somebody was going to change the home domain of an issuer to some bad value, I *think* it pretty much wedges the issuer (best case), worst case it allows attackers to hijack those assets (as it allows to change key endpoints and properties advertised by that issuer). It sounds like a high privilege type of operation.

**Comment by theaeolianmachine** [comment]
@tomquisel do you have any thoughts on @MonsieurNicolas's comment? Does it make more sense to just have better documentation on this?

**Comment by tomquisel** [comment]
I'm just going to close this out.
