### ISSUE TITLE
SEP-24: Layered fee structure

### ISSUE THREAD

**Issue by jopmiddelkamp** [stellar/stellar-protocol#1394]
One of our anchors has a layered fee approach.

_Note: I'm interested in hearing your thoughts on this because I personally find it unfavorable since it can lead to a poor user interface and experience on the client's side. Explaining it to users can be quite challenging._

### What problem does your feature solve?
Layered fee structures are not supported by SEP-24.

**Deposits:**
5000 - 65k : 1% + N55
66k - 219k: N700
220k - 5m: 0.3%

**Withdrawals:**
5000 - 5m: 1% + 110NGN Capped at 760 NGN

### What would you like to see?
Maybe some structure like this?
```json
"deposit": {
  "NGNC": {
    "fee_tree": [
      {
        "from": 0.0,
        "fee_fixed": 55.0,
        "fee_percent": 1.0
      },
      {
        "from": 65000.0,
        "fee_fixed": 700.0,
        "fee_percent": 0.0
      },
      {
        "from": 220000.0,
        "fee_fixed": 0.0,
        "fee_percent": 0.3
      },
      {
        "from": 5000000.0,
        "fee_fixed": 0.0,
        "fee_percent": 0.0
      }
    ]
  }
},
"withdraw": {
  "NGNC": {
    "max_fee": 760.0,
    "fee_tree": [
      {
        "from": 0.0,
        "fee_fixed": 110.0,
        "fee_percent": 1.0
      },
      {
        "from": 5000000.0,
        "fee_fixed": 0.0,
        "fee_percent": 0.0
      }
    ]
  }
},
```

**Comment by Ifropc** [comment]
Hi @jopmiddelkamp , we recently introduced SEP-38 quote API in the SEP-24 protocol (#1358)
The SEP-38 `GET /price` API (https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0038.md#get-price) allows to introduce more complex fee structure, for example:
```
  "fee": {
    "total": "8.40",
    "asset": "stellar:USDC:GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN",
    "details": [
      {
        "name": "Service fee",
        "amount": "8.40"
      }
    ]
  }
```
(See SEP-38 protocol for more details)
In practice, that means that a wallet could call /prices endpoint prior to starting interactive flow to fetch exchange ratio and fees

I will close the issue, if you think it doesn't cover your use case please feel free to reopen it.
