### ISSUE TITLE
SEP-0001 Collateral Signatures

### ISSUE THREAD

**Issue by johansten** [stellar/stellar-protocol#140]
Where does the variables inside `collateral_address_signatures` strings come from?
It seems quite useless to list a bunch of signatures if I can't recreate the messages to verify them.
Might as well just post random garbage instead.

Also, is $START and $END when the *reserve* is valid, or when the signature is valid?

**Comment by tomquisel** [comment]
@johansten Thanks for bringing this up. My intent is that these signed messages contain both the content and the signature, similar to a signed Stellar transaction.

If you think the explanation for $PUBLIC_KEY, $CODE, or $ISSUER_ADDRESS is unclear, a PR explaining them better would be very helpful. Same on the $START and $END front. The intention is that it's the period of time when the reserve is valid.

**Comment by johansten** [comment]
@tomquisel Now, *that* makes is clearer.

So you'd have collateral_address_signatures be an array of messages to validate, interleaved with their signatures? E.g.,

`collateral_address_signatures = ["The assets in the account...","SY/32dr63c==="]`

base64-encoded raw signatures, and not decorated signatures, I'm guessing.
And no hashing of the message before signing?

**Comment by tomquisel** [comment]
@johansten I was originally thinking entries in `collateral_address_signatures` would contain base64-encoded objects containing both the message and the signature like Stellar `TransactionEnvelope`s, but looking into things more, it seems more standard across Bitcoin, Ethereum, etc... to have separate messages and signatures like you're suggesting.

Probably the cleanest solution is to leave `collateral_address_signatures` as a list of base64-encoded raw signatures, and add a new field: `collateral_address_messages` to contain the message contents. So it's exactly like you're suggesting, but we `unzip` that list into two separate lists.

Sound good? Feel free to write up a PR along these lines and I'll merge it, or I'll get to it soon.

Thanks so much for your help clarifying!

**Comment by tomquisel** [comment]
PR: #164

**Comment by theaeolianmachine** [comment]
Closed by #164.

**Comment by theaeolianmachine** [comment]
Also, thanks @johansten!
