### ISSUE TITLE
Split `/customer` endpoint from SEP-6 into its own SEP

### ISSUE THREAD

**Issue by tomquisel** [stellar/stellar-protocol#149]
I'm thinking of splitting the [`/customer`](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md#customer) endpoint from SEP-6 into its own SEP.

Here's why: 

* It's largely independent of the deposit/withdrawal functionality
* it will be useful in other systems, for example we'll need a structured way for a user's wallet to ask an `AUTH_REQUIRED` asset issuer exactly what is needed for the issuer to allow the user to buy/hold the asset. In most cases, the issuer will need the user to upload some KYC data, which will require something like the `/customer` endpoint. I'll call this new use case SEP-11.

The other option is to simply add the SEP-11 auth request functionality to [SEP-6](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md). It fits within SEP-6's description (wallet / anchor interop), but SEP-6 is already large and deposit / withdrawal is a separate need from buy / hold. Some issuers may only need to implement one or the other.

Thoughts?

@MonsieurNicolas @tomerweller @jedmccaleb

**Comment by MonsieurNicolas** [comment]
Maybe I am missing something... SEP006 is marked as "accepted" so whatever is in there can be implemented; you can always open new SEPs to extend it.
I think in general (in the future as SEP006 is done) it's probably a good idea to split up SEPs to speed things up and get scoped conversations.

**Comment by tomquisel** [comment]
@MonsieurNicolas yeah, I'm not suggesting changing anything that would affect an implementation. I'm suggesting we move the description of the `/customer` endpoint to SEP-11 from SEP-6, and have SEP-6 refer to SEP-11. So the semantics of SEP-6 are identical, but it's more modular.

**Comment by tomquisel** [comment]
PR: #161
