### ISSUE TITLE
Prettier should output what the diff is required to make it pass

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-protocol#1493]
Prettier currently runs on CI on PRs that change the markdown files, and checks that they are formatted.

However, the output of prettier doesn't say what's wrong and what needs fixing:

<img width="853" alt="Screenshot 2024-06-14 at 10 34 55 am" src="https://github.com/stellar/stellar-protocol/assets/351529/b7164acc-23e8-4b75-b850-b981cfd9cc7f">

It would be helpful for folks without prettier installed if the diff was outputted so that they could copy-paste and apply that diff locally.

Alternatively, the CI could even apply the diff and push it to the PR.

cc @Ifropc

**Comment by Ifropc** [comment]
I tried applying the diff and pushing to PR, but it didn't work because other jobs were not triggered by that commit (and we require all jobs to pass before merge), but I'll look into printing the diff
