### ISSUE TITLE
Access control flags for regular key?

### ISSUE THREAD

**Issue by roosmaa** [stellar/stellar-protocol#15]
Imagine a gateway which requires email confirmation to authorise trust lines. For such a gateway implementing the cold & hot wallet pattern would be meaningless as the issuing account private (master or regular) key would still have to be present on the servers to authorise trust-lines.

It would be nice if it was possible to limit the access granted to the regular key. A flag of what the regular key can authorise: payment, trust set, offers, etc.

So if I want the regular key to be able to only authorise trust lines, I can safely have the key on my servers without having to worry about too much damage that could be done should it be stolen.

**Comment by jedmccaleb** [comment]
this is done now
