### ISSUE TITLE
Duplicate credit_alphanum4 / credit_alphanum12 assets

### ISSUE THREAD

**Issue by tomquisel** [stellar/stellar-protocol#160]
As far as I understand it, it's possible to effectively issue the same asset twice. For each asset code (`EURT` for example) and each asset issuer (`GAP5LETOV6YIE62YAM56STDANPRDO7ZFDBGSNHJQIYGGKSMOZAHOOS2S` for example), the asset can be issued both with type `credit_alphanum4` and `credit_alphanum12`, so long as the asset code is no more than 4 characters in length.

I'd vote for disallowing assets of type `credit_alphanum12` with asset code length <= 4 in the Stellar protocol.

**Comment by cavemanbingo** [comment]
This is a great solution. The current allowance makes it pointlessly hard to be *sure* what you think you're buying is what you think it is, unless you're extremely sophisticated.

**Comment by MonsieurNicolas** [comment]
this is already the case, maybe it's not enforced in sdks, but `credit_alphanum12` has to be at least 5 characters.

**Comment by tomquisel** [comment]
@MonsieurNicolas Great! I'll close it out here.

**Comment by bartekn** [comment]
In official SDKs the underlying type (`credit_alphanum4`/`credit_alphanum12`) is hidden from a developer. The decision which one to use is based on the asset code length during XDR encoding.
