### ISSUE TITLE
account_tx should allow DestinationTag to be filterable

### ISSUE THREAD

**Issue by VincentTide** [stellar/stellar-protocol#17]
The account_tx API call should allow you to enter in a destination tag to view transactions that affect an account with the specified destination tag.

If you are only interested in a specific customers account, this will allow faster lookups since each customer will have a unique destination tag.

**Comment by jedmccaleb** [comment]
If you'd still like this can you make an issue in https://github.com/stellar/horizon this is where it would be implemented
