### ISSUE TITLE
Raise the maximum for number of signers and thresholds/master key weight

### ISSUE THREAD

**Issue by MisterTicot** [stellar/stellar-protocol#174]
As we are in the process in figuring out how to secure multi signatures transactions, I would like to open the discussion on allowing an arbitrary amount of signers for accounts.

Blockchain & smart contracts use cases include crowd-funding and collective control over investment. A simple example is allowing the whole set of investors to gradually vote for funds unlocking. This is the kind of solution that is currently investigated by various block chain to move on from the craziness of blunt ICOs.

Stellar block chain aims at making ICOs more secure and accessible, so it makes sense to see if we can move toward this direction with a protocol change. What is required is to allow an arbitrary (or very high) number of signer per account, and raising thresholds accordingly.

I assume the limits were puts so low to keep the ledger data compact. So the first question that comes to mind is a: is there any way we could enable higher limits without bloating everything?

**Comment by tomerweller** [comment]
MuSig should allow this: https://github.com/stellar/stellar-protocol/issues/91

**Comment by theaeolianmachine** [comment]
Closing this in favor of the work for #91.
