### ISSUE TITLE
Potential for abuse by using trust lines (Trust Line Attacks)

### ISSUE THREAD

**Issue by JonLister** [stellar/stellar-protocol#176]
Hello Stellar Team,

I found a potential issue which could lead to abuse (Trust Line Attacks).

Users could target an anchor or individual by adding trust lines to maliciously named tokens. So when users search the victim's address on an explorer they see all the spam tokens created by the attacker. Here's an example:

https://stellar.expert/explorer/public/account/GB6A5WRAINJK5HNDOWA2G3RH22P2MQVOEBFIMQF3QTNMXDM2DQK2GO6N

Could this be resolved by allowing only the issuing account to create new tokens? Or maybe this would be an initiative that explorers could resolve by only showing assets that have a supply > 0.

**Comment by orbitlens** [comment]
To my mind, new asset issuing shouldn't be chargeless. For example, NEM blockchain charges a fee for making a new asset: 100 XEM (~10$) for the top-level namespace/asset and 10 XEM for each sub-namespace. 

It looks to me as a wise step to prevent the uncontrolled new assets generation and network spamming. Following the NEM approach, Stellar could charge 1000x`base_reserve` (1000 x 0.5 = 500 XLM) fee for the first asset issued by the account and 1x`base_reserve` (1 x 0.5 = 0.5 XLM) for each subsequent asset in addition to the transactions fee.

It wouldn't solve the asset name spoofing problem entirely, but it will help to reduce the spam and greatly increase the price of a possible attack.

**Comment by tomerweller** [comment]
@orbitlens why not employ @JonLister's solution of only displaying assets with a circulating supply of more than 0? 

A more complete solution would be for wallets and explorers to resolve the account home domain's TOML file and verify the asset with the [currencies section](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md#currency-documentation). Assets that can't be verified should either not be displayed or have some red `UNVERIFIED` label on them.  

I don't see a need for a protocol change here.

**Comment by orbitlens** [comment]
@tomerweller I don't think that just hiding assets with zero supply or without trustlines makes any sense. From the technical point of view, there are no difficulties in issuing malicious assets with large supply and a few trustlines, it can be achieved by using 3-4 accounts that create trustlines to each other. 

The same with `stellar.toml` verification, it doesn't really protects users. For example, I can register a domain `mоbius.network` (I bet that nobody will spot a Cyrillic `о` symbol visually identical to ANSI `o`), it costs only $4.99 for the first year. Then I generate an address resembling the Mobius issuer account using vanity address generator – a few minutes to get the address ending with identical 6 chars, place `stellar.toml` file on my fake domain, and I'm good to go – everything is ready for the new "free giveaway, just-put-your-secret-key-here".

I'm not telling here about the database pollution. An attacker can easily create hundreds of new assets per second and flood the underlying tables.

**Comment by JonLister** [comment]
@orbitlens attackers won't be able to create supply of the spam token, only the issuing address can. As long as the supply of the token is 0, it wouldn't matter how many trust lines were added to it.

I do agree with you on pollution of the underlying tables - but there wouldn't be much of an incentive to do the attack if the spam tokens aren't displayed anywhere

**Comment by tomerweller** [comment]
I think we're conflating several different issues here: 

1. Having valid issuers appear as if they issue assets that they haven't. This is the original topic of this issue and the solution of only showing assets with a positive supply holds (an attacker can create as many trust-lines as they want but they can't generate supply from an issuer account they don't have control of). I still think that we in the ecosystem should get in a habit of verifying these with the relevant TOML file. 

2. Malicious issuers pretend to be someone they're not (phishing) using similar home domains and account ids. This is an ecosystem problem that deserves a discussion, though probably in a separate gh issue. I don't think making asset issuance more expensive in the protocol level will help with this.  

3. Database pollution. In the context of stellar-core (or other future stellar implementations), trustlines come with the cost of the base reserve which should deter an attacker from creating a very large amount of these. If these trustlines are created and removed, then in the context of historical databases (horizon and others) we should probably have more strict rules in terms of what we index and not. As a starting point, maybe only ingest assets that have a positive supply?

**Comment by orbitlens** [comment]
Ok, now I got the point of @JonLister. 

I'll update StellarExpert interface to show only those assets that have at list one active trustline by default. All other assets will be hidden under the spoiler.

> I still think that we in the ecosystem should get in a habit of verifying these with the relevant TOML file.

Agree with that. However, not showing assets without corresponding `stellar.toml` record in `/assets` endpoint response may be a problem. What about marking such assets with a "non_verified" flag?

> This is an ecosystem problem that deserves a discussion, though probably in a separate gh issue. I don't think making asset issuance more expensive in the protocol level will help with this. 

Yes, it's a complex problem and it's better to discuss it in a separate thread.

**Comment by tomerweller** [comment]
> What about marking such assets with a "non_verified" flag?

That sounds like a good solution. Maybe with a link to some sort of a faq that explains what that means.

Will close this issue for now. We should discuss related issues in their own tickets.
