### ISSUE TITLE
`DEPOSIT_SERVER` is not documented in the specification, but used in the example

### ISSUE THREAD

**Issue by Ryanmtate** [stellar/stellar-protocol#177]
README.md file contains an example where a `DEPOSIT_SERVER` variable is defined in the stellar.toml file.

This variable is not documented in the 0001 specification. I assume this variable in the example should instead be `TRANSFER_SERVER`

**Comment by theaeolianmachine** [comment]
@Ryanmtate, what README are you referring to? One in another repo, such as [stellar-core](www.github.com/stellar/stellar-core), [go](www.github.com/stellar/go), or [docs](www.github.com/stellar/docs)?

**Comment by ire-and-curses** [comment]
I think the issue is here: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md

`DEPOSIT_SERVER` is used in the example in that file, but in the spec above, it isn't defined. `TRANSFER_SERVER` is defined, but isn't in the example.
