### ISSUE TITLE
Fetch one transaction by id in SEP0006

### ISSUE THREAD

**Issue by istrau2** [stellar/stellar-protocol#206]
I think there should be an endpoint similar to `/transactions` where one can fetch a transaction by its:

1. id
2. external_transaction_id
3. stellar_transaction_id

Use case: so that client applications (perhaps backend processes etc.) can confirm the status of a specific transaction.

@tomquisel

**Comment by tomquisel** [comment]
I believe this is dealt with now.

**Comment by efritze** [comment]
Please make **asset_code** a required field for the **/transaction** endpoint.

There are many cases where banks/anchors could have the same transaction ids for different assets they host (e.g. in the case of auto-incremented transaction ids.)

Also, the asset_code parameter will help anchors identify the right host to send requests to in the case of anchors that run anchors on different hosts.

**Comment by tomquisel** [comment]
@efritze thanks for the suggestion! Can you raise it as a separate issue?

**Comment by efritze** [comment]
@tomquisel  
Done.
https://github.com/stellar/stellar-protocol/issues/368
