### ISSUE TITLE
SEP-0006 should allow for more complex fee structures

### ISSUE THREAD

**Issue by vcarl** [stellar/stellar-protocol#234]
Already we're encountering anchors who want to use more complex fee structures than can be conveyed with just `fee_fixed` and `fee_percent`. I'd propose adding a `fee_schedule` property, an object with the amount to be used for the lower bound as a key, with a value of an object with keys `fee_percent` and `fee_fixed`.

```json
{
  "fee_schedule": {
    "0": {
      "fee_fixed": 5,
      "fee_percent": 0
    },
    "50": {
      "fee_fixed": 0,
      "fee_percent": 3
    },
  }
}
```

This example would charge $5 when moving 0-50 and 3% when moving >50. The amount would be exclusive, i.e. the fee applies when the amount being moved is `>` the key value, not `>=`. Any `fee_fixed` and `fee_percent` should be ignored if a `fee_schedule` is present.

**Comment by tomquisel** [comment]
Great point! Here's a proposal for SEP-6 that handles any fee structure: #241
