### ISSUE TITLE
Add the ability to attach key/value pairs to an account

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-protocol#27]
Create a new DataEntry that is just a key/value pair.
These DataEntries are owned by accounts. The key would be a string and the value would be 32bytes.
There would be operations to add and remove DataEntries.

Each DataEntry would increase the storage cost of the account. 

Could be used for things like attaching an encryption key to the account. Having the account publicly attest to some fact.  If the account needs to provide other meta data about itself.

**Comment by jedmccaleb** [comment]
possible implementation: https://github.com/stellar/stellar-core/pull/997
12 character strings as keys
64 bytes as values

**Comment by MonsieurNicolas** [comment]
What are the actual use cased for this? Until now we had a strict schema for the user (like homeDomain)

**Comment by jedmccaleb** [comment]
It could be used for:
associating an encryption key with an account (this is the main thing we need it for now since this is a building block of the kyc stuff and private transactions)
associating other meta data, like name, other ways to contact, etc.
homeDomain could probably be this instead
Making a decentralized keybase.

Also I think there will be a lot of unanticipated things that will be able to use this. It seems like a pretty useful extension point.

**Comment by MonsieurNicolas** [comment]
Right, I understand it's generic, which quickly turns into garbage-in garbage-out type of situation as it's completely unstructured with no namespace.
I thought that even for kyc there was a need for external stores that deal with identity for example.

**Comment by jedmccaleb** [comment]
Well there will be agreement outside the protocol at the application layer about what the keynames mean. Similar to how assets work.

**Comment by elliots** [comment]
I don't want to just say +1, but that's basically the gist of this comment. This would be useful. 

As a compromise between strict schema and garbage, perhaps a namespace field? Still not an actual schema, but would allow (through convention... domain?) for companies to namespace their fields and avoid clashes ('verificationCode' etc).

**Comment by sunny-g** [comment]
+1

**Comment by sunny-g** [comment]
In addition :+1: this proposal, in addition to this repo for outlining new proposals, is there a publicly-available roadmap or priority list for when these proposals will be implemented?

Also, might this be a better use for IPFS storage for longer values as opposed to a dedicated protocol change like #32?

**Comment by jedmccaleb** [comment]
@sunny-g  In this repo we discuss them but just because we are talking about them here doesn't mean that they will get implemented. If the idea is good and makes sense to include we will make an issue in stellar-core or the appropriate repo. 

You could certainly use these key value pairs to include links to IPFS storage but it would be linked to a particular account. #32 is for attaching to transactions.

**Comment by sunny-g** [comment]
@jedmccaleb thanks for the prompt response and especially for your patience, I understand the differences now!

**Comment by MikeFair** [comment]
Isn't this in?
Or is there something about this proposal that's different than the "Manage Data" txn API?

**Comment by jedmccaleb** [comment]
yes this is now in
