### ISSUE TITLE
Deterministic Accounts Stop Gap

### ISSUE THREAD

**Issue by JeremyRubin** [stellar/stellar-protocol#288]
Given the lull on implementing deterministic accounts https://github.com/stellar/stellar-protocol/issues/99, I wanted to propose the following simple features which will let us get much of the benefit of deterministic accounts without as much core churn:

A CreateAccount operation which doesn't fail if the account already exists and throws away/sends to the tx source any excess balance (EnsureNewAccount). The account should also not have any subentries. The sequence should be before the given limit.

This feature can be used as follows:

```
Transaction:
  Source: A
  Operations:
    EnsureNewAccount B, 100 XLM, seq_limit = FAR_OFF_FUTURE_LEDGER << 32 | 0
    BumpSequence (FAR_OFF_FUTURE_LEDGER << 32 | 0)
    /* At this point, B exists at a known sequence number with a known balance */
```

While deterministic accounts are strictly nicer as they don't have concerns around the signer on B, such an EnsureNewAccount operation can be used to create an account in a well known state. If the account B's key is constructed in an MPC (e.g., using MuSig) then the account can't be tampered with by any of the parties, it could just be created at an unexpected sequence number or have an unexpected amount of lumens.

Such a transaction can be used much like a deterministic account as follows:

```
Transaction:
  Source: A
  Operations:
    EnsureNewAccount B, 100 XLM, seq_limit = FAR_OFF_FUTURE_LEDGER << 32 | 0
    BumpSequence (FAR_OFF_FUTURE_LEDGER << 32 | 0)
    SetOptions:
       Add Signer for a Preauth Transaction at (FAR_OFF_FUTURE_LEDGER << 32) | 0
       masterweight = 0
```

This transaction is guaranteed to succeed as long as account B is not tampered with and the time is before FAR_OFF_FUTURE LEDGER.

Downsides of this approach is that it restricts our ability to increase the ledger rate appreciably as contractors may be dependent on the FAR_OFF_FUTURE_LEDGER being very far away.

It also requires an ephemeral key for the setup of the account. We can make the ephemeral key partially deterministic by having an unambiguous contract hash which is salted along with each parties public key to produce the temporary key. This prevents various kinds of 'false start' attacks.

However, the existence of this key precludes setting up trust-less automata (e.g, an automata that sells 100000 assets per week in perpetuity).

Upsides of this approach are that we get a stable identifier for the account, so we don't have any issues predicting the names of assets issued by this account for branched operations.

# Safety
The effects of this new operation can be argued to be safe as they are equivalent/emulable as a few other executions:

If B Exists:
```
operations:
  AccountMerge B
  CreateAccount B, 100 XLM
  BumpSequence B to FAR_FUTURE << 32
```
If B does not Exist:

```
operations:
  CreateAccount B, 100 XLM
  BumpSequence B to FAR_FUTURE << 32
```

The feature is essentially letting us execute the conditional logic inside the transaction itself.

# Rationale

This feature is simple enough that it could be slated for *immediate inclusion* and would help bolster the development of payment channels, ATP3, and related protocols.

Design work on Deterministic Accounts can then be postponed indefinitely, or lumped with a more comprehensive account system redesign.

review:

@MonsieurNicolas @stanford-scs @danrobinson

**Comment by JeremyRubin** [comment]
One issue with this proposal is that the account is made effectively unmergeable -- this may or may not be an issue.

**Comment by MonsieurNicolas** [comment]
We went with `BalanceEntry` instead
