### ISSUE TITLE
Semantic Ledger Time Sorting

### ISSUE THREAD

**Issue by JeremyRubin** [stellar/stellar-protocol#291]
We should sort transactions in a ledger by mintime so that smaller mintimes execute first. We should also sort by maxTime so that later maxTimes execute later.

I.e., no transaction should execute in a ledger while there is a pending transaction with an earlier minTime. No transaction should execute in a ledger for a given minTime bucket until it is the transaction with the smallest un-executed maxTime.

I think that Semantic Ledger Time Order should be considered independently from TimeBounds Ledger Number #290  -- it has the unfortunate side effect of making transactions with a minTime trivially front-runnable, but has the benefit of improving the semantic passing of time between transactions.

This increases the complexity of the ledger formation process, but does not increase the validation complexity significantly as the check can be performed while processing each transaction. It also makes it simpler for writers of multi-transaction multi-source contracts to guarantee a specific execution order within a single ledger.

**Comment by JeremyRubin** [comment]
Note that it's still possible under this semantic to have the case where:
```
Ledger N:
   Tx w/ minTime t

Ledger N+1:
  Tx w/ minTime t-1
```

which is not ideal -- but guaranteeing that the transactions are ordered correctly in the same ledger or in different ledgers still improves the situation somewhat.

**Comment by ire-and-curses** [comment]
If you can't guarantee the ordering across ledgers, and you can't guarantee that you're going to get into the same ledger, then how does this help the submitter? Since sequence numbers still need to be monotonic increasing, it seems to me the submitter still has to produce and submit transactions in the correct order, and either wait for ledger close for each, or monitor for failures and resubmit, until all transactions are accepted. To be clear, this is the current situation as I understand it. I'm just not seeing how ordering by time within the ledger helps.

**Comment by JeremyRubin** [comment]
To be clear: the goal is not to make all interleavings work perfectly, it is to make *some* interleavings work better than they currently do.

As it stands, if I have an account A:

```
Account A:
  Signers:
    - s_1
```

and then I have a transaction which removes `s_1`, then it's possible for transactions involving account A to be accepted into a ledger and then fail an individual operation with bad auth and still assess a fee.

These execution semantics are really poorly documented/described, so I'm still not sure exactly when fee is assessed, you need to understand the entire execution model based on reading the code.

What this proposal would let you do would be to be sure that, by setting mintimes accordingly, the transactions are either executed in the correct order within one ledger, in the correct order within multiple ledgers, or are invalid (e.g., because of key changes) across multiple ledgers.

It sounds like kind of a narrow win, and one that is difficult to fully explain why this is good without a more clear document explaining transaction set lifetime and exactly when side effects (like updated keys and fees being paid) are written/observable.

**Comment by JeremyRubin** [comment]
This is partly documented here: https://github.com/stellar/stellar-core/tree/master/src/transactions#applying-a-transaction.

First, all accounts are charged a fee. Then they are attempted to be applied, being either valid, success, or fail.

I really don't get how fees can be assessed if they are TX_AUTH_BAD so those must be filtered out before they are attempted, but this is undocumented.
