### ISSUE TITLE
XDR Organization Proposal:

### ISSUE THREAD

**Issue by JeremyRubin** [stellar/stellar-protocol#294]
It might be handy to mirror the XDR into this repository so that Pull Requests can include the relevant XDR changes, and we can (downstream in stellar-core) see how it is out of sync with the specification.

We can keep master as a bleeding edge set of XDR changes which allows drafts to modify, and have a separate release branch which only includes CAPs which are slated to be implemented.

This may be a bad idea, but it was something that occurred to me might be useful.

**Comment by tomerweller** [comment]
I'd go further and say that the XDR source of truth should *not* be inside of the stellar-core repo. The XDRs are part of the protocol spec, they shouldn't belong inside a specific implementation. 

Though, I'm not sure if here or a dedicated repo makes more sense. (versioning sounds complex if it's here)

**Comment by JeremyRubin** [comment]
I agree with the sentiment there -- it should be possible to pull down the XDR as a separate repo into other projects. Maybe someone with git submodule-fu skills would know the best pattern for upstreaming changes like that.

**Comment by theaeolianmachine** [comment]
Yeah I definitely agree, I think it should be a submodule in both this repo and stellar-core (stellar-core already uses some submodules). I'm pretty knowledgable of submodules, so would be happy to maintain it here.

@MonsieurNicolas, any thoughts on having this over in `stellar-core`?

**Comment by bartekn** [comment]
Related: https://github.com/stellar/stellar-core/issues/984
