### ISSUE TITLE
CDN/hosting javascript libraries

### ISSUE THREAD

**Issue by johansten** [stellar/stellar-protocol#30]
One issue we came up on when we did the signup page for the inflation pool was getting users to trust a page enough to put their private key into a form field.

The signup code itself is only 20-30 lines of code, but since we're hosting js-stellar-sdk ourselves, users will have to make sure our version is not instrumented in any way.

Having SDF host the javascript libraries would be very helpful, since the end-users ultimately *have to* trust SDF. (If they don't, they're in the wrong place anyway)

Something like this perhaps:
`cdn.stellar.org/{version-number}}/stellar-sdk.min.js`

If you also publish hashes (together w/ the github tag commit perhaps) that would be extra helpful, as web pages could just add SRI to make sure the files aren't changed on your side.

**Comment by irisli** [comment]
Here is a related issue in js-stellar-base: https://github.com/stellar/js-stellar-base/issues/20
(Just commenting here so that things can be better connected)

**Comment by johansten** [comment]
I started checking out cdnjs yesterday but got sidetracked. I think it looks good. Their new approach is to actively ping for new versions of libraries, so we just need to get accepted into the program and then it'll be set up, with no more action needed.

**Comment by irisli** [comment]
The requirement I saw with cdnjs though was that projects needed at least 100 stars and they should be "production ready" (not alpha or beta).

Right now unfortunately, I don't think js-stellar-sdk is there yet.

**Comment by johansten** [comment]
One of the other things they base inclusion on is npm downloads (>500/month), where we're at triple that right now.

Sacarlson found rawgit.com, which make things even easier, as they just proxy whatever you request. No signup.

So what's missing now is just the SRI hashes.

**Comment by cyberomin** [comment]
Hey @johansten and @irisli, I did submit the SDK to CDNJS yesterday and it has been merged. I think this should have been sorted now.
