### ISSUE TITLE
need to mention recommended size for logo

### ISSUE THREAD

**Issue by skirsch** [stellar/stellar-protocol#302]
https://www.stellar.org/developers/guides/walkthroughs/how-to-complete-stellar-toml.html 

see org_logo. 

No mention of preferred size or aspect ratio or whether transparent or opaque or file types accepted (png, gif, jpg????)

**Comment by msfeldstein** [comment]
This is a good question.  It would be great to do something like what the web platform did with favicons where you can specify multiple sizes and the client application can choose what fits best.  This might be premature however given that this isn't very widely used.

We probably should add some suggestion that the aspect ratio be square, and file format transparent PNG.  We might also suggest that logos be no larger than 256x256, and closer to 128x128, it seems that most places use them around the size of a touch icon, any larger is a waste.

**Comment by msfeldstein** [comment]
https://github.com/stellar/docs/pull/506
