### ISSUE TITLE
Proposal: remove [QUORUM_SET] from stellar.toml

### ISSUE THREAD

**Issue by sui77** [stellar/stellar-protocol#307]
I'd like to propose to remove [QUORUM_SET] from the stellar.toml specification in [SEP-1](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md).

Reasons:
- It bloats the file without serving a useful purpose.
- Even if, it can not reflect multiple validator nodes with different qset configs under the same domain.
- Lot of people seem to just copy&paste the `"$self", "$lab1", "$nelisky1","$jianing","$eno","$donovan"` example.
- It's prone to be outdated when validator qsets are changed but stellar.toml is not updated (as currently seen on https://www.stellar.org/.well-known/stellar.toml ).
- All information that it should serve is already reliably accessable via SCP (or stellarbeat) and can be simply related to SEP-20 self-verified validators

**Comment by tomerweller** [comment]
Agreed. @rice2000 is working on a SEP1 cleanup PR. This will definitely be part of it.

**Comment by theaeolianmachine** [comment]
Marking #308 to close this out once merged, feel free to take a look with any feedback @sui77.

**Comment by sui77** [comment]
Thx, nothing to do here any more :)
