### ISSUE TITLE
SEP-0006: Add custom withdrawal network fees

### ISSUE THREAD

**Issue by ramontayag** [stellar/stellar-protocol#317]
We would like to be able to use the withdraw endpoint while setting a crypto network fee. To be able to create a wallet where users can choose "economical" or "custom" and set their own fees, SEP-0006 would need to be able to accept a "network fee" in the `/withdraw` endpoint. 

On a more technical level, the changes would touch the `info` endpoint and the `withdraw` endpoint.

- `/info` would have an extra field `custom_withdrawal_network_fee` that can be set to `true`.
- When set `custom_withdrawal_network_fee` is `true`, clients can expect `/withdraw` to accept `network_fee` decimal, which is added on top of any other fees.

Example:

- `custom_withdrawal_network_fee` is `true`
- `fee_fixed` is `0.01`
- `fee_percent` is `1`
- user has `1` BTC token and wants to withdraw `0.5`
- user will submit `0.005` as the withdrawal `network_fee`
- user should send over (their wallet makes this computation) `0.52`

```
0.5 BTC = 0.50 B⃦
+ 1% fee_percent = 1 %
+ 0.01 fee_fixed = 0.01
+ 0.005 network_fee = 0.005
Total = 0.52 B⃦
```

The withdraw server will send out 0.5 Bitcoin to the user's `dest` and will set the network fee to be `0.005`.

I thought about making a new endpoint that allows users to estimate the withdrawal network fee by submitting strings like `ECONOMICAL` or a target number of blocks like `3`, but I think that can be handled outside of SEP. The wallets that hold the BTC tokens would just talk to some other service that returns the network fee estimate which is submitted like described above.

**Comment by tomquisel** [comment]
Thanks @ramontayag! My sense is that, to keep SEP-6 and the user experience simple, it's best if the issuer set  a `fee_fixed` that will cover the network fee in most reasonable cases, and then eats the network fee. The issuer can always adjust that fee upwards if network congestion is becoming an issue.

**Comment by ramontayag** [comment]
Alright thanks will close this
