### ISSUE TITLE
SEP-007 - Doesn't Support Timebounds

### ISSUE THREAD

**Issue by aanupam23** [stellar/stellar-protocol#347]
**Problem**
SEP-007 consists of two type of operations, _pay_ and _tx_ for delegated signing. This issue addresses the _tx_ operation when using timebounds.

**Description**
SEP-0007 allows users to sign transactions through delegated signing in an open and decentralized manner. However, if an application consists of creating operations that will become valid at a particular timestamp(using timebounds), then SEP-007 will fail since delegated signing wallet submits the transaction immediately and hence it will be under the error category `tx_too_early`.

**Solution**
One possible solution for this issue is for SEP-0007 compatible wallets to allow the signing of transactions but don't submit the transactions until the minimum timebound becomes valid.

**Comment by tomerweller** [comment]
What about using the optinal `callback` parameter so that the wallet signs and returns the signed tx to the bckend without signing it?

**Comment by aanupam23** [comment]
Thanks @tomerweller 
`callback` parameter is exactly what I needed, I will test this and share the results.
