### ISSUE TITLE
Add `url` attribute to Transaction resource on SEP6 /transaction and /transactions endpoints

### ISSUE THREAD

**Issue by accordeiro** [stellar/stellar-protocol#348]
[Based on a conversation with @tomerweller]

The transaction endpoints on SEP6 are currently not clear about what token/currency was deposited or withdrawn in a given transaction, making it hard for wallet users to track the status of the external parts of the operation.

We can fix this by adding a `url` attribute to our Transaction resource on both `/transaction` and `/transactions` endpoints. For example, anchors could provide an Etherscan URL for tracking ETH transactions, or Blockcypher for BTC transactions. For fiat transactions, anchors could provide an internet banking URL.

An example `/transaction` response:

```json
{
  "transaction": {
    "id": "82fhs729f63dh0v4",
    "kind": "deposit",
    "status": "pending_external",
    "status_eta": 3600,
    "external_transaction_id": "0x236f8d1a0f564aa2183dd6b7897fdc596da81e01674c7630d0f473fc9ad96896",
    "url": "https://etherscan.io/tx/0x236f8d1a0f564aa2183dd6b7897fdc596da81e01674c7630d0f473fc9ad96896",
    "amount_in": "24.4742389",
    "amount_out": "24.3742389",
    "amount_fee": "0.1",
    "started_at": "2019-07-19T13:25:46Z"
  }
}
```

Open questions:
1. Should we also add an `asset` parameter, to identify more easily what asset is being deposited / withdrawn?

**Comment by poliha** [comment]
Given that a transaction can contain `n` operations, should this info be at the transaction or operation resource? 
If this information is coming from anchors, maybe it should be added to [SEP 4](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0004.md)?

**Comment by accordeiro** [comment]
Oh sorry @poliha, I forgot to mention this issue was specifically related to the SEP6 transaction endpoints. I've updated the title and description to make that more explicit :)

**Comment by msfeldstein** [comment]
This could also be used to show more information about a cash pickup.  If there was a storefront anchor in which you needed to show an order confirmation or something to pick up your cash, this url could have that.

**Comment by msfeldstein** [comment]
Can i open a pull request for this?

**Comment by accordeiro** [comment]
@msfeldstein it looks like a `more_info_url` attribute has been added to the `Transaction` resource on #342. Do you think it could also be used for the purpose you've described above, or should we create a separate param for that? [cc @tomquisel / @tomerweller]

**Comment by tomquisel** [comment]
Throwing my vote into the ring: I'd say use that `more_info_url` parameter.

**Comment by msfeldstein** [comment]
yeah that should work.  Should we close this?

**Comment by accordeiro** [comment]
Yep, closing it now. Thanks!
