### ISSUE TITLE
Sign TRANSFER_SERVER with asset account

### ISSUE THREAD

**Issue by patrickxb** [stellar/stellar-protocol#349]
Right now, TRANSFER_SERVER is just trusted to be legit.

It would be nice if there was a way when processing stellar.toml to validate that TRANSFER_SERVER does actually pertain to the asset(s) in question.

One thought would be to sign the TRANSFER_SERVER value with each secret key for the assets it handles and include those signatures in stellar.toml.

cc @tomerweller

**Comment by s-a-y** [comment]
I personally think it's redundant.
If we start questioning authenticity of individual fields in stellar.toml, then maybe we need to sign the whole thing?
But generally you don't need to do that, even domain ownership can be confirmed by placing text file on it. We kinda assume at the moment, that you own domain where stellar.toml is hosted

**Comment by leighmcculloch** [comment]
I think if wanting to validate trust in stellar.toml being served by a domain, validating trust in the certificate in use for HTTPS is the place to do it. You can validate certificates based on their root certificate being a well known trusted issuer by using built-in root ca lists in the OS and many http libraries will do this by default. Alternatively if you want to trust a specific certificate you could build that into your application too.
