### ISSUE TITLE
Standardize on one content-type?

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-protocol#364]
Currently we have some protocols that expect `x-www-form-urlencoded` (3,7,8,10) some that expect `application/json` (8,10,19) and some that expect both (8,10).  I think it would be great to standardize on one format, and I'm especially worried about the protocols that expect both.  Allowing multiple content-types creates a combinatorics problem for clients and servers to run into problems.  In sep10, @nebolsin [mentions](https://github.com/stellar/stellar-protocol/pull/150) that adding urlencoded is a benefit because it doesn't require CORS preflight, but it seems like this is actually a problem.  Now that servers can develop using urlencoded, they might miss the CORS headers and any web clients that use json will break.  There's also longstanding issues with urlencoded formats as sergey mentions in the same comment.

I'm partial to application/json as most tools seem to use as the default these days and the tooling is better, but wanted to get community feedback on this.

Thoughts @tomquisel @tomerweller @nebolsin ?

**Comment by tomquisel** [comment]
@skirsch I'd love your thoughts too.
