### ISSUE TITLE
I’m what way (if any) will Stellar interoperate with Polkadot?

### ISSUE THREAD

**Issue by erlend-sh** [stellar/stellar-protocol#365]
I’d love to know what the interoperability story is for Stellar (and by extension slingshot https://github.com/stellar/slingshot) with regards to Polkadot https://github.com/stellar/slingshot.

**Comment by msfeldstein** [comment]
This isn't really the right place for this question, this repo is for CAPs and SEPs and other issues with the existing protocol.  I would ask this in the developer mailing list or keybase/reddit communities
