### ISSUE TITLE
Deprecate SEP-0012?

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-protocol#367]
[SEP-12](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0012.md) is intended to share KYC/UserData from the wallet to anchors, but there are some open privacy concerns there, as nothing in the SEP explains the user consent portion of this data movement.  

Seeing as there are concerns with it, coupled with the fact(?) that no one has implemented or depends on it yet, we should consider deprecating it.  If a use case comes up where it is needed, we can revisit it, but I don't see much value to supporting an un-needed SEP.

If people are actually using this please post here, I'd love to see implementations that are useful

**Comment by msfeldstein** [comment]
cc @tomquisel

**Comment by tomquisel** [comment]
My thought is that in 6 months we may want to go back to recommending SEP-12 in many cases once the ecosystem has evolved and patterns in how anchors integrate have emerged. For that reason, it makes sense to leave it live to avoid whiplash.

On the other hand, for the time being, SEP-12 basically is deprecated. Maybe having it live is just causing confusion for all, and deprecating would more effectively push anchors and wallets to the best path.

However, it may be painful for SDK maintainers. They may have implemented SEP-12, and then deprecate it, and then need to revive it again in 6 months.

There are some implementations out there, but I don't believe any wallet / anchor pairs are depending on it yet as you pointed out.

@msfeldstein thoughts?

**Comment by rice2000** [comment]
How about just adding a note to the top that sums up this conversation?  Essentially: "This SEP is deprecated at the moment, but may be revived and revised as anchors evolve new methods for handling KYC."

**Comment by tomquisel** [comment]
I like that idea @rice2000.
