### ISSUE TITLE
SEP0006: Make asset_code field mandatory on the /transaction endpoint

### ISSUE THREAD

**Issue by efritze** [stellar/stellar-protocol#368]
Please make asset_code a required field on the /transaction endpoint.

There are many cases where banks/anchors could have the same transaction ids for different assets they host (e.g. in the case of auto-incremented transaction ids.)

Also, the asset_code parameter will help anchors identify the right host to send requests to in the case of anchors that run anchors on different hosts.

**Comment by msfeldstein** [comment]
Why would an organization reuse transaction IDs?
