### ISSUE TITLE
decouple deposit/withdraw from anchor

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-protocol#397]
### Rationale
By convention, an anchored asset's issuer is also the only entity that facilitates deposits and withdraws for that asset. For example, AnchorUSD are the only entity that facilitates deposits and withdraws for the AnchorUSD USD token.

However, there's nothing stopping other financial institutions from doing the same. For example, let's say I run an Israeli FI, *ShekelsAreUS*. I could accept AnchorUSD USD withdrawals in Israel and supply users with either fiat USD or convert off-chain to fiat NIS. Symmetrically, I could also keep AnchorUSD USD in stock and allow deposits (i.e, sell AnchorUSD USD). 

Through my relationship with AnchorUSD I can buy/sell AnchorUSD USD for fiat USD according to my needs. Essentially, I'm an AnchorUSD merchant. (@jimdanz, do you find that offensive?) 

### Why is this good?
1. Allow for specialization. As *ShekelsAreUS* I'm not interested in issuing an asset, but I have great infrastructure to move money around in Israel. 
2. Facilitate off-chain withdraw/deposit currency conversions. See https://github.com/stellar/stellar-protocol/issues/395#issuecomment-528980139
3. Prevent fragmented liquidity. Fewer assets => fewer markets to make => market makers can create deeper orderbooks with the same amount of liabilities. 

### What do we need to change?
This is mostly a convention. I think that it's just a matter of changing the definition of "currency issued" to "currency supported" in SEP-0001: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md#currency-documentation. What am I missing?

**Comment by msfeldstein** [comment]
At first glance this seems good.  The asset itself will still point to the issuers home_domain which is the important direction.
