### ISSUE TITLE
sep0006 - extract initial setup 

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-protocol#398]
Often times there's a setup phase (or "on-boarding") associated with deposits and withdraws, especially with interactive ones. This setup will usually include KYC and sometimes connecting a banking rail (ACH, for example). 

Wallets might want to initiate this setup phase when on-boarding users (either on install or on setting up a trustline, etc) outside the context of a withdraw or deposit. 

Technicalities aside, should sep-0006 add an explicit option to do that?

**Comment by msfeldstein** [comment]
This seems like a good idea.  It seems like most of the time this would be happening is when a wallet is hardcoding in or building towards a particular anchor which makes the protocol less important, but there's no reason not to add it to the spec, or a standalone spec.

**Comment by accordeiro** [comment]
I really like this idea. Let me see if I understand this correctly: we could

1. Have a separate endpoint, let's call it `/setup` or `/signup`, that would provide an interactive flow for handling the KYC / banking rail connection, which can then inform the wallet (maybe via `postMessage`?) whether the setup was successful and the KYC was approved, or not
2. After going through the `/setup` flow, the interactive `/withdraw` or `/deposit` flows would be very simplified, maybe only requesting the user to input the desired amount

Does that sound right? If so, this is very aligned with some discussions @brunomuler and I had for some use cases we've been discussing.

One last question, though – how would this work for multi-tiered KYC?

**Comment by tomerweller** [comment]
> Have a separate endpoint, let's call it `/setup` or `/signup`

Yup. I would make that endpoint optional and have the `/info` endpoint expose whether or not this is implemented.

> After going through the `/setup` flow, the interactive `/withdraw` or `/deposit` flows would be very simplified, maybe only requesting the user to input the desired amount

Ideally. Still, withdraw/deposit can retain their interactivity, so if `/setup` was not called they'll go through this process on first use. 

Regarding multi-tier kyc, it's up to the anchor. The anchor can still collect extra information on the deposit/withdraw flows if `/setup` was not sufficient.

@accordeiro does that make sense?

**Comment by accordeiro** [comment]
@tomerweller yes, this makes perfect sense. The user may perform the "basic" KYC/setup through a separate `/setup` endpoint if they choose to, otherwise they'll simply have a longer interactive `/withdraw` or `/deposit` flow. 

If the `amount` the user is requesting belongs to a different tier from the basic KYC/setup they did through `/setup`, the anchor can still collect more required info during the interactive `/withdraw` or  `/deposit` flows.

I really like this. @brunomuler do you think this improves the CBP withdraw / deposit UX?

If we're all on the same page, I'd be happy to take a stab drafting a PR for this.

**Comment by brunomuler** [comment]
@accordeiro Yes, I believe this will bring more flexibility on the app side and might provide a better UX.

**Comment by tomerweller** [comment]
Happy.
