### ISSUE TITLE
Time format: seconds after year 2000 vs unix timestamp

### ISSUE THREAD

**Issue by irisli** [stellar/stellar-protocol#4]
The switch to having timestamps as seconds after year 2000 gives only 30 years compared to unix timestamp. This doesn't significantly affect the long term timebomb of a 32-bit epoch. Using a uint32, we will run out of space in 2106 with a unix timestamp and 2136 with the 2000 timestamp.

Timestamp libraries are also complex due to the many edge cases (leap years, leap seconds). This complicates things for developers. It would be easier to be compatible with existing unix timestamp libraries.

I'm thinking that a 64-bit unix time stamp would be a better choice especially if we want to plan for long term success of Stellar.

**Comment by jedmccaleb** [comment]
this is done now
