### ISSUE TITLE
SEP0006: TRANSFER_SERVER should be placed under each asset

### ISSUE THREAD

**Issue by efritze** [stellar/stellar-protocol#430]
As an organization handling multiple assets on different servers, SEP0006 makes our job harder than it should be.

An organization may very well host multiple USD assets with different issuing accounts for different clients. SEP0006's /deposit and /info endpoints don't have an asset_issuer query parameter that helps makes that distinction.

SEP0006 also makes me jump through unnecessary hoops to redirect requests to my right asset anchor server. Say I anchor BTC, and ETH on different servers. I have to use nginx's query parameter filtering support to determine which server to redirect my SEP0006 requests to.

The /info endpoint too doesn't scale well for organizations anchoring multiple assets on different servers. Say I anchor 10 different assets on 10 separate servers... BTC, ETH, LTC .... I'll still need a separate server for the /info endpoint. Which isn't ideal even if I did have that extra server, because the server where my anchored asset is located doesn't get to decide what features it enables or disables! The ability to determine if an asset anchor enables deposits or not, enables withdrawals or not, enables transactions history or not, custom fees, are all determined by a different server, which technically might not have as much (real time) information about the asset as the asset anchor server itself.

It sucks that with SEP0006, you either enable transaction history for all assets, or none at all. Say I anchor 10 different assets on 10 separate servers... I want to enable transaction history on BTC and ETH, but I don't want to enable transaction history for USD and EUR. There's no way to do that right now with SEP0006, because the transactions(enabled/disabled) field on the /info endpoint is a global setting for all assets!
Same goes for the (custom) fees (enabled/disabled) field on the /info endpoint, which is another global setting for all assets.

Another issue is the /transactions endpoint as stipulated in #368 . There is no (easy) way to get the transaction details only from the transaction id in the case of assets anchored on different  servers (defined in  the same stellar.toml file). Some asset transactions may very well have the same transaction ids in the case of auto-increment. Even when UUIDs are used, the TRANSFER_SERVER wouldn't know which asset anchor to send requests to, based only on the transaction id.

Most of these issues will be solved if the TRANSFER_SERVER endpoint (and the WEB_AUTH_ENDPOINT in SEP0010) are all defined under the asset itself ([CURRENCIES]), and not under the root of the stellar.toml file. 

This also makes life much easier for the wallet developer who wants to implement SEP0006. The developer only needs to look at the right entry under [CURRENCIES], without having to cycle back to the root for more info. 
It also sucks that to handle deposits/withdrawals for one asset, one has to load and parse the /info endpoint which contains unnecessary information about other assets.

TRANSFER_SERVER should be placed under each asset.

**Comment by efritze** [comment]
Bump

**Comment by tomerweller** [comment]
This seems like a good idea @efritze. Can you create the PR? 
Also, do you think the `WEB_AUTH_ENDPOINT` and the `SIGNING_KEY` (SEP10) should be asset specific?
