### ISSUE TITLE
SEP-0024/26: Require an amount parameter at the /withdraw endpoint

### ISSUE THREAD

**Issue by efritze** [stellar/stellar-protocol#434]
The solution to custom complex fee structures is not necessarily a separate /fee endpoint.

The fees can be calculated appropriately (and returned as fee_fixed) at the /withdraw endpoint if the amount query parameter is made mandatory.

Same could be said for the /deposit endpoint (though in the case of deposits the amount query parameter should be made optional)

Think of the typical asset withdrawal workflow. The end user will typically enter the amount they wish to withdraw, alongside the recipient's destination address. Then there'll probably be a confirmation step where the fees are shown. No need to call a separate /fee endpoint when the appropriate fees could easily be obtained from the /withdraw endpoint, alongside other useful info like the minimum amount to withdraw.

**Comment by msfeldstein** [comment]
Can you explain what you mean by `though in the case of deposits the amount query parameter should be made optional`?
