### ISSUE TITLE
SEP-0010: Should we verify the data key of ManageData operation?

### ISSUE THREAD

**Issue by overcat** [stellar/stellar-protocol#436]
Currently, we set the data key to `<anchor name> auth`, but we didn't verify it when we checked challenge transaction. Should we verify it?

**Comment by ire-and-curses** [comment]
I think the key is mostly just to aid debugging, and what goes there isn't required, just suggested. That keeps it flexible. Is there a particular reason you think it should be validated?

**Comment by overcat** [comment]
Thank you for your explanation.
