### ISSUE TITLE
Increaese Set Signer Limit

### ISSUE THREAD

**Issue by MuhammedKarakurt** [stellar/stellar-protocol#442]
Hey, I am Muhammed Ali

I am working on a blockchain project and we are using stellar. For a use case I need a multi signature account and I am using SetOptionsOperation for set signer to an account but we can add only 20 signers. So I have two questions.

Could you remove or increase this limit?
Why did you need this limit?

**Comment by tomerweller** [comment]
I believe 20 is used an arbitrary "small" number. Core scans account signers as part of the signature verification process so changing that to a "big" number would require architecture changes (probably to the protocol as well). Also, core limits the number of sub-entries (1000, I think) and signers count as sub-entries.

**Comment by msfeldstein** [comment]
Going to close this for now, if someone has use cases that would make this necessary we can reopen discussion
