### ISSUE TITLE
Proposal: testnet "friendbot" for anchored assets

### ISSUE THREAD

**Issue by jimdanz** [stellar/stellar-protocol#451]
We (AnchorUSD) have released a testnet "friendbot" that you can use to ask for as much testnet-AnchorUSD as you'd like.

Example call:
curl 'https://sandbox-api.anchorusd.com/transfer/friendbot?addr=GDKXL2HUL3FK6FAFFH54WIRFHMHPWNS72IL7QH3NXK6LRMDZPUE7KVK4&amount=50000'

* `addr` is required
* `amount` is optional, default 1000

We validate that the trustline exists and return an error if not.  In the success case, we return the raw response from Horizon (as does the XLM friendbot).

We used to get requests from people to give them testnet AnchorUSD.  We're happy to do so, but this makes it self-serve.  Particularly useful for folks who may be starting with trying to test withdraw functionality before deposit, or working on a trading app.

I propose this should be a part of the spec for anchors to implement.  Most likely as a testnet-only `TRANSFER_SERVER` endpoint.  What do folks think?

**Comment by tomerweller** [comment]
I love this idea. 
@jimdanz Can you submit a pull request?
@msfeldstein do you think this should be part of sep24 or something separate?

**Comment by tomerweller** [comment]
Or, come to think of it, shouldn't the mock deposit provide that functionality?

**Comment by msfeldstein** [comment]
I'd prefer it not be part of SEP24 this would be useful in many other
places.  The mock deposit functionality seems quite different in that it is
required in the context of a transaction, even if it can end up being used
for the same purpose.

Ideally this would be its own SEP, you'd have a 'friendbot' api endpoint in
your toml that you POST a stellar_account, and optional amount to.

Overall its a great idea that we should definitely do.

**Comment by msfeldstein** [comment]
also maybe we call it faucet instead of friendbot so people coming from other crypto projects are more famililar?

**Comment by leighmcculloch** [comment]
Can we rename the lumen testnet friendbot to faucet too for consistency?

> Most likely as a testnet-only `TRANSFER_SERVER` endpoint.

I think we should consider making the URL a separate config value in `stellar.toml` instead of making it a new endpoint on the existing `TRANSFER_SERVER`. I don't think there's a ton of reasons that they need to be part of the same set of endpoints, and then it will also be easier to express as a standalone SEP.

**Comment by msfeldstein** [comment]
> I think we should consider making the URL a separate config value in stellar.toml
Definitely.  The endpoint can be inside the transfer server, but we should point to it directly.

**Comment by jimdanz** [comment]
Thanks for the responses!  I'm +1 to having it a separate URL in stellar.toml.  It's a great point because any issuer can have a faucet even if they don't implement SEP-0024.

I agree that faucet is a more helpful name.

TBH if you're considering renaming friendbot, I'd advocate for renaming it to `account-creator-bot` or such.  The fact that it is _strictly_ unable to give lumens to accounts that already exist can be pretty confusing when you're new to Stellar.

The anchor faucets that I'm proposing wouldn't have that limitation.  As long as you have the trustline they'll be happy to give you the asset, as many times as you like [I see no downside to that].

Happy to submit a pull request.  Should it be its own SEP or just a PR to SEP-0001 (like #413)?  @tomerweller @msfeldstein 

/cc @andywer

**Comment by jimdanz** [comment]
Also @andywer pointed out that the Anchor could issue multiple assets.  So the faucet should take `asset_code` as a parameter the same way `/transfer/deposit` does.

**Comment by msfeldstein** [comment]
I think it should be it's own sep.  There's enough detail to it to warrant its own sep.

And yes it should take asset_code, and probably issuer as well (the same anchor/toml-file can issue multiple currencies from separate keys)
