### ISSUE TITLE
SEP-24 withdrawal transaction id response

### ISSUE THREAD

**Issue by istrau2** [stellar/stellar-protocol#456]
This issue refers to this part of SEP24:

> The anchor's internal ID for this deposit / withdrawal request. The wallet will use this ID to query the /transaction endpoint to check status of the request.

While some anchors produce a specific reference or transaction id for each request, man anchors (including Stellarport) do not have a transaction id at the time of withdrawal instructions request (this depends on the anchor usecase). 

The proposal here, is for the `id` parameter to be optional (i.e. anchor can return it or not). Depending on whether or not the `id` is included in the response, the wallet will poll (to initiate the withdrawal) differently:

- If the `id` is included, the wallet will poll the `/transaction` endpoint (with the returned id). Once the endpoint returns `pending_user_transfer_start`, the wallet will initiate the withdrawal.
- If the id is not included, the wallet will poll the `/transactions/interactive/withdrawal` endpoint. Once the endpoint returns a `200` status, the wallet will initiate the withdrawal.

**Comment by msfeldstein** [comment]
I still think this creates a bad UX.  If someone tries to do a deposit, and they get to the point where they have to say, go to a bank to make a physical deposit, the app has no way to track that this is happening for the user. The wallets should have a way of saying "the user started a deposit, here is it's pending state so they can jump back into the flow".

It might make sense for people used to crypto exchanges to see transactions as just a crypto address they send money to, but for most people in the world they want to start a deposit and then see it to completion.

**Comment by istrau2** [comment]
Ok, fair enough. I see where you are coming from with respect to fiat. I think its debatable if the UX is better w.r.t to crypto, perhaps yes.

However, I still think the SEP should respect anchors whose systems are not built that way (i.e. where the transaction is created on deposit instructions request). It seems there are many anchors that only create the transaction on receipt. Its pretty easy to support too... it just means the wallet has to poll a different endpoint...

**Comment by msfeldstein** [comment]
Is there a reason you need your system to be built without txid's until the last minute?  If its simply an implementation detail that would be fairly easy to change i think we should keep the spec as uniform as possible with as few branches.

If there's a reason why its better to not create txid's at start then we can figure out the proper way to change the spec

**Comment by msfeldstein** [comment]
> it just means the wallet has to poll a different endpoint...

It means the wallet has to now keep track of transactions in 2 different ways, in addition to changing the way in which it polls even a single transaction as it moves from no-txid to having a txid.  This adds a good bit of app level complexity and failure cases.

**Comment by msfeldstein** [comment]
From an off-channel conversation, seems like wallets do want the txid asap and anchors are on board for it

```
we would prefer to have anchors return the pending withdrawal attempts even if the funds have not been sent by the user.

otherwise, I guess the UI could be confusing - we could end up with ppl starting multiple attempts to withdraw, as they don't have any visual indication of the withdrawal process.

I guess it's kinda OK if you would "drop" the old (i.e. 30 days+) unfunded withdrawal attempts from the /transactions endpoint, but having something to show to user to inform him that he has indeed started the withdrawal request and see the status is quite important.

example: user starts withdrawal, fills in KYC. anchors takes 24 hours to review KYC. until KYC review is completed, it's important to show the pending withdrawal attempt, I assume the status should be "pending_anchor". 
the wallet does not allow to send funds, while the status is "pending_anchor", but still should show the pending attempt.

let's say, in 24 hours the KYC is approved, and the status changes to "pending_user_transfer_start". The wallet can now show a "Complete withdrawal" button in the UI, which would finish the transaction and send funds to the anchor.

if the anchor does not generate the ID, and the /transaction response is empty, I don't see how we could implement such flow to prevent confusion from the user.

so, our take: please generate tx ID immediately.
I'm hoping that the example above highlights why this is important for us. lmk if I missed something :)
```
