### ISSUE TITLE
Trouble implementing SEP0011 in other languages (JavaScript)?

### ISSUE THREAD

**Issue by pselden** [stellar/stellar-protocol#461]
Since SEP0007 recently included a section for "replace" that uses SEP0011's as a way to represent which fields need to be replaced, I've been working on adding it to my TypeScript implementation (https://github.com/stellarguard/stellar-uri/pull/10). Now, it's easy enough to represent the replacement in the URI, but performing the replacement is a different matter.

I went searching for implementations of it and of course found @stanford-scs reference implementation here: https://github.com/xdrpp/stc/blob/master/stcdetail/txrep.go#L280

When I was trying to follow along with what it did, I noticed that it was able to use a very generic XdrMarshal method to handle most of the converting: https://github.com/xdrpp/stc/blob/master/stcdetail/txrep.go#L280 -- implementation here (https://github.com/xdrpp/goxdr/blob/7b19e304c65626a37b59d214087edbc9d3d7bb7c/cmd/goxdr/goxdr.go) and didn't really have that much Stellar specific things in it.

However when I went to implement it in JavaScript I did not find any similar method. The closest I found was https://github.com/abuiles/json-xdr, which lets you convert a transaction to JSON -- and since the txrep is sort of like JSON-path I was hoping I could use that. Unfortunately there are some differences that make it hard to use. See https://gist.github.com/pselden/0f16099c355b18435bbd3b244da7e916 for how the reference example is converted to JSON. Key differences are the _type fields (differ both in key name and the actual values for them -- EX: `PATH_PAYMENT` -> `pathPayment`, account representations, and assets.

So instead I believe I have to use some _very_ Stellar specific parsing, with room for error and modifications that I will have to make every time something in the stellar js lib changes as well.

Here is my first attempt: https://github.com/stellarguard/txrep/blob/initial-commit/src/lib/txrepToTx.ts#L12-L29 -- you'll notice how I have to basically treat every single field as a special case -- with operations being the worst offender: https://github.com/stellarguard/txrep/blob/initial-commit/src/lib/txrepToTx.ts#L118-L153

Anyway -- I just wanted to ask here since it seems like the goal of SEP0011 was to make it _easy_ to parse and convert -- am I missing something here, or is the format too tightly coupled with the C/Go XDR parsers?

**Comment by pselden** [comment]
Additionally, parsing comments out of the values seems like it's going to be one of the hardest parts about this since there's no clear separator between comment and value.

**Comment by stanford-scs** [comment]
@pselden I think in retrospect one mistake we have made is to make it harder to do automatic conversion/processing of XDR, precisely because of the kind of issues you have run into (e.g., `PATH_PAYMENT` vs. `pathPayment`).  I would like to see us move in a direction where these kinds of conversions are "dumber"--i.e., they might not match the normal style or case conventions of the language, but it is much easier to do them mechanically.  `goxdr` is a step in this direction for go, and I would ideally like to see this happen for other languages.

I'm happy to discuss working this from multiple angles.  For example, if there are things in txrep that are annoyingly too C/go-specific, we can tweak the spec.  It also wouldn't be too hard to modify `goxdr` to output JavaScript as well.  Having an XDR representation that allows generic traversal can greatly improve productivity, and more importantly accommodate future protocol upgrades without a lot of additional work.

**Comment by pselden** [comment]
Is that a problem with the lower level js-xdr library? Or something specific to the stellar libs that use it? I did notice that the .x files have all the upper case enum names like PATH_PAYMENT.

I decided to take two approaches for this:

1. Continue with the manual parsing of the txrep and treating each field individually, using the higher level stellar-js-sdk to build the Transaction. I know this will work but as you mentioned it's a bit of work and will need to be constantly maintained. However to get something working it's probably my clearest path. It also has the benefit of getting any argument validation that the stellar-js-sdk uses.

You'll see that I have to do lots of switch statements on both sides of the conversion: https://github.com/stellarguard/txrep/commit/8a606900ec425150af40b1ab6f4c800a58f5fe1f#diff-08aaf5d63e6416f92bb675a5d86fff5bR81-R88 and https://github.com/stellarguard/txrep/blob/initial-commit/src/lib/txrepToTx.ts#L158-L177

2. After I get it working I want to try to generalize it. The plan was to use json-xdr to come up with a "pretty close" representation of an unflattened txrep object (txrep keys are basically JSON paths so you can inflate them to build an object from them), and then determine the transformations needed to convert from one to another. This still has some downsides of needing to know what keys need to be transformed and how to do it, but it might end up with some smaller code. Still maintenance required though.

A couple things in txrep that I noticed in my implemenation:

1. Would help to simplify how comments are delineated -- the wording in the SEP makes it seem like anything after the value can be a comment. But that means I actually need to define a formal grammar parser instead of doing some quick and dirty splits and regex. That makes it much harder to implement it (at least for me). Even saying something like: comments are enclosed in parentheses immediately following the value plus a space would help.

2. All of the meta fields (including len) should start with a _. (Actually here's a question... is type actually a meta field or is part of the XDR definition?) That makes it easier to tell whether it's ok to ignore them. When "inflating" the txrep to a json object in order to make it easier to operate on those special fields interfere with it (like adding a len property to an array) so my implementation just removes them.

**Comment by stanford-scs** [comment]
@pselden Agree on the holy grail of getting everything closer to XDR.  One plausible approach might be to add a javascript option to goxdr.

In terms of parsing, the comment just starts with whitespace.  Is that somehow harder to parse than if it started with anything else, like `#`?  Of course you have to be careful with quoted strings, but that's true regardless of how comments start.  The regular expression is `[ \t]`, which may be quick but doesn't seem especially dirty...

We went back and forth on the name of `len`, but ended up deciding since there was never any ambiguity it didn't matter.  I don't have an inherent objection to `_len` other than compatibility with what is already deployed.  But is there an ambiguity?  It seems like you would first check the type to see if it is an array or not, and only then look at the length.

**Comment by pselden** [comment]
> One plausible approach might be to add a javascript option to goxdr.

It might make it easier to operate on server-side (shell out to goxdr and parse the resulting JS object), but unfortunately we can't use it in the browser -- unless i'm misinterpreting how you think that would be used.

There's no ambiguity in `len` vs `_len`, but consistency is king in my book -- but yeah now that it's done it's done. The problem it presented was likely just in my implementation of it -- in order to make it easier to operate on it I first take the txrep and turn it into a raw JavaScript object.

EX:

```
tx.sourceAccount: GCUNWINQBGP6ZLAFNAU74OYZCMPBY4NQO6RCOBL2LEUKIWV3VQO7YOBF
  tx.fee: 100
  tx.seqNum: 1375042369748993
  tx.timeBounds._present: true
  tx.timeBounds.minTime: 0
  tx.timeBounds.maxTime: 0
  tx.memo.type: MEMO_NONE
  tx.operations.len: 1
  tx.operations[0].sourceAccount._present: true
  tx.operations[0].sourceAccount: GCUNWINQBGP6ZLAFNAU74OYZCMPBY4NQO6RCOBL2LEUKIWV3VQO7YOBF
  tx.operations[0].body.type: CREATE_ACCOUNT
  tx.operations[0].body.createAccountOp.destination: GBAF6NXN3DHSF357QBZLTBNWUTABKUODJXJYYE32ZDKA2QBM2H33IK6O
  tx.operations[0].body.createAccountOp.startingBalance: 123400000 (12.34e7)
  tx.ext.v: 0
  signatures.len: 0
```
becomes
```
{
    "tx": {
      "sourceAccount": "GCUNWINQBGP6ZLAFNAU74OYZCMPBY4NQO6RCOBL2LEUKIWV3VQO7YOBF",
      "fee": "100",
      "seqNum": "1375042369748993",
      "timeBounds": {
        "minTime": "0",
        "maxTime": "0"
      },
      "memo": {
        "type": "MEMO_NONE"
      },
      "operations": [
        {
          "sourceAccount": "GCUNWINQBGP6ZLAFNAU74OYZCMPBY4NQO6RCOBL2LEUKIWV3VQO7YOBF",
          "body": {
            "type": "CREATE_ACCOUNT",
            "createAccountOp": {
              "destination": "GBAF6NXN3DHSF357QBZLTBNWUTABKUODJXJYYE32ZDKA2QBM2H33IK6O",
              "startingBalance": "123400000"
            }
          }
        }
      ],
      "ext": {
        "v": "0"
      }
    }
  }
```

Since I'm building that object up one line at a time, when it sees that ".tx.operations.len: 1" line it actually builds an object out of it, not an array

```js
{
  tx: {
    operations: {
       len: 1
    }
  }
}
```
At this point since it's an object an not an array it messes the rest of it up.

Anyway, this is probably not something anyone else would encounter so maybe not a big deal. It just caused a few failed tests at first.

--- 

I'm slowly getting to a working solution for this all, although in many more lines of code than I wanted. When I switched to scanning the line character by character instead of doing splits/regexes it became easier to parse the comments. You're right that the quoted strings were the the part that gave me the most headache. Thanks for the pointers.

**Comment by pselden** [comment]
Just did an initial release of the JS/TypeScript lib: https://github.com/stellarguard/txrep -- demo here: https://stellarguard.github.io/txrep/demo/
