### ISSUE TITLE
SEP24: Should it support DELETE requests? 

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-protocol#481]
A user might want the anchor to "forget" their KYC information. 
Some potential reasons: 
- Privacy - a user is not interested in their information being stored on the anchor side anymore. 
- Testing - Repeatedly testing deposits/withdraws in production, including KYC steps. 

Alternatively, instead of being a part of the protocol this could be a best practice for anchors to implement a delete flow on their website.

**Comment by ire-and-curses** [comment]
The anchor could also have to comply with GDPR if they have European users.
