### ISSUE TITLE
Clarify the flow of statuses in sep24

### ISSUE THREAD

**Issue by msfeldstein** [stellar/stellar-protocol#488]
The list of statuses in sep24 is a bit confusing.  We should clearly explain the flow (state machine?) of statuses, and also provide examples of when to use each status.

https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#fields-for-withdraw-transactions

**Comment by msfeldstein** [comment]
[Status Diagrams.pdf](https://github.com/stellar/stellar-protocol/files/4094781/Status.Diagrams.pdf)

**Comment by msfeldstein** [comment]
![State Diagram](https://user-images.githubusercontent.com/161135/72857372-4a608800-3c72-11ea-98ee-d8cffc8095b7.png)

**Comment by leighmcculloch** [comment]
That diagram helped a lot. What did you use to create it? Is there anyway we can codify the diagram into the stellar-protocol repo so that the source and rendered image are stored here and easily editable?

**Comment by msfeldstein** [comment]
It's just in figma, but i want to look at something like mermaid to see if that can do what you're asking now that i have the basic structure.
