### ISSUE TITLE
Remove pre-authorization signer even if signature verification fails

### ISSUE THREAD

**Issue by sisuresh** [stellar/stellar-protocol#495]
## Issue
If signature verification for a pre-auth transaction fails, the pre-auth signer needs to be manually removed using the Set Options operation. If the sequence number for the failed transaction has been consumed, the pre-auth signer can never be used again, so there's no reason to keep it around.

## Proposal
If the transaction signature is invalid, clean up the pre-auth signers right after the sequence number is consumed. 

## Specifications

`removeUsedOneTimeSignerKeys` will be called in `TransactionFrame::apply` if `commonValid` returns `ValidationType::kInvalidUpdateSeqNum`.

```c++
auto cv = commonValid(signatureChecker, ltxTx, 0, true);
if (cv >= ValidationType::kInvalidUpdateSeqNum)
{
    processSeqNum(ltxTx);

    if (ltxTx.loadHeader().current().ledgerVersion >= NEXT_LEDGER_VERSION 
        && cv == ValidationType::kInvalidUpdateSeqNum)
    {
        removeUsedOneTimeSignerKeys(signatureChecker, ltxTx);
    }
}

auto signaturesValid = cv >= (ValidationType::kInvalidPostAuth) &&
                        processSignatures(signatureChecker, ltxTx);
```

If `cv` returns a higher value, then we default to the current behavior where `processSignatures` calls `removeUsedOneTimeSignerKeys` since the signature verification for the operations may depend on the one time signer keys.

**Comment by jonjove** [comment]
Implemented in CAP-0028
