### ISSUE TITLE
Remove NO_ISSUER Operation Results

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-protocol#497]
The following operation results indicate that an operation failed because the issuer of an asset does not exist: `PAYMENT_NO_ISSUER`, `PATH_PAYMENT_STRICT_RECEIVE_NO_ISSUER`, `PATH_PAYMENT_STRICT_SEND_NO_ISSUER`, `MANAGE_SELL_OFFER_SELL_NO_ISSUER`, `MANAGE_SELL_OFFER_BUY_NO_ISSUER`, `MANAGE_BUY_OFFER_SELL_NO_ISSUER`, `MANAGE_BUY_OFFER_BUY_NO_ISSUER`, and `CHANGE_TRUST_NO_ISSUER`. Each of the operations that can produce these results other than `ChangeTrustOp` does not otherwise depend on the existence of the issuer. As for `ChangeTrustOp`, the situation is more complicated because the result does actually depend on the state of the issuer account (specifically, the flags such as `AUTH_REQUIRED`). But any account is able to create the issuer account if it does not exist, even if they do not know the underlying private key. Therefore it is sensible to set the behavior of `ChangeTrustOp` to default to no flags if the account does not exist, since any account is able to force this behavior anyway. Analogously, any account can avoid this result in the other operations by first creating the issuer account.

Given the above, I propose to remove all `NO_ISSUER` results. This is related to the development of CAP-0023 (Two-Part Payments) because otherwise we may want to return `NO_ISSUER` results there as well.

**Comment by MonsieurNicolas** [comment]
I would support this change.

Maybe one thing that would be left related to this is deciding on what to do with trust lines that are not authorized, have a balance and the issuer doesn't exist.

Reason it should be fixed at the same time is that it doesn't seem to make sense that creating a new account with a new key would have more rights than an existing one that was frozen in the past.

We can:
* either allow such accounts to "send back" to the non existent issuer (we would also allow this to happen even if the issuer exists). Basically treat "frozen" as "removed from total supply".
* or consider that "no issuer" is equivalent to being an unrestricted assets (what the `ChangeTrustOp` change above implies), so ignore the authorization flag when the issuer doesn't exist.

I think option 1 is cleaner and has the benefit of not having performance overhead (we don't need to load the issuer).

**Comment by jonjove** [comment]
@MonsieurNicolas I'm not sure if I agree with you about changing the behavior of
> trust lines that are not authorized, have a balance and the issuer doesn't exist

Under the current protocol, if the issuer account were toggled from `AUTH_REQUIRED` to not `AUTH_REQUIRED` after revoking authorization from some accounts then those accounts would remain unauthorized while new accounts would be fully authorized. Because toggling an issuer account from `AUTH_REQUIRED` to not `AUTH_REQUIRED` is conceptually the same as deleting the issuer account, I don't see any reason they should behave differently.

I think that option 2 presents issues from a backwards compatibility perspective, because it would restore authorization to accounts that the issuing party believed would never be authorized again without explicit action. 

I'm not opposed to option 1, but I'm also not convinced it's directly related to the `NO_ISSUER` return codes. Can you provide more information about why you think it would be a good idea to do both changes at the same time?

**Comment by MonsieurNicolas** [comment]
Reason I'd like to fix it is that it seems it's the last big bug related to issuers: it's a violation of one design principle where an account cannot "wedge" a different account. In this case, an issuer deleting the issuing account breaks any account that is not authorized as those trust lines cannot be deleted.

Yeah I agree that option 2 is not desirable, I listed it for completeness as it's the only other option to burning tokens if we don't want accounts to be "wedged" if an issuer is clearly gone (there is no home domain attached to the token for example).

**Comment by jonjove** [comment]
@sisuresh Some comments on the proposal. 

> Remove every `*_NO_ISSUER` result from `Stellar-transaction.x`

This is wrong (and doesn’t match your implementation). This proposal requires no XDR changes.

> For every operation that can return a `*_NO_ISSUER` result, remove the issuer check code along with the result.

This is wrong (and doesn’t match your implementation). These results must still be returned prior to protocol version 13.

> For the `ChangeTrustOp`, remove all `CHANGE_TRUST_NO_ISSUER` results. When checking the `AUTH_REQUIRED` flag on the issuer, check if the issuer exists first. If not, the `TrustLine` will not be authorized on creation.

This is wrong, and also wrong in my original comment https://github.com/stellar/stellar-protocol/issues/497#issue-537250280. Sorry about that. I wrote “Therefore it is sensible to set the behavior of `ChangeTrustOp` to default to no flags if the account does not exist, since any account is able to force this behavior anyway.” What I should have written is “Therefore it is sensible to set the behavior of `ChangeTrustOp` to default to `AUTHORIZED_FLAG` if the issuer does not exist, because anyone can force this behavior anyway by creating the issuer with no flags set.”

Nitpick: these proposals are meant to be read by people who are familiar with the specification of stellar-core but not the implementation (eg. developers of downstream systems such as Horizon and SDKs, developers of a distinct implementation of the Stellar protocol). For this reason, I don’t think sample code is particularly valuable unless it references only the XDR. Generally, description of the behavior will likely help more. For example, you might write something like “If the issuer account `A` exists, then the trust line flags should be set to 0 if `A.flags & AUTH_REQUIRED_FLAG` and `AUTHORIZED_FLAG` otherwise. If the issuer account does not exist, then the trust line flags should be set to `AUTHORIZED_FLAG`.” (I’m not saying include this exact phrase, I’m just providing feedback on how to make these documents more accessible.)

**Comment by jonjove** [comment]
Implemented in https://github.com/stellar/stellar-core/pull/2389
