### ISSUE TITLE
What key does the sending FI use to specify their refund address?

### ISSUE THREAD

**Issue by ace-subido** [stellar/stellar-protocol#50]
[The documentation](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md), says that the sender should attach the refund address to the "attachment" json. What should the key be?

**Comment by bartekn** [comment]
The article you linked is about `tx_status` that returns information about transactions that have been already sent.

> `refund_tx` only appears if the status is "refunded". It will be the txID of the tx sending the money back. The address to send the refund to needs to be sent as part of the original payment attachment otherwise the receiver won't know how to refund.

So it's there only if transaction has been refunded. Currently there is no way to send refund address via Compliance protocol. FIs should just sent funds back to the sender.
