### ISSUE TITLE
SEP-24: Which endpoints require SEP-10 auth?

### ISSUE THREAD

**Issue by yuriescl** [stellar/stellar-protocol#520]
Currently SEP-24 states the following about using SEP-10 authentication:

> As stated, Anchors must support SEP-10 web authentication to enable authenticated deposits, withdrawals, or transaction history lookups. Clients must submit the JWT previously obtained from the anchor via the SEP-10 authentication flow to all API endpoints.

> The JWT should be included in all requests as request header

Just want to clarify if all SEP-24 endpoints must require a SEP-10 authentication token, or there are exceptions (ex: `/info`). I don't see why it would be needed in `/info` since it provides public information, like `stellar.toml` does.

**Comment by JakeUrban** [comment]
As an anchor, you're free to make an exception for `/info`, but wallets should assume all endpoints need the token.

**Comment by msfeldstein** [comment]
https://github.com/stellar/stellar-protocol/pull/522

After discussing more it seems important to keep /info unauthenticated so other non-wallet applications can access that public information.
