### ISSUE TITLE
SEP-26 backward compatibility

### ISSUE THREAD

**Issue by istrau2** [stellar/stellar-protocol#521]
This is a similar issue with SEP-24. Can we make the SEP-26 endpoints new and not use the same ones as SEP-6. For example, can we user `transactions/withdraw/noninteractive` and `transactions/deposit/noninteractive`

**Comment by msfeldstein** [comment]
SEP-26 endpoints can use whatever prefix you want so if you have a conflict and already have a sep6 deposit endpoint at `mydomain.com/deposit` you can have your api path be `mydomain.com/non-interactive` and the deposit url will be `mydomain.com/non-interactive/deposit`.  I don't think we need to make any modifications to the actual endpoint names, but lmk if i am off base here
