### ISSUE TITLE
Update threshold range from 0-255 to 1-255

### ISSUE THREAD

**Issue by nikhilsaraf** [stellar/stellar-protocol#54]
The intention of this issue is to start a conversation around this topic; see conversation from a PR about a change in the docs for multi-sig: https://github.com/stellar/docs/pull/237#discussion_r145478808

**Background:**
A threshold of `0` and `1` are effectively the same since we need at least 1 key with a non-zero weight to sign a transaction. By allowing a threshold of `0`, we are creating an exception case for the logical condition `sum_key_weights >= threshold` to make it more like `(sum_key_weights >= threshold && threshold > 0) || (sum_key_weights > threshold && threshold == 0)` where we treat a 0-threshold differently from a non-0 threshold to account for signing transactions with a key that is weighted at 0.

**Proposed solution:**
If it's possible to limit the minimum threshold to be `1`, we can simplify the condition to be the former, `sum_key_weights >= threshold` for all cases and more importantly, this will make it simpler for users to understand.
The tricky part here would be dealing with existing accounts and having to update all of them to use this new range (change all `0` thresholds to a `1`). There may be other approaches that could make this easier.

**Comment by nullstyle** [comment]
I think the threshold behavior is more succinctly expressed as `sum_key_weights >= threshold && sum_key_weights >= 1`, right?

**Comment by nikhilsaraf** [comment]
yeah, that's a better way to express that condition.
In the case of your expression the exception case would be `sum_key_weights >= 1`, which can be avoided by limiting the range.

**Comment by MonsieurNicolas** [comment]
The current semantics are that a weight of 0 means the key is (logically for the master key) deleted from the list of signers; this is consistent with how `SetOptions` works.
