### ISSUE TITLE
SEP-0010/0030: Evaluate usage of url-encoded form / json content types

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/stellar-protocol#557]
In [SEP-10] we support request bodies to be in JSON or url-encoded form content types. There's an overhead for every implementer of a SEP to implement two request parsing models. In some programming languages this is really easy, in others it may not be so.

We shouldn't remove the use of a content-type from an existing SEP, but we should evaluate if this is a pattern we should apply to future SEPs or if we should stick with a single request body type (i.e. JSON) from here on.

@nebolsin introduced the concept of supporting url-encoded forms as well in SEP-10 and shared some points for why it is beneficial, see stellar/stellar-protocol#150 for more details there. We should weigh these benefits with the costs and usage that we can find.

I'm considering this because I'm writing [SEP-30] that has to choose to include it or not.

[SEP-10]: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md
[SEP-30]: https://github.com/stellar/stellar-protocol/pull/553

**Comment by leighmcculloch** [comment]
👋 @stellar/integration Do you folks have any insight into whether people prefer to use url-encoded form or JSON for request bodies when implementing SEPs?

I notice that [SEP-24] actually supports only `multipart/form-data`. Is there a reason it uses multipart and not `application/x-www-form-urlencoded`?

[SEP-24]: https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md

**Comment by JakeUrban** [comment]
The SEP should be updated, Polaris uses `application/x-www-form-urlencoded`.

I don't have any insight for anchors' encoding preference, but I agree with the comments made in [#150](https://github.com/stellar/stellar-protocol/pull/150). I would assume JSON is more popular but at the same time I'd be surprised if implementing the parsing logic for 2 encodings was non-trivial for any mainstream language.

**Comment by leighmcculloch** [comment]
I'm going to close this and continue with supporting both in SEP-30. This went the opposite way than I expected with SEP-24 getting expanded to support it in #558 😄. Great outcome! Thanks Jake!

**Comment by leighmcculloch** [comment]
FYI @accordeiro
