### ISSUE TITLE
Forced account_merge

### ISSUE THREAD

**Issue by bartekn** [stellar/stellar-protocol#56]
This should work like `account_merge` operation but before merging it'd remove all subentries. Trust lines balances are sent to:
* `destination` for shared trust lines.
* to issuer if `destination` does not have a trust line.

Use cases:
* Some projects (ex. [Bifrost](https://github.com/stellar/go/pull/81)) may require configuring account (ex. creating trust lines) before displaying secret key to the end user. If something goes bad (network connection, browser crash) account should be merged back to funder. Currently, Bifrost creates 4 recovery transactions but with forced `account_merge` it would need only one.

**Comment by nullstyle** [comment]
Shouldn't you just need 1 transaction with 4 operations?

**Comment by bartekn** [comment]
No. Depending on a stage we're in, account may have trust lines (or not) or have credit assets (or not).

**Comment by nullstyle** [comment]
I don't understand why that's an issue:  If they don't have trustlines, don't remove them, just do the account merge.  If they have trustlines send the money to wherever they want in an operation that occurs before the account merge.

**Comment by bartekn** [comment]
Well, we're doing this now but for more complicated processes you basically end up with bunch of transactions (and bunch of code to create them). You also need to know exact amount of asset you have to send them back and sometimes it's not possible to determine.

Let's say I'm OK with the current solution but with forced `account_merge` it would be just way easier.

**Comment by nullstyle** [comment]
What situation requires more than one transaction?  

---

My concern is that people will not understand the ramifications of performing a forced merge.  Indeed, the entire concept of account merging is something that IMO we will need to hide from end users:  My hunch is that people just want to close their accounts... they don't care about the technicalities beyond "where is my money going when I close this?"

Frankly, if a developer is merging and account on behalf of an end user I think it is strictly better if we make them drain the account manually.  Closing an account shouldn't be easy enough that you put at risk the certainty of what is going to happen when you close the account.

---

IMO a safer solution would be to build a comprehensive document titled "Every dirty little secret you need to know when closing a stellar account" or something similarly cheeky ;)

**Comment by MonsieurNicolas** [comment]
yeah merging a trustline may mean many things depending on the asset type (in some cases you want to send back to the issuer, in others send to the destination account). I'd rather have explicit business logic to deal with this than guess at the protocol layer (and potentially cause grief).

**Comment by jedmccaleb** [comment]
I think the issue bartek is having is that the account you are trying to merge back in can be in several states. and the merge operations have to be presigned by the client so the server can't just look at the state of the account and craft the merge (since the server doesn't have the secret)

But, I'm still not sure we should have this operation. It seems too heavy handed.  I could buy having an operation that sends as much of an asset as it can rather than failing if the account doesn't have enough. I could see that being useful in a lot of contexts

**Comment by nullstyle** [comment]
> But, I'm still not sure we should have this operation. It seems too heavy handed. I could buy having an operation that sends as much of an asset as it can rather than failing if the account doesn't have enough. I could see that being useful in a lot of contexts

A "drain balance into X account" operation?

**Comment by jedmccaleb** [comment]
I mean, right now payments really mean "Send this exact amount to account" I want a payment that is "Send at most this amount to account"

**Comment by jedmccaleb** [comment]
Closing as is but someone could reopen with a  "Send at most this amount to account" operation
