### ISSUE TITLE
Drop the concept of rippling in favor of long lived offers

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-protocol#6]
Rippling and offers sort of serve the same function. It seems cleaner to combine the two concepts.
You can achieve the effect of rippling if you create two offers between two currency pairs.

This would just require a new flag on the offers saying that they never expire and are always offering at the given price as long as the owner has the takerGets currency.

**Comment by sunny-g** [comment]
But if you accepted n currencies, wouldn't you need to set up (n^2 -n) offers to simulate full rippling (though my math might be wrong if I'm misunderstanding something)? 
> Rippling is no longer needed since Stellar will be used more for centralized gateways than a p2p system.
I thought the point of Stellar was to be more p2p than Ripple...

**Comment by xekoukou** [comment]
Not really, offers are 'sticky'. You would only need 2n for n trust lines. 

I like Jed's idea. I don't understand what irsli is saying. I also want full p2p.

**Comment by irisli** [comment]
Sorry, p2p is a term used in many contexts. By p2p, I meant that I am not going to issue a irisliUSD and have it ripple through xekoukouUSD to sunny-gUSD. Instead, I would be using bigcompanyUSD and sending it to you through anothercompanyUSD. In the case of bigger gateways (and not a gateway per person), rippling is not very necessary.

**Comment by sunny-g** [comment]
>rippling is not very necessary.

Well if they can be adapted to do the same thing (offers and rippling), then only one is necessary. But one application I've been working on is social credit which necessarily has each user operate as a pseudo-gateway so naturally I don't want changes made that might remove that application entirely.

**Comment by irisli** [comment]
You'll still be able to accomplish the same things as rippling through market making with offers. Offers are more explicit and more easily controlled since it happens on the gateway's end (individual issuers as opposed to consumers of those credits). I do see what you mean by the (n^2-n) offers necessary to "ripple" this way through offers.

**Comment by xekoukou** [comment]
It seems to me that offers are a binary relation that is transitive.
http://en.m.wikipedia.org/wiki/Binary_relation
So only 2n.

This is not a removal of rippling. The opposite, it is an enhancement.
What can be removed is the dead code that treated both as separate while they are the same.

I really want to create xekoukouUSD.

**Comment by sunny-g** [comment]
>I really want to create xekoukouUSD.

@xekoukou why can't you do that now though with rippling? 

It seems to me then that in the end, this would just provide a greater degree of granularity rather than making full rippling among anything that qualifies as USD the default, which if so, is actually much better.

**Comment by xekoukou** [comment]
@sunny-g I can.

Granularity: exactly!

**Comment by sunny-g** [comment]
One thing that only just recently came to mind:

Rippling with trust lines sets limits such that if two types of IOUs were being traded against each other, there would be a limit to how much one can trade one for the other. How would this be maintained if one were establishing a market offer between their own IOU and someone else's?

**Comment by jedmccaleb** [comment]
this is done now

**Comment by sunny-g** [comment]
@jedmccaleb so offers have replaced trust lines? If so, two questions:

- Is information on how to use offers documented anywhere?
- Can you (the issuer, not consumer) still specify how many of a certain issuer's credit you're willing to hold as a result of accepting it in offers (essentially, can you still specify something that operates as a trust limit)?

**Comment by jedmccaleb** [comment]
Trust lines still exist: https://www.stellar.org/developers/learn/concepts/assets.html
"rippling" was replaced by just placing offers.

**Comment by sunny-g** [comment]
@jedmccaleb thank you for the clarification! With regards to offers, isi documentation like this still valid: https://github.com/stellar/docs/blob/master/learn/concepts/list-of-operations.md#manage-offer ?

**Comment by jedmccaleb** [comment]
yep
