### ISSUE TITLE
SEP-24: list available types for the fee endpoint

### ISSUE THREAD

**Issue by yuriescl** [stellar/stellar-protocol#614]
Allow Wallets to discover which types are available for the [fee endpoint](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#fee).

It currently states:
`type`: (optional) Type of deposit or withdrawal (SEPA, bank_account, cash, etc...).

Wallets should be able to discover which values are available for that `type` parameter.

**Comment by yuriescl** [comment]
@msfeldstein

**Comment by yuriescl** [comment]
SEP-6 also has a /fee endpoint, so the same suggestion applies there.

**Comment by JakeUrban** [comment]
I happened to be browsing the repo's issues and saw this. Here is what I always thought could be a solution to this.

Anchors could specify the `type` values and descriptions in the `/info` response:
```
{
    ...,
    "fee": {
        "enabled": false,
        "types": {
            "deposit": {
                "description": "`type` value to use for deposit transaction fees"
            },
            "deposit_over_20000USD": {
                "description": "`type` value to use for large deposits over $20k"
            }
        }
    }
}
```

This is similar to the structure for SEP-31's `/info` endpoint, which has an anchor-defined `fields` dictionary. @tomerweller @morleyzhi I'm curious what your thoughts on this may be. As of now we don't know if `type` is used in the ecosystem right?

**Comment by JakeUrban** [comment]
Not stale, just a part of a larger issue that we're planning to address
