### ISSUE TITLE
Feature Request: SEP-24 custom fields

### ISSUE THREAD

**Issue by yuriescl** [stellar/stellar-protocol#616]
SEP-6 has support for [custom fields (there's a "fields" field)](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0006.md#for-each-deposit-asset-response-contains) to be passed to `/deposit` and `/withdraw`, but [SEP-24 doesn't (no fields parameter)](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#for-each-deposit-asset-response-contains).
Some Anchors might want to support custom extra fields for `/transactions/deposit/interactive` and `/transactions/withdraw/interactive`, so a `fields` field would be useful in the `/info` response.

**Comment by msfeldstein** [comment]
Can you just collect this in the interactive flow itself? Whats the purpose of sending it to the API (and thus requiring the wallet to build a UI to collect it)

**Comment by yuriescl** [comment]
You're right. There's a very specific use case I'm working on, in which the Anchor allows the Wallet to pre-set some values before the interactive flow, but this might be too specific and not needed in the protocol.
