### ISSUE TITLE
Request: cleanup result for failed transactions containing multiple operations

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-protocol#621]
Right now the `txINNER` error code is quite confusing:
if a transaction containing multiple operations has one operation failing, the operation results after the failing operation are either defaulted to `0`, or operations are applied anyways (but their results are arbitrary).

Reason we picked this behavior originally was to try to give as much information to callers as possible so that callers can fix as many problems as they can.

In reality, this is just confusing, so we should fix that.

I think the fix should be to truncate the results up to the first failing operation (that way we can also "fast fail" the transaction - the transaction is failed anyways).

**Comment by tomerweller** [comment]
Agree that the current handling is very confusing. 
However, I'm concerned about having an operation results list that is shorter than the submitted operations list. That seems to break an implicit contract and might break existing code that relies on it.
What about adding an error code that explicitly means "This operation was not evaluated" ?

**Comment by ire-and-curses** [comment]
I like "operation not evaluated"as well. On Horizon side I think it would make it simpler for callers to reason about their tx and it seems unambiguous.

**Comment by MonsieurNicolas** [comment]
I also thought at first that adding a new error code to `OperationResultCode` was the least disrupting change; but then I realized that if there is code out there that looks at those results, they are buggy and would probably not be able to distinguish a "real" error code from an error code that says "not an error code", so crashing with an "out of bound" error or "NRE" seems like a better property to me.

Also, I don't see why we'd rely on sentinel values when we have control over the size of the result.

@ire-and-curses I am not sure I understand the ambiguity argument?

**Comment by ire-and-curses** [comment]
Ambiguous - I meant that returning results up to the first failing operation is a convention, which must be known, understood and the variable list length handled by the caller. Returning all the results can't be misunderstood. I do agree with your point about existing code potentially not inspecting the error type, but I'm not sure what the consequences of that would be. Probably any error would cause a general failure path to trigger on the caller side, which seems fine?

**Comment by MonsieurNicolas** [comment]
yeah the convention is that for operation `op_i` the result is `result_i`, but I am not talking about changing this

**Comment by MonsieurNicolas** [comment]
@jonjove not sure if we care about this

**Comment by jonjove** [comment]
I still care about this, mostly from the perspective that we should not be applying operations after the first failure (it's purely wasted computation). To fix that problem, we will need to sort out this issue somehow.
