### ISSUE TITLE
(meta) CAP process update

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-protocol#624]
Recent protocol changes help identify some gaps in the process, in particular there was some confusion on the responsibilities between the working group and the protocol committee.

Here are some changes I'd like to see and discuss.

# Working group updates

## Updated contribution model

A simple way to help add clarity to this stage is by providing guidance on how to run that working group, by setting up of the responsibility assignment matrix, and follow a [RACI](https://en.wikipedia.org/wiki/Responsibility_assignment_matrix#Role_distinction) like model.

The template preamble gets modified as to replace the ambiguous `Author` field by:
* `Recommender` - group of people that write the CAP
* `Owner` - (aka "Accountable" in RACI) the *one* person responsible for the CAP, ensures that the process is followed and is the decision maker on the CAP's content.
* `Consulted` - list of people that the workgroup consulted and got feedback from.

 _We're not including the `Informed` group in the template, as this can be tracked offline by the working group as needed (and a CAP with its related discussions are public anyways)._

When a PR is submitted to change a CAP, the `Owner` has to sign off on the change (ideally, the `Owner` is the one opening the PR as to make the merging process as quick as possible).

The `Owner` has to take special care of assembling a meaningful set of `Recommender` and `Consulted` as to included stakeholders impacted by the CAP.

## Updated section

A new section `Protocol Upgrade Transition` replaces `Backwards Incompatibilities`
    * `Backwards Incompatibilities` becomes a subsection and focuses on breaking changes
    * `Resource Utilization` is a new subsection that focuses on the impact on CPU, bandwidth, disk utilization.

### Semantic protocol changes

For changes that make semantic changes to the protocol, like the addition or change of operations.

Stakeholders must include a representative set of
  * downstream systems developers (Horizon, block explorers, etc)
  * SDK developers (golang, Javascript)

In some cases, application developers (or somebody representing their interest) can also be involved.

The motivation section should clearly show how the stack lights up and be specific about it.

### Ledger and historical subsystem changes

Stakeholders must include a representative set of
  * downstream systems developers (Horizon, block explorers, etc)
  * node operators

The motivation section should articulate the impact on stakeholders

### CAP process adjustments

When a CAP is ready to move out of draft, at the meeting with the committee:
 * the "motivation" and "goals alignment" sections
    * should clearly articulate how the CAP will ultimately be used and the impact it will have on the overall network.
    * should have compelling evidence of the feasibility of those projects. In some cases, the evidence may link to related SEPs, prototypes, white papers, etc.
 * the working group must be available to respond to questions raised by the committee.

**Comment by jonjove** [comment]
This seems great. One other minor thing I've mentioned in the past is that we aren't making any use of the "Test Cases" section. We should either articulate how to use this section correctly and _actually_ use it, or we should remove it. Either path is fine by me.

**Comment by ire-and-curses** [comment]
> * Resource Utilization is a new subsection that focuses on the impact on CPU, bandwidth, disk utilization.

Utilization by what? Stellar Core? Or downstream?

> The motivation section should clearly show how the stack lights up and be specific about it.

What does "how the stack lights up" mean?

**Comment by tomquisel** [comment]
I like this update to the process! The most important part I'd like to see included in the CAP process is a part where the the expected changes to the following systems are mapped out at a high level:
* Horizon
* SDKs
* ecosystem apps

Ideally changes to the Horizon REST API, key changes to the SDK interfaces, and key changes to the ecosystem apps can be written out explicitly, and confirmed / approved as part of the CAP approval. 

This avoids scenarios where the CAP designers think SDKs should be updated one way, and SDK maintainers think a different approach is better, and the disagreement isn't detected until the changes are already implemented.

It also helps to better explore unexpected implications of CAPs, although obviously it cannot do this perfectly.

It probably makes sense to have a section of the CAP that links to the SEPs, Horizon & SDK interface changes that will be part of implementing the CAP.
