### ISSUE TITLE
Feature Request: Asynchronous Voucher Transactions

### ISSUE THREAD

**Issue by stanbar** [stellar/stellar-protocol#630]
### What problem does your feature solve?
For my project build on Stellar, I need to create an asynchronous "voucher" transactions that can be redeemed (published to the network) any time, in any order. 
I know that it can be achieved by channels. The voucher distributor creates a channel account for each "voucher" transaction. This channel account is then the source of the transaction for redeeming "voucher", and the voucher is valid as long as no one uses the same channel to publish transactions (bumping seq number).
In my case, there is one more limitation. The distributor must not know the channel secret key. Therefore he can not create such channels upfront. The channel secret key must be private to the user who is going to publish the transaction to the network. That way, he is sure that his "voucher" is always valid (no one can bump the seq number). 
Everything would be great if not the fact, that channel is a stellar account, which must be funded by 1 XLM. Therefore two transactions must be submitted to the network. Which is unacceptable in my case. Everything should be contained in one "voucher" transaction.

### What would you like to see?
 Here is an example:
```js
const channelKeypair = StellarSdk.Keypair.random()
const channelPublicKey = sourceKeypair.publicKey();
const channelAccount = await server.loadAccount(sourcePublicKey);

const transaction = new StellarSdk.TransactionBuilder(channelAccount, {
  fee,
  networkPassphrase: StellarSdk.Networks.TESTNET
})
  .addOperation(
    StellarSdk.Operation.createAccount({
      source: distributorPublicKey,
      destination: channelPublicKey,
      startingBalance: "1.00003"
    })
  )
  .addOperation(
    StellarSdk.Operation.payment({
      source: distributorPublicKey,
      destination: doesntReallyMatter,
      asset: voucherToken,
      amount: "1"
    })
  )
  .addOperation(
    StellarSdk.Operation.accountMerge({
      destination: distributorPublicKey,
    })
  )
  .build();

transaction.sign(channelKeypair);
requestDistributorSign(transaction);

// wait some time ...

server.submitTransaction(transaction)
```

Right now it won't work since channelAccount is not created yet, even the fact that its creation op is contained in such transaction.

What I would like to see, is the ability to `source` the transaction from account that is not yet created, but its creation op is included in such transaction

### What alternatives are there?

Channel can be created by third party, which the distributor has no access to, but it is a dirty  workaround.

**Comment by MonsieurNicolas** [comment]
Would something like [CAP-0023](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0023.md) solve your problem?

**Comment by stasbar** [comment]
What is the maximum number of claimants ?
And what are the types of predicates ?

**Comment by leighmcculloch** [comment]
The claimable balances are limited to 10 claimaints:
https://github.com/stellar/stellar-protocol/blob/725cb17e7493b841c8e886b5caf35bcb141e04e1/core/cap-0023.md#L131
These are the predicates defined in the CAP at the moment:
https://github.com/stellar/stellar-protocol/blob/725cb17e7493b841c8e886b5caf35bcb141e04e1/core/cap-0023.md#L79-L94

**Comment by stasbar** [comment]
Unfortunately, it doesn't solve the problem. In my case, the user doesn't have a stellar account. He just wants to redeem a voucher, without even knowing that he's using Stellar blockchain.

**Comment by stasbar** [comment]
Is there any chance of seeing this in the stellar protocol? This feature would allow anonymous transactions, which are not possible in any other way (because of the seq number synchronization).
