### ISSUE TITLE
Prospective SEP Discussion: Exchange API

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#633]
**Purpose**

This issue should facilitate discussion for a possible new SEP, which would describe a standardized way for wallets and anchors to allow users to purchase Stellar tokenized assets with a different off-chain asset.

For example, there has been prior discussion about how to support users who want to purchase XLM using their local fiat currency. See stellar/stellar-protocol#625. 

The goal would be to allow anchors to act similarly to exchanges, enabling users to purchase stellar assets with off-chain assets through the same anchor that supports deposits and withdraws of the user's local fiat currency.

**Discussion**

1. Is there sufficient ecosystem demand for the functionality described above?

2. How would this SEP work?

**Comment by JakeUrban** [comment]
@andywer @msfeldstein @tomerweller

**Comment by s-a-y** [comment]
This is something I'm looking at, but not sure what are the benefits of having a SEP, there is no really interaction between different parties, I was planning to do that just inside the interactive flow, user is making a deposit, but then have to choose the currency to pay with.

**Comment by tomerweller** [comment]
@marcinx yeah, if there's an on-chain market then this is irrelevant. However, this discussion is around off-chain liquidity. So for example, let's say you've got some XLM and are willing to sell them for Israeli Shekels (fiat). 

@s-a-y you're right. An interactive deposit/withdraw works, for the most part. The problem with this approach is that is that now you're dealing with two currencies so whenever you encounter an `amount` field you need to disambiguate. For example, in the `/info` and/or `/fee` endpoint. See Jake's changes here: https://github.com/stellar/stellar-protocol/pull/625. 

I'm afraid that going down this rabbit hole is going to create a full exchange API, and I'm not sure there's enough demand in the ecosystem.
