### ISSUE TITLE
Inconsistency in the outcome of the Horizon, Operations End-Point.

### ISSUE THREAD

**Issue by farzbood** [stellar/stellar-protocol#672]
Hi Everyone,
While I was exploring my pilot-app's transactions/operations, this comes across:
Account: "GA263PIIYTCWVD7TQX2TLC7KCHW6EOP5A57ZIOY4OR33GA2SJ2C4EETI" created by
Account: "GAEINH2YYS57QGSR2M4VGU6XSILY3NQLFKVIQN7AJN545HK2UC6NV4SP" as shown in this query:
https://horizon-testnet.stellar.org/accounts/GA263PIIYTCWVD7TQX2TLC7KCHW6EOP5A57ZIOY4OR33GA2SJ2C4EETI/operations

But the corresponding "create_account" Operation has no entries in "source_account" as shown in this query:
https://horizon-testnet.stellar.org/accounts/GAEINH2YYS57QGSR2M4VGU6XSILY3NQLFKVIQN7AJN545HK2UC6NV4SP/operations

Does it make sense?
Worth noting that my other Source-Accounts still hold these entries in their queries for Accounts created by them, only until "2020-07-01", but not for any newly created Accounts afterward. (Perhaps some updates in the Horizon/Core caused it in the meantime) this caused misbehavior in my app that depends on previously documented and working end-point outcome.
https://developers.stellar.org/api/resources/operations/list/

e.g. I used this Account for my test scenarios and it holds 7 out of 8 "create_account" Operations it made until the above mentioned date.
https://horizon-testnet.stellar.org/accounts/GDP4HJRNBGEX5QCMJ7L54HYCIBRXH6IR6VUZ5HWBOLUPMALRKV4N2HHY/operations

Regards

**Comment by bartekn** [comment]
It's [there](https://horizon-testnet.stellar.org/accounts/GAEINH2YYS57QGSR2M4VGU6XSILY3NQLFKVIQN7AJN545HK2UC6NV4SP/operations?cursor=4430306010468353) but on the next page of results (by default Horizon displays 10 results per page).

**Comment by farzbood** [comment]
Got it !
Thanks for your kind reply.
Sorry for bothering you.
Stay Safe V
