### ISSUE TITLE
SEP-31: questions about SEP-12

### ISSUE THREAD

**Issue by yuriescl** [stellar/stellar-protocol#676]
In [SEP-31](https://github.com/stellar/stellar-protocol/blob/a0e4114f973e21fa206f2dc4ddf2ef85ebbc25fd/ecosystem/sep-0031.md) there are mentions about SEP-12 and the KYC process of both senders and receivers (users).
Isn't SEP-12 used to store individual information about Stellar accounts? (first name, last name, bank account, etc)

Since SEP-31 is for Anchor-Anchor transactions, I don't see how SEP-12 can be used, since there's a single sender Stellar account, and a single receiver Stellar account in SEP-31.

_The sending anchor should, at minimum, collect the KYC information of the sending and receiving users specified by the receiving anchor's SEP-12 implementation._
Why is this necessary? Isn't the receiving Anchor responsible for their users KYC? Why does the sender have to worry about KYC of receiving users?

Maybe the SEP should be more specific if it's talking about the Anchor or it's customers when it says "user".

**Comment by msfeldstein** [comment]
The purpose of sep12 is to communicate customer information from the sending anchor to the receiving anchor.  We assumed that both anchors would want to at least know who both sides of the transaction are.

> Why is this necessary? Isn't the receiving Anchor responsible for their users KYC? Why does the sender have to worry about KYC of receiving users?
The receiving anchor is responsible to run any kyc checks on either of the end users that it cares to check out, but its up to the sender to provide the information.  The SEP31 flow assumes that the receiving client never needs to do anything.

These new updates don't change the base assumptions that all the customer information is provided by the sending client, to the sending anchor, and then communicated over a SEP to the receiving anchor (at least i don't see any difference but let me know if im misunderstanding part of it)

**Comment by msfeldstein** [comment]
SEP-12 is used to communicate customer information between anchors, it doesn't make any statements or assumptions about what checks or verifications get done with that information.

**Comment by yuriescl** [comment]
Isn't SEP-12 intended to store information about the owner of an individual Stellar account? My confusion is that SEP-31 has only two accounts and they're Anchor accounts, it wouldn't make sense to use SEP-12 for that.

**Comment by yuriescl** [comment]
Why not just pass all required fields in a single `/send` call?

**Comment by msfeldstein** [comment]
The reason we made this change was to allow customer information to be sent prior to any transaction being made.  Sometimes the KYC checks anchors want to run take a while, especially for b2b payments, and they want to be able to onboard users ahead of a transaction.

SEP-12 does key by a stellar account, but it allows for a memo which allows a custodial style approach to identifying users.  The stellar account used is the anchors, but the memo is what identifies the actual user.

**Comment by JakeUrban** [comment]
> Why not just pass all required fields in a single /send call?

@yuriescl some anchors want to KYC the sending and receiving users before starting a transaction.

For example, if a _receiving anchor_ takes 24 hours to approve a user's KYC info, a _sending anchor_ would want to register the sending and receiving users via SEP-12 before starting the SEP-31 transaction via a `/send` call.

Also, its more work for the sending anchor to send the KYC info on each `/send` call. Its easier for them to simply pass a `sender_id` and `receiver_id` when the receiving anchor already has the info.

**Comment by JakeUrban** [comment]
SEP-12 lets clients use a `memo` and `account`, so a SEP-31 sending anchor would use their own `account` but use a `memo` as their user ID.

**Comment by yuriescl** [comment]
> The reason we made this change was to allow customer information to be sent prior to any transaction being made. Sometimes the KYC checks anchors want to run take a while, especially for b2b payments, and they want to be able to onboard users ahead of a transaction.
This makes sense.

> SEP-12 lets clients use a memo and account, so a SEP-31 sending anchor would use their own account but use a memo as their user ID.
Oh, I see.
In SEP-12, why is there an account parameter if SEP10 already carries the pubkey?

Thanks for the clarification!
A suggestion is to add those insights/suggestions to the SEP docs.

**Comment by JakeUrban** [comment]
> In SEP-12, why is there an account parameter if SEP10 already carries the pubkey?

In the context of SEP-31, you're right the `account` parameter is unnecessary. But in the future it may be possible the account thats authenticated via SEP-10 is different from the `account` being passed via SEP-12. `M-addresses` may fit this case.

**Comment by yuriescl** [comment]
All my questions were answered and I don't have anything more to add, feel free to close this issue, thanks!
