### ISSUE TITLE
Feature Request: A way of providing/altering "home_domain" after limiting "Issuer - Master weight".

### ISSUE THREAD

**Issue by farzbood** [stellar/stellar-protocol#680]
### What problem does your feature solve?
Keeping the Anchor's "Issuer Account(s)" enable to change "home_domain" of their Asset(s) even after limitnig their "Master weight" (which is recommended by Stellar Documentation, to ensure "trustors" of their status consistency) to the minimum value only suite to validate "Low threshold" operations, perhaps (e.g. Allow Trust).

### What would you like to see?
I expect to have a way to be able to set/change my Anchor's "home_domain" option, with a "Low threshold" compliant signature weight, in case my domain altered in the future, which is likely to happen.

### What alternatives are there?
To my understanding, there's no one there since Set_Options is a "High threshold" Operation.

**Comment by tomerweller** [comment]
There are some security implications to lowering the threshold on setting the `home_domain`. Low threshold signers will usually be kept online ("hot wallets") so are expected to be somewhat less secure. If a malicious user redirects an asset's home domain to a malicious domain that can be catastrophic. One example is a malicious transfer server that redirects deposits/withdraws.    

@farzbood can you address security implications in your proposal?

**Comment by farzbood** [comment]
Well, I'm not an Sec. expert, so won't argue about those aspects of the Network. but from a software solution analysis P.O.V, the high-tide cohesion to an attribute like a **domain-address**, is not so encouraging to me.
### What comes to my understanding is:

- Status quo:

  All Signers of an Account are evaluate the same (except for their Weight).

- Proposing Specification:

 A Master-Key differentiated from other let say, Co-Signers to cover such situations where an Account-Holder needs to take actions according to its attributes that doesn't affect/decline Trustors rights, inappropriately. and keep it only for internal use by Anchor's Apps. (Don't handover the Master-Key to any 3rd party like "wallets")
What I mean is, the Holder of an Account needs a **"full-governance with all respect to it's trustors rights"** other than setting it up once and done.
So I believe one way to facilitate managing Accounts for Anchors/Holders is to configure Master-Keys in a way that keep their priviledges to some areas even in their low threshold weight status.
Stay Safe V
