### ISSUE TITLE
Feature Request: Separation of the Logic and Representation of (Buy)Offers of Assets.

### ISSUE THREAD

**Issue by farzbood** [stellar/stellar-protocol#695]
### What problem does your feature solve?
**Ambiguity** in `(Buy)Offers`: `price` and `amount` attributes represents as the **exploration result**.
whenever a `BuyOffer` issues, the above mentioned attribs are shown in the result_set of the queries, as we set in the time of issuing, but as it `crossed`**(partialy filled)** a counter-offer, those attributes are transformed as the Offer was originally a `SellOffer `with `price(n,d)` swapped and `amount` showed the `selling_asset` amount for the **residual of the original Offer**, which is a cause of the **Modeling all Offers as SellOffers in the Core-Logic** (As mentioned in the Docs. https://developers.stellar.org/docs/glossary/decentralized-exchange/) perhaps.

### What would you like to see?
1) When I'm attempting to **review my (Buy)Offers** status in the `OrderBook`, I expect to see my original attributes to be able to even recognize that's what I intended to do, and take any action required to handle my balances.(currently those (Buy)Offers are fetched as (Buy)Offers of the Asset, but with the price_r, price, and amount according to selling_asset in action) that is misleading to the viewer.

2) I'm not sure if it already covered(I didn't find a convenient way so far), but it worth to asking a way to have the **historical data of Offers** even after they filled and removed from `OrderBook`

### What alternatives are there?
I didn't find a way to re-create my (Buy)Offers as they were intended to be, after they crossed and prtialy-filled.
To my understandig, **separation** of the **Offer-Modeling at the Core-Level Business-Logic** and its **Reresentation at the User-Level** would helps a lot to handle the situation.

Stay Safe V

**Comment by MonsieurNicolas** [comment]
Was chatting today about what's next on "effects" with @bartekn ; being able to trace an offer all the way back to its creation would be nice

**Comment by ire-and-curses** [comment]
Testing removal of `stale` label.
