### ISSUE TITLE
Streamline native stellard currency format

### ISSUE THREAD

**Issue by irisli** [stellar/stellar-protocol#7]
Currency codes are currently formatted in the long formatted like explained in the Ripple wiki: https://wiki.ripple.com/Currency_format#National_currency_.28ISO_codes.29

## Streamline native currency format
They could be streamlined into 4 bytes of ascii. This is assuming that we don't add demurrage, which I believe it does not belong here and belongs in here: https://www.stellar.org/api/#api-accountset like how TransferRate is set. The only thing a currency format should store is the currency code itself.

If Stellar is to become a decentralized standardized network, we need to consider the design of small details such as this.

**Comment by jedmccaleb** [comment]
no longer applies
