### ISSUE TITLE
Account flag: memo required 

### ISSUE THREAD

**Issue by s-a-y** [stellar/stellar-protocol#71]
It's been discussed on Slack, but I want to put it forward.
Is it possible to bring back flag `memo_required` on account level?

It's not only for exchanges (although it will be a big win in the beginning), any merchant needs that in order to receive payments. I've been processing payments and people tend to forget to add memo, having flag will just prevent many mistakes. Yes, I can implement federation in a way:
`order123*piiko.co`, but many people send from exchanges, so they won't know what to do anyway.

There was just one comment from @jedmccaleb 

> jed [11:31 AM] 
> the ledger is precious. We should have done a better job getting exchanges to use federation  though

But flag on account level doesn't really take that much space.

@johansten, please 👍 this issue

**Comment by MonsieurNicolas** [comment]
I thought that this was already discussed and we didn't really know how to solve this just yet: the flag does not solve the underlying issue (what happens when people "guess"?). In fact even a regex would not even solve it: we still end up in situations where the payment is not valid for some reason.

A sensible way to address this probably involves a combination of:
1. business logic to ensure that there is a well defined simple way to "return" funds that cannot be processed (this must be implemented regardless), and include information in the return (memo)
2.  mechanisms to reduce the chance of a malformed memo
    * federation + toml -> recipes for memo depending on use case
    * submit the transactions to the merchant directly (that can perform any additional validation upfront before the tx makes it into the network)

In a way this seems very similar to what happens when sending emails: right now we don't have a well defined way to "bounce" emails at various stages.

**Comment by s-a-y** [comment]
ok, I haven't been part of that discussion, hence I had no idea about your decision. While this doesn't solve it completely, it could still reduce number of error by an order of magnitude.

1. Easy way to return would be good, but again the same problem when you need to refund user, who sent from an exchange. In this case you need some additional mechanism to be implemented on the exchange itself to send metadata with transaction. I'm very skeptical that's gonna happen after watching them not using federation for couple of years.
2. federation + toml already exist, yet we have all these issues

> submit the transactions to the merchant directly (that can perform any additional validation upfront before the tx makes it into the network)
That sounds interesting, but isn't going to help with exchanges again. Perhaps rejecting incoming transactions by an account on protocol level could help, but that's quite a big change to the protocol.
Do exchanges have their own nodes or they simply use your public horizon instance?

**Comment by johansten** [comment]
With stellard tx's failed if an account required a destination tag.

I don't see why the same thing can't be done now? It's just one bit in a (largely unpopulated) 32bit bitfield, so space isn't an issue.

Of course, getting exchanges to actually flag themselves as needing a memo -- good luck with that.

**Comment by s-a-y** [comment]
> Of course, getting exchanges to actually flag themselves as needing a memo -- good luck with that. 
Yeah, but I consider that as a maximum we can expect from their side. Pretty good deal, spend 1 min, get number of support queries reduced 10x

**Comment by seancil** [comment]
Sending services are also getting support requests when funds are sent from their service -> another service requiring memos. This is something we're going to need in some form, and @s-a-y is right that it should be possible to convince the exchange when they're getting hit with so many requests about memos....

**Comment by theaeolianmachine** [comment]
Closing this in favor of [CAP-0018](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0018.md); feel free to ping on the thread if you don't think this enables the goals present here off-chain.

**Comment by tomerweller** [comment]
Reopening this as CAP-0018 only solves this problem for regulated assets and issuer approval. The bigger problem is still there. 
 
Copying my notes from #341:
> I agree that this is a problem and getting exchanges to use federated addresses is an uphill battle, which we're losing. While such a flag might solve most of the issues, it still doesn't address issues caused by people typing in the wrong memo, or putting in the wrong type. I'd rather see a general purpose "sign to receive" feature which can allow services to actually verify that the memo makes sense before accepting it.

**Comment by aghamir** [comment]
Is there any progress on this issue? To be honest, force to use federation address cannot solve the problem because many exchanges don't support federation address as a withdraw address. I think implementing the memo_required_flag is the best practice to reduce this issue for exchanges same as XRP and BNB.

**Comment by rice2000** [comment]
> Is there any progress on this issue? To be honest, forcing to use federation address cannot solve the problem because many exchanges don't support federation address as a withdraw address. I think implementing the memo_required_flag is the best practice to reduce this issue for exchanges same as XRP and BNB.

Yes!  This has been addressed at the ecosystem level by SEP-29, which specifies how to set a `memo-required` flag on an account:
https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0029.md

It's also been addressed at the protocol level by CAP-27, which introduces first-class multiplexed accounts (though there's still work to be done to figure out how to best expose the feature in Horizon + SDKs):
https://github.com/stellar/stellar-protocol/blob/master/core/cap-0027.md

**Comment by ire-and-curses** [comment]
Also worth noting that most SDKs are enforcing SEP 29, e.g. here it is in the Go SDK: https://godoc.org/github.com/stellar/go/clients/horizonclient#Client.SubmitTransaction
