### ISSUE TITLE
Add stop-limit orders

### ISSUE THREAD

**Issue by ramontayag** [stellar/stellar-protocol#72]
[Stop-limit orders](https://www.capitaloneinvesting.com/main/help/topic.aspx?CategoryCode=CRTTORDTYP) would be a good feature to have.

I have thought about ways of doing it outside Stellar core (signed tx of order submitted to app, app watches the orderbook at broadcasts it when price reaches specified amount), but I don't know if this is something that's generic enough and should be in Stellar core.

**Comment by MonsieurNicolas** [comment]
In general, if it can be implemented outside of core, it's better to live it there.

What I would suggest is to build this type of functionality outside of the core protocol, and as you try to add more types of trading, we may find that some new operation or functionality at the protocol level could unblock things or make things a lot more efficient.

**Comment by ramontayag** [comment]
Ok, I have an idea on how to implement this thanks to talking with someone knowledgeable with the Stellar ecosystem. Basically, the stop-limit order will be given to a server which will watch the order book, and broadcast it when the price hits that range.

**Comment by jedmccaleb** [comment]
Yep could be turned into an SEP if someone wanted to . Closing for now
