### ISSUE TITLE
Feature Request: Improve "passive order" rule

### ISSUE THREAD

**Issue by phil-stellar** [stellar/stellar-protocol#723]
### What problem does your feature solve?
It improves the "passive order" rule for order/execution management on the SDEX.

### What would you like to see?
Retool the "passive order" to act more like a "maker only" ("post only") order. The current "passive order" allows for locked markets (but still executes for crossed markets), which in my opinion has very little utility. Changing this to "maker only" order prevents both locked and crossed markets (which is a good safety measure) by preventing an order from initiating a transaction against another order. Instead, it places the order as a limit order at the best available marketable price without initiating a trade. It is a liquidity enhancing order and will only execute if a "taker" order trades against it.  

The description would read something like this: "A passive order is a limit order that does not immediately execute against a marketable counter order on the orderbook. It adds liquidity as a limit order at the best marketable price and will only be filled if another non-passive order trades against it. For example, if there is an ask to sell 1 XLM at $0.10, and you create a passive buy order to buy to buy 1 XLM for $0.10 (or above), your passive buy order does not take that existing $0.10 ask. Instead, it will place your bid at the highest possible price up to your limit price without executing the order, in this case ($0.09999999). It is a passive order because it will never initiate an order execution. 

### What alternatives are there?
See answer above.

**Comment by MonsieurNicolas** [comment]
@sisuresh @jonjove FYI
