### ISSUE TITLE
SEP-0024 fee types

### ISSUE THREAD

**Issue by LeviticusMB** [stellar/stellar-protocol#733]
Updated: 2019-09-18
Version 1.0.0

Since the `fields` structure was removed from this SEP, there is no longer possible for the server to specify what kind of deposits are available. That means that the client has no way to know what to supply in the `type` QP.

Complex fees most certainly depends on what deposit method will be used, in addition to the amount Doesn't that make the whole `/fee` endpoint kind of useless?

**Comment by JakeUrban** [comment]
Not stale, just a part of a problem spanning multiple SEPs and scenarios. A comprehensive solution needs to be developed and we haven't had time to give it the thought it deserves.

**Comment by JakeUrban** [comment]
Hi @LeviticusMB, I just noticed that there is another issue on the same subject so I'm going to close this issue. Discussion about adding `type` values to the SEP-24 `/info` endpoint can continue on #614
