### ISSUE TITLE
Feature Request: flexible asset min and max amounts

### ISSUE THREAD

**Issue by yuriescl** [stellar/stellar-protocol#743]
Some Anchors might want to have different minimum and maximum deposit/withdrawal amounts for their assets, depending on the type of deposit/withdrawal.
For example, SEPA transfers might have a different deposit_min_amount than Cash deposits.

See https://github.com/stellar/django-polaris/issues/322

**Comment by JakeUrban** [comment]
This is related to #716 , which is focused on having different fees per type. These two issues will likely be solved at the same time.

**Comment by JakeUrban** [comment]
Not stale, its just a part of a larger discussion that we haven't had time think about adequately
