### ISSUE TITLE
meta: change template to make it easier to understand what a CAP does

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/stellar-protocol#748]
Here are some ideas from @ire-and-curses to get started:

 *  Motivation in CAPs is currently very minimal. It would be great to describe explicit use cases (aka worked examples). They are motivational and also aid understanding and help identify inadequacies in the proposal.
 * An FAQ for the CAP is a huge help to understanding. Particularly around explanations of specific behaviour (e.g. "Why does this always succeed? What triggers this error code? What happens in the case of the native asset?" etc). This can be another WG output, but any interesting design choices in the CAP should be highlighted (like a comment in tricky source code).
 * A top-level summary like "this CAP adds 2 new operations and changes the semantics of existing operation X. This is a breaking change.".

**Comment by ire-and-curses** [comment]
Is this something to discuss in next protocol meeting?

**Comment by MonsieurNicolas** [comment]
couple things:
* I would like to get specific feedback (positive and negative) on the existing CAP process and template before making even more changes. 
* the protocol meeting is to discuss the adoption of a proposal, and this is issue seems to be in a state closer to "needs more discussion" and is not even close to a concrete proposal

**Comment by leighmcculloch** [comment]
The ideas in the PR description sound well formed and could be presented individually as meta PRs that then get discussed on the mailing list. I don't think this needs realtime discussion at this point.
