### ISSUE TITLE
SEP31: guide sender/receiver implementations

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-protocol#749]
SEP31 defines an interoperability standard between sending anchors and receiving anchors. The receiver needs to implement a set of endpoints (=server) and the sender consumes these endpoint (=client). 

Should we try to refactor the SEP in a way that helps senders and receivers understand what they need to implement? For example, SEP24 has a [Basic Wallet Implementation](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#basic-wallet-implementation) and a [Basic Anchor Implementation](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#basic-wallet-implementation) sections to help navigate the respective parties. We can either do something similar (add basic implementation strategies) or divide the entire document into two main sections (Sender Implementation, Receiver Implementation).

Would love to know what others think. 

(This issue is semantical - it doesn't mandate any protocol change)

**Comment by JakeUrban** [comment]
I'm all for making SEPs more readable and focused on use case, and SEP-31 definitely focuses more on the receiver, leaving the client to infer whats required of them.
