### ISSUE TITLE
SEP24: deposit trustline improvements / clarifications

### ISSUE THREAD

**Issue by tomerweller** [stellar/stellar-protocol#756]
- If account doesn't exist the anchor should create it with sufficient XLM to cover the base reserve of trustline
- if account exists but doesn't have sufficient XLM to cover the base reserve of the trustline, the anchor should make a payment to cover that 
- encourage anchors to notify the user (email/text/etc) when their accounts are in a pending trust status
- ensure the `/transaction` endpoint doesn't require a JWT token. this will allow wallets to check status in the background without worrying about refreshing jwt tokens.

**Comment by JakeUrban** [comment]
@tomerweller SEP-24 already includes the first two points you mentioned in the [Special Cases](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#special-cases) section.

We don't do the third point, we can add that.

Regarding the last point about exposing `/transaction` without a JWT, the `on_change_callback` parameter was added for exactly this purpose: getting updates on the status of the transaction. We're doubling down on this approach with a [SEP-12 PR](https://github.com/stellar/stellar-protocol/pull/805) as well.

**Comment by JakeUrban** [comment]
closing this -- please reopen if you believe issues mentioned have not been resolved
