### ISSUE TITLE
SEP-24: improve special cases handling

### ISSUE THREAD

**Issue by howardtw** [stellar/stellar-protocol#771]
**Why**

In the [section](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#special-cases) of handling special cases, what we recommend for the two cases are inconsistent. In [stellar account does not exist](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#stellar-account-does-not-exist), we recommend anchors to convert part of the deposit into XLM while in [stellar account does not trust asset](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#stellar-account-doesnt-trust-asset), we recommend anchors to `send the needed amount of XLM to the Account for creating a trust line` without saying whether the needed amount should be taken from the deposit.

Regarding the section for `stellar account does not exist`:
1. We don't really know why 2.01 XLM was previously recommended.
2. The reserve should be in addition to the deposit amount. However, our current recommendation suggests that anchors should convert part of the deposit into XLM, but we don't have a guideline for anchors to communicate the fact that some of the deposit will be used as the account reserve.
3. If we end up having anchors send extra XLM to users' accounts as the account reserve and transaction fee, the same should be done in other cases where a user already has an account with or without a trustline.

Given that our goal is not to have users think about XLM reserves at all, we have rooms to improve for the above points. Finally, it would be great to learn which anchors have implemented the account creation flow or the trustline-reserve-sponsor flow so that we can know how they are doing it.

**Comment by JakeUrban** [comment]
Hi @howardtw I'm starting to work on this now. I'm not sure which anchors sponsor account creation, but Polaris [creates the account](https://github.com/stellar/django-polaris/blob/master/polaris/polaris/management/commands/poll_pending_deposits.py#L135-L167) with a 2.01XLM balance funded by the anchor's distribution account (AKA not part of the deposit amount).

Let me respond to each of your points:
1. I'll do some poking around to figure out if any knows why this is the case. I'm inclined to keep it as-is if we cannot find a good reason to change it though.
2. The reserve should be in addition to the deposit amount, I agree. I'll update the SEP for this.
3. I don't agree that the anchor should give accounts with trustlines 2.01XLM. Anchors will not do it if they don't need to. If the account exists and the trustline doesn't, the anchor should ensure the account has at least 2.01XLM before changing the transaction status to `pending_trust`.

**Comment by howardtw** [comment]
> I'll do some poking around to figure out if any knows why this is the case. I'm inclined to keep it as-is if we cannot find a good reason to change it though.

Sounds good. Makes sense to keep it as it is if there's no obvious reason to change it.

> I don't agree that the anchor should give accounts with trustlines 2.01XLM.

Totally. In this case, accounts equipped with the trustline to the receiving asset should be able to receive the payment without additional funding.

> If the account exists and the trustline doesn't, the anchor should ensure the account has at least 2.01XLM before changing the transaction status to pending_trust.

By saying ensuring, do you mean the anchor should just wait or the anchor should sponsor? My point is that if we ask anchors to cover the reserves (account & trustline) when the account doesn't exist, shouldn't we also ask anchors to cover the reserve (trustline) when the account exists but does not have the trustline?
