### ISSUE TITLE
Minor Operation Validation Improvements

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-protocol#776]
Upon reviewing certain aspects of the protocol, I noticed that

1. It is valid to submit change trust for an asset issued by the source account (but we fail during apply)
2. It is valid to submit allow trust with trustor as the source account (but we fail during apply)

Both of these meet our typical guidelines for being validation checks rather than application checks.

**Comment by MonsieurNicolas** [comment]
Protocol 16 candidate? @jonjove

**Comment by jonjove** [comment]
Definitely. Let's make sure this gets fixed @sisuresh. @MonsieurNicolas do you want a CAP for this? It seems so minor that it might not be necessary. Maybe @leighmcculloch or @tomerweller have opinions about this.

**Comment by leighmcculloch** [comment]
I think this is very low priority. I don't know of any meaningful problems this has caused.

**Comment by jonjove** [comment]
I meant opinions about the need for a CAP. The fix is trivial, we just missed the deadline for it in protocol 15. We try to do some bug-fixes in every release to make the protocol easier to reason about.

**Comment by tomerweller** [comment]
Yes on the change. No on the CAP. I can't imagine a scenario in which people are relying on when exactly these edge cases fail.

**Comment by jonjove** [comment]
Resolved by https://github.com/stellar/stellar-core/pull/2903
