### ISSUE TITLE
Feature Request: More than one SEP12 type support in SEP31 info endpoint

### ISSUE THREAD

**Issue by gaclaudiu** [stellar/stellar-protocol#802]
### What problem does your feature solve?
More SEP12 types  to cover the use case when a sender or receiver is a : 
* counter party 
* individual (person) client 
* entity (organization) client

### What would you like to see?
I would like to see SEP31 info point configuration per SEP12 type , or if a config can be reused then the sender_sep12_type or receiver_sep12_type to allow an array. 

For our use case the array implementation should be enough.
Configuration example : 
`{
   "receive":{
      "USD":{
         "enabled":true,
         "fee_fixed":5,
         "fee_percent":1,
         "min_amount":0.1,
         "max_amount":1000,
         "sender_sep12_type": "sep31-senderIndividualClient, sep-31EntityClient",
         "receiver_sep12_type": "sep31-receiverIndividualClient, sep-31EntityClient, sep-31CounterPaty",
         "fields":{
            "transaction":{
               "receiver_routing_number":{
                  "description": "routing number of the destination bank account"
               },
               "receiver_account_number":{
                  "description": "bank account number of the destination"
               },
               "type":{
                  "description": "type of deposit to make",
                  "choices":[
                     "SEPA",
                     "SWIFT"
                  ]
               }
            }
         }
      }
   }
}`

**Comment by JakeUrban** [comment]
Hi @gaclaudiu, I agree we need to be able to specify multiple values for both sender & receiver:
```
{
   "receive":{
      "USD":{
         ...
         "sender_sep12_type": ["sep31-senderIndividualClient, sep-31EntityClient"],
         "receiver_sep12_type": ["sep31-receiverIndividualClient, sep-31EntityClient, sep-31CounterPaty"],
         ...
      }
   }
}
```

Regarding "SEP31 info point configuration per SEP12 type", its a bit more complicated. Some anchors would like to have different info configurations per transaction type (SEPA, SWIFT, etc.) or per-country of operation, see #731, #716, #743. So more discussion on this is needed.

Can you give more info on what fields would need to be different per SEP-12 type?

**Comment by gaclaudiu** [comment]
Hi @JakeUrban , 
"SEP31 info point configuration per SEP12 type"  : 
Use case example : 
You can pass for receiver a client (person or organization ) or a counter party. 

For a client we need only his finClusive account ID to put the money in . 

For a counter party we need it's full bank details to do an ACH to it account . 

Maybe info is not the right place, but I am thinking that this should be somehow reflected in the SEP31 . 

What do you think ?
