### ISSUE TITLE
CAP-36: incomplete sentence

### ISSUE THREAD

**Issue by howardtw** [stellar/stellar-protocol#807]
**What**

We have an incomplete sentence [here](https://github.com/stellar/stellar-protocol/blob/a60d936/core/cap-0036.md#semantics):
```
The amount of the asset clawed back is burned and is not sent to any other address since the return of an asset to the .
```

**Comment by leighmcculloch** [comment]
Thanks for picking up on this. I expect CAP-36 will be rejected on the basis that CAP-35 now contains clawback of claimable balances. I'm going to close this because it's not worth going back and fixing up the CAP, but I can revive this if something happens CAP-36 comes back to life.
