### ISSUE TITLE
Update CAP-0029 Proposal Using Current Template

### ISSUE THREAD

**Issue by jonjove** [stellar/stellar-protocol#843]

**Comment by jonjove** [comment]
@sisuresh is this totally done?

**Comment by sisuresh** [comment]
Yeah this was the PR - https://github.com/stellar/stellar-protocol/pull/865.

**Comment by jonjove** [comment]
Lines 38-39 in the proposal seems like they're missing some important details. Line 38: what about `AUTHORIZED_TO_MAINTAIN_LIABILITIES_FLAG`? Line 39: this should be restricted to revocation, right?

There also seem to be some missing sections from the template: 
- I see that you didn't add any design rationale (perhaps you felt there was nothing to explain?)
- The security concerns section is also missing (the template explicitly says, "If a change does not have security implications, briefly explain why")

I'm not pointing this out just to be annoying. I don't think compliance with the template has to be complete. For example, the specification is divided into "XDR changes" and "Semantics" but obviously there are no XDR changes here so I don't see any reason to enforce that division. But I tend to think that the design rationale is the most important section in the document.

You could, for instance, explore why we should bother fixing allow trust (and thereby introducing backwards incompatibilities) in the context of the new `SetTrustLineFlagsOp` from CAP-0035? That would be perfect for the design rationale--and who knows, maybe the answer is we should only fix this for `SetTrustLineFlagsOp`. (@tomerweller might have some thoughts on this last question, even though its just an example).

**Comment by sisuresh** [comment]
I opened a PR (#871) addressing the missing details. I initially didn't include the design rationale since the motivation section was clear, and the actual design change is very simple. The point you brought up about `SetTrustLineFlagsOp` is a good one though, so I added that to the design rationale section.
