### ISSUE TITLE
Feature request, add limit to AllowTrust operation

### ISSUE THREAD

**Issue by bonen** [stellar/stellar-protocol#85]
The current protocol allows an asset holder to set a trustline limit. However it would be very valuable if also the Anchors can set a limit when they approve an acount (AllowTrust).
The Anchors we are working with (financial institutions) need to enforce a limit per asset holder they whitelisted (approved) for KYC reasons (different tier levels matching different limits).

**Comment by MonsieurNicolas** [comment]
Are those different tiers also requiring additional controls?

From what I understand of some of those other requirements, there are:
* trade limits - per trade amount but also and aggregate per some time window like day/month.
* rules based on the direction of the trade.

**Comment by bonen** [comment]
Yes these controls would definitely be even more valuable. Not sure though what you mean with rules based on the direction of the trade.
For our use case (the asset is qualified as a financial instrument/effect) the 'ideal' controls, that would massively help  in convincing EU regulators to accept the solution, would be:

For each asset:
1. Specify maximum amount that can be owned
2. Specify the trade limits per time window e.g. month
3. Specify which assets can be traded against, e.g. to only allow trading against EURT or other tokens that are issued by a financial institution that ensures KYC processes apply

**Comment by jedmccaleb** [comment]
At least for 1. if you are authorizing the account to hold your asset, you can do that only if they have trusted you for the correct amount.

**Comment by johansten** [comment]
I've been looking at this recently too.

@jedmccaleb, as @bonen says, there's nothing preventing an account from raising its limit after the trustline has been authorized.

I think it would be useful to change the semantics of `allow trust`, so that it authorizes the *limit* too.
I.e., if you try to increase the limit, you get deauthorized automatically.

I'm looking at ICOs mainly, where you sometimes want to limit how many tokens a user is able to buy during the token sale.

**Comment by theaeolianmachine** [comment]
Closing this out in favor of the implementation in [CAP-0018](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0018.md). If anyone feels this doesn't adequately address the concerns of this discussion, feel free to ping on the thread, or better yet open up discussion on the mailing list.
