### ISSUE TITLE
Impossible to keep track of the XLM balance of account using effects/operations/transactions

### ISSUE THREAD

**Issue by salessandri** [stellar/stellar-protocol#86]
## Problem Description

> It is impossible to keep track of the XLM balance of an account using its effects/operations/transactions.

In the presence of failed transactions, the TX fee is deducted from the source account but the TX is not recorded anywhere (or at least is not retrievable through Horizon).

This has the effect of modifying the account's balance. But the source of that effect cannot be tracked.

I came across this issue when trying to keep track the account balance only by subscribing to the account's TX feed.
If a TX from the account being tracked failed, I would get an inconsistency between the balance retrieved used the account endpoint and the one that was calculating using the TX feed.

_Note: The same applies with TX sequence numbers a number is "skipped"_

## Relevance

I think this is a relevant issue because it boils down to accountability and audit.

There is no way to determine why 100 stroops dissappeared from the account balance. 

## Basic Example

The account `GBPMLK3JT5WLEJSZ3PMO3HKHONEAVMJPGVCIELVIOYKRRYBAG5IS6QA7` on the testnet is an example of this.

This account was created using the friend bot, thus got a funding of `XLM 10,000`.
This was done in TX: `a7a7b2e74d949644d286b43078f62671754cca66aa935b609476fa9b1740328d`.

Then a TX was created to transfer `XLM 50,000` to another account. This TX was signed and submitted, its hash: `81291e92d924e2dfb8117fccaa58dcb0dd0daecfa658cfb7a8931e94ee628b3f`.
The TX failed as expected.

Now the account balance shows: `XLM 9,999.9999900`. The TX fee was deducted.

But when querying the TX for the account, the only TX listed is the one where the account creation happened.
No effects or operations apart from the account creation ones are listed.

**Comment by MonsieurNicolas** [comment]
All side effects are recorded in the `txfee` and `txhistory` core tables but yes, Horizon doesn't import those for some reason. I found this annoying for myself as it makes it hard to know if transactions should be resubmitted or not and while debugging

**Comment by MikeFair** [comment]
Even if failed transactions weren't tracked, perhaps the account effects could be linked to the ledger close itself.  (A ledger close event collects all the fees from the accounts.)

I know a number of folks have been wanting the ability to collect fees from transactions involving their own custom assets as well.  Perhaps a "fees" transaction as part of the ledger close can be used to process fees in all kinds of assets, not just XLM.  (Like states collecting Sales Tax perhaps?)

**Comment by salessandri** [comment]
This seems to be a Horizon problem, we should continue the discussion there. Closing this issue.
