### ISSUE TITLE
SEP-24: Add no-information-needed response to deposit or remove it from withdraw

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#864]
SEP-24 offers a no additional information needed response for `POST /transactions/withdraw/interactive`, but does not offer a similar endpoint for `POST /transactions/deposit/interactive`.

It is not clear why this is the case. Anchors could conceivably not need any additional information for a deposit in the same way it is possible for withdraw, that is: the user has been KYC previously in connection with the same Stellar account being used in the current transaction request.

So, we have two choices:

1. Adding a deposit no-additional-info-needed response. The response body would probably look something like this:
```json
{
    "id": "a8e11fcb-9ae5-410a-86d6-a6a0bf1fe40f",
    "how": "a human-readable message outlining how the user should send funds to the anchor's off-chain account. This is how SEP-6 does it",
    "fee_fixed": "optional number as a string",
    "fee_percent": "optional number between 0 and 100 as a string",
    "max_amount": "optional number as a string",
    "min_amount": "optional number as a string"
}
```

2. Removing the withdraw no-additional-info-needed response. This would technically be a breaking change, although it is possible this response is not used by any anchor. Polaris doesn't support it. And it is very possible that wallet applications don't either. If we go this route, anchors would always return an interactive info need response, but the `url` would just be a confirmation/informational page when no additional information is required.

**Comment by JakeUrban** [comment]
@leighmcculloch @tomerweller I'm curious what your thoughts are on this

**Comment by leighmcculloch** [comment]
If we can get some confidence on no support in practice, I'd mark it as deprecated. I'd also be okay with removing if our confidence is high.
