### ISSUE TITLE
Add a built-in and automatic “Trust Limit” control for issuers

### ISSUE THREAD

**Issue by KuknosCoreTeam** [stellar/stellar-protocol#877]
As said in issue #85, some financial institutions need to set the maximum amount of asset that can be owned by a holder. Although asset issuers can enforce this kind of limitation by manually checking “Trust Limit” value requested in the “Change Trust” operation (using authorization and “Allow Trust” operation);  We propose using an automated and built-in solution, which could help issuers to preventively control maximum asset balance for each account. This would provide a simple use and built-in “Trust Limit” control mechanism.
The steps of this mechanism are as following:

- The issuer should set a “Data Entry”, that points to the corresponding asset and represents the maximum amount of the asset that can be owned by an account.

  - We name this “Data Entry” as “Asset Limit”.
  
           
  - “Asset    Limit” key name, should be defined by convention. We propose using ASSETCODE + “_limit”.
  - “Asset Limit” value is the maximum number of the asset that can be owned by the holder.
       
- “Change Trust” operation should check the existence of “Asset Limit” in the issuer account.
     
- If  “Asset Limit” exists, the operation would make sure the “Trust Limit” requested by the user is less than or equal to “Asset Limit”. Otherwise, the operation is rejected.

Code:
```c++
// This function is called at the end of doApply() function. And checks the asset limit validation.
bool ChangeTrustOpFrame::doCheckAssetLimit(AbstractLedgerTxn& ltx, AccountID const& issuerID){
     std::string assetCode = "";
     if (mChangeTrust.line.type() == ASSET_TYPE_CREDIT_ALPHANUM4){
          assetCodeToStr(mChangeTrust.line.alphaNum4().assetCode, assetCode);
     }else if (mChangeTrust.line.type() == ASSET_TYPE_CREDIT_ALPHANUM12){
          assetCodeToStr(mChangeTrust.line.alphaNum12().assetCode, assetCode);
     }
     auto const& assetLimitKey = assetCode + "_limit";
     LedgerTxnEntry const& limitEntry =
     stellar::loadData(ltx, issuerID, assetLimitKey);
     if (limitEntry){
          std::string limitValueStr = "";
          auto const& limitValue = limitEntry.current().data.data().dataValue;
          for (int i = 0; i < limitValue.size(); i++){
               limitValueStr += (char(limitValue[i]));
          }
          CLOG(ERROR, "Tx") << "check limit: " <<  assetLimitKey << ", value: " << limitValueStr << ". Requested: " << mChangeTrust.limit;
          unsigned long long assetLimit = 0;
          try{
               assetLimit = std::stoull(limitValueStr);
          }catch (std::exception& cerr){
               CLOG(ERROR, "Tx") << "check limit: " << cerr.what();
          }
          if (assetLimit > 0 && assetLimit < mChangeTrust.limit){
               return false;
          }
     }
     return true;
}
```

**Comment by tlack29** [comment]
can i get my assets

**Comment by tlack29** [comment]
How i do that
