### ISSUE TITLE
API to get the count of failed login attempts for a stellar account ID

### ISSUE THREAD

**Issue by vassrini** [stellar/stellar-protocol#9]
Need an API to get the count of login attempts failure for a stellar account ID. This API should retrive the data collected by the function loginFailureTracker.record(req.ip).
This will be a good alternative similar to the feature offered by web based email providers who notify us when there are failed login attempts. This is a must have feature until 2FA is implemented.

function actuallyLogin() {      
        wallet.get(id).then(function(wallet) {
        if(typeof wallet === "undefined") {
          //TODO: confirm this works well behind cloudflare
          loginFailureTracker.record(req.ip);
          fail();
        } else {
          res.send({
            "status" : "success",
            "data"   : _.omit(wallet, ['recoveryId', 'recoveryData'])
          });
        }
      });
    }

**Comment by jedmccaleb** [comment]
yes not a protocol issue
