### ISSUE TITLE
Maturing Keys

### ISSUE THREAD

**Issue by JeremyRubin** [stellar/stellar-protocol#90]
Background
---

A time-programmed freeze is useful for many different kinds of contract in Stellar. It's possible to do certain kinds of freezes currently, but the more useful kind (relative time freezes) does not seem to be possible.

The State-Channels on Stellar protocol would benefit from relative timeouts because it would remove the requirement to do a periodic channel update.

Other contracts that could benefit include inheritance schemes.

This document is an informal proposal to generate discussion on this new feature, and proposes two potential features: maturing-keys, and direct account freezes. I haven't fully specified them as I wanted to seek feedback first.

Current Freeze Semantics
---
Currently, it is possible to do as follows within a transaction T

- Remove all Signers (or set thresholds too high)
- Add a preauth to add back all signers after some MinTime m

This enables one to put a temporary 'freeze' on an account.

However, if one wants to ensure that MinTime is some amount of time d after T, it is not easily achievable to do so. One could in theory sign a bunch of copies of T with different mintime/maxtimes on T that set a different MinTime on the preauth. But it would be difficult to broadcast these transactions because they have tight time constraints on when they may be broadcast and require knowledge of the duration within which an operation may occur.

Maturing Keys
----

A maturing-key specifies a relative time and a signer. When the maturing-key is added, the relative-time field is computed to be an absolute time based on the ledger's time. After the absolute-time is passed, the key may be used to sign.

Extensions to Maturing Keys
-----
It might be useful to also allow: absolute-time maturing keys, fully lifespanned-keys (upper and lower time bound).

Direct Account Freeze
----
The maturing-key paradigm is a minimal solution which will work for specific protocols such as state channels. However, it adds a bit of complexity on the programmer side as they would need to know all the signers to be able to remove them to enforce the freeze. This complexity can be used to do novel smart contracts that are yet to be designed.

However, a much simpler alternative feature would be to just have an Operation which Freezes it's source account until a relative time (or absolute time) d. An account which is frozen is not permitted to perform any transactions until the freeze expires. It's critical that this is done as an operation with an arbitrary target as there may be a need (as with state channels) to use other sources for the transaction.

Types of Direct Account Freeze
-----

There should be three (or more?) types of freeze in this model. A transaction freeze, a sequence freeze, and an operation freeze. Under a transaction freeze, the account may not directly perform any transaction. However, operations sourced from the the account may still be run if another account is the source. This is the variant required for relative timeout state channels. The stricter form, a sequence freeze, prevents the sequence number from changing for a certain duration. The sequence freeze still allows funds to be sent in other operations, but does not permit a sequence bump operation. The strictest form, a total operation freeze, would prevent the account from authorizing any transactions whatsoever. 

More exotic freeze types could include: thawable freezes (i.e., one specific key may thaw the account earlier), partial freezes (i.e., frozen except for some set of preauthorized transactions).  

Remarks
----

Generally, I believe that maturing keys are the simpler primitive to introduce, but perhaps there are motivations for introducing both variants, semi-redundantly.

**Comment by robdenison** [comment]
Could this be done more simply by dropping the key part and just having a `relativeMintime` signer that specifies a relative time? If you want to assign a key as well, that could just be another signer on the account, with the threshold set to 2. In addition to being simpler, this would also give you the flexibility of using a preauthorized transaction (or any other useful signer type that is added in the future) as the cosigner, instead of a key.

We might as well also add `relativeMaxTime`, `minTime`, and `maxTime` signers at the same time. (Eventually, if we add something like #89, the `minTime` and `maxTime` fields in the transaction header could be entirely deprecated in favor of those being assertions in the transaction.)

**Comment by JeremyRubin** [comment]
I don't believe so. Just using thresholds ends up being very complicated, and falls apart in the case where the sum of activated relative time signers is greater than a threshold.

For example, if we are doing competing version claims in state channels:
After Alice claims that the version is 1, then there should be 1 D time till Snapshot 1 is usable.
After Bob counter claims version 2, there should be D time till Snapshot 2 is usable (and T1 is excluded by sequence #).
But if you literally add to the channel account in Alice's version 1 claim a signer that matures D time later, you then need to somehow remove it with Bob's counter claim.

It's much simpler if Alice's claim of version 1 bumps R's sequence, adds a preauth (at that specific sequence number) that is usable after D time. (If you don't like preauth, a signer that is usable that just so happens to have pre-signed the snapshot -- there are multiple ways to handle snapshots auth, e.g. 1 tx that adds a bunch of preauth, chain of preauth, etc, so it's a bit immaterial to this discussion other than to argue that it is preferable)

**Comment by jedmccaleb** [comment]
I think in practice you will want to change the weights on the account when the signers change.

Also can't this be achieved if we allow any seqNum in preauth txs as in #88 we would just add a preauth tx with timebounds that adds or removes another signer.

**Comment by JeremyRubin** [comment]
@jedmccaleb, no, we need some notion of relative time which doesn't currently exist. There might be multiple ways of orchestrating (e.g., just changing weights) but there needs to be a relative time feature.

**Comment by theaeolianmachine** [comment]
@JeremyRubin do you want to write up a CAP, or would like someone else to take it over?

**Comment by JeremyRubin** [comment]
Superseded by https://github.com/stellar/stellar-protocol/blob/master/core/cap-0011.md
