### ISSUE TITLE
SEP-1: Add ORG_SUPPORT_EMAIL to TOML file

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#903]
`ORG_OFFICIAL_EMAIL` is usually not a support email, so wallets usually asks the anchor directly for a support email and stores it on their service's backend. This is not idea because the anchor has to reach out to the wallet to change it, and some wallet services are frontend-only.

This is why an additional email field, `ORG_SUPPORT_EMAIL` would be helpful for anchors and clients.

**Comment by leighmcculloch** [comment]
Makes sense to me. This begs the question, what is the official email for or what do we hope it will be used for?

**Comment by JakeUrban** [comment]
An email for business inquiries makes the most sense to me, as does the partner who requested this change.
