### ISSUE TITLE
SEP-0009: Add sex field

### ISSUE THREAD

**Issue by ymatienzo** [stellar/stellar-protocol#915]
### What problem does your feature solve?

Sometimes anchors need to collect user gender information as part of their KYC requirements. 

### What would you like to see?

1. Add gender as an additional field for the individual
2. Gender could have the following values [male, female, undefined]

**Comment by leighmcculloch** [comment]
Thanks for opening this issue @ymatienzo. Could you provide some examples of the jurisdiction (e.g. country) where gender is required for KYC and how it influences KYC?

A quick internet search turned up this [this document](https://www.pwc.com/gx/en/financial-services/publications/assets/pwc-anti-money-laundering-2016.pdf) dated 2016 that indicates it is a KYC requirement in these countries:
- South Korea
- Mexico
- Isle of Man
- Russia
- Israel

I'm wondering whether for KYC the importance in these countries is biological or behavioral/cultural, and if the former, if it would be more appropriate to use the term `sex`. A reference for more details on `sex` vs `gender` is [here](https://www.merriam-webster.com/dictionary/gender#usage-1). Passports and other identity documentation use the term `sex`. Given the data collected in KYC is verified through identity documents such as passports it probably makes most sense to mirror those and stick to the biological focus. i.e. If a field is added, have the field be `sex`.

cc @lydiat @JakeUrban Thoughts?

**Comment by ymatienzo** [comment]
> this document

**Comment by JakeUrban** [comment]
Sounds like a reasonable addition to the standard, thanks for filing @ymatienzo.
