### ISSUE TITLE
SEP-6: Integrate SEP-38

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#917]
Now that we have a standard for providing clients quotes between on and off chain assets, we should integrate this functionality into SEP-6.

For withdrawals, the user will provide the anchor with an on-chain asset A and receive a different off-chain asset B. For deposits, the reverse will occur. This will be made possible by the client fetching a quote and referencing the quote ID in the SEP-6 deposit or withdraw request.

**Comment by shanzzam** [comment]
Removing the stale label and putting this in Product Eng team backlog for planning
