### ISSUE TITLE
SEP-6 & 24: Allow 'account' deposit & withdraw parameters different than authenticated account

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#958]
We're seeing ecosystem demand for the ability to authenticate a Stellar account via SEP-10 while specifying a different Stellar  account in `/deposit` & `/withdraw` requests.

The idea is that the account authenticated via SEP-10 (the 'authenticated account') should be associated with the KYC data collected, while the account sent in `/deposit` and `/withdraw` requests (the 'account parameter') is the account the anchor should send funds to or expect to receive funds from, respectively.

This request is distinct from the ability to use a shared Stellar account in SEP-10 authentication, as described in #726 

cc @leighmcculloch @tomerweller

**Comment by leighmcculloch** [comment]
How does the anchor have any confidence over who they're sending money to or receiving money from if the accounts they send to or receive from have not been authenticated? This seems to me like it would make it trivial for a person KYC'd to help an anchor send funds to someone the anchor has not KYC'd.

**Comment by JakeUrban** [comment]
I agree @leighmcculloch, my thought was that the anchor could also require KYC for the second account too, but in the use case that started inspired this issue, this account cannot sign SEP-10 challenge transactions. Without the ability to sign challenge transactions, the anchor would need to collect KYC outside an interoperability standard, so I'm not thrilled with this idea.

**Comment by leighmcculloch** [comment]
Ah gotcha, so the authenticated account would provide information for the third party account, and the anchor trusts that what the authenticated account has to say about the third party account is legit? If that's sufficient then I think it sounds okay.

I think we need some input on the non-technical aspects of this.

**Comment by JakeUrban** [comment]
closing as a duplicate of #958
