### ISSUE TITLE
SEP-12: Clarify `fields` and `field.status` ambiguity 

### ISSUE THREAD

**Issue by JakeUrban** [stellar/stellar-protocol#981]
related to stellar/stellar-demo-wallet#189

This issue is for discussion what steps to take in order to clarify the issues mentioned below.

The changes made for the [property verification](https://github.com/stellar/stellar-protocol/commit/2d46fe87fa9aa512610078eda51dc52573ed754b) functionality introduces some variability in the `GET /customer` response, specifically related to the presence of the `fields` and field-level `status` properties.

The commit clarified that `fields` may be present for all customer statuses, not just `NEEDS_INFO`. However, there is no reason for `fields` to be present for other customer statuses unless the field-level `status` properties are present.

Field-level `status` properties are optional, but its not clear what the client should assume if the property is omitted. Most importantly, **clients used to be able to assume all fields present needed to be collected, but that is no longer the case if field-level status values are not `NOT_PROVIDED`.**

That last point is a breaking change that we missed when making the change.

cc @leighmcculloch

**Comment by leighmcculloch** [comment]
Interesting. We made a breaking change, is that a bug? If so we can probably change fix that bug with a patch change. Do we know if anyone is dependent on that buggy logic?

I don't feel strongly for how we resolve the fields presence though. I can see arguments for both approaches. It could be confusing if someone can't see the final status for a field when the status changes to needs info to something else. Especially if the user is rejected and the server wishes to signal which field was rejected and related to the overall rejection.

**Comment by JakeUrban** [comment]
The change was made 2 months ago, and I'm not aware of any service who has implemented SEP-12 in that timeframe but its possible someone has.

The only way I can think of that ensures existing SEP-12 clients consume the response properly is by maintaining the rule that `fields` in a `NEEDS_INFO` response can only be for fields the anchor has not yet received. But this is directly at odds with what we're trying to achieve: letting the anchor signal that verification is required for a field that has already been provided. I also think its confusing to limit the fields listed in a `NEEDS_INFO` response but allow all fields to be listed for customers in other statuses.

**Comment by leighmcculloch** [comment]
> this is directly at odds with what we're trying to achieve: letting the anchor signal that verification is required for a field that has already been provided

🤔 We could create a new `fields` that contains the new behavior and keep the old `fields` as is. Wdyt?

**Comment by JakeUrban** [comment]
I think thats the best we can do. We can use the original `fields` as an object containing the fields not yet provided, and a `providedFields`/`collectedFields` object that contains fields that the anchor has on their end already. This new object should be the one with field `status` attributes, since `status: NOT_PROVIDED` is redundant for fields in the original object.

**Comment by leighmcculloch** [comment]
I was struggling to find a concept that could differentiate the two, but I really like the distinction you propose. `providedFields` sounds good to me.
